from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Context import Context

class AdwHomeBadger:
    INTENT_UPDATE_COUNTER: ClassVar[str]
    PACKAGENAME: ClassVar[str]
    CLASSNAME: ClassVar[str]
    COUNT: ClassVar[str]
    def __init__(self) -> None: ...
    def getSupportLaunchers(self) -> list: ...
    def executeBadge(self, p0: Context, p1: ComponentName, p2: int) -> None: ...

from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Context import Context

class ApexHomeBadger:
    def __init__(self) -> None: ...
    def getSupportLaunchers(self) -> list: ...
    def executeBadge(self, p0: Context, p1: ComponentName, p2: int) -> None: ...

from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Context import Context

class AsusHomeBadger:
    def __init__(self) -> None: ...
    def getSupportLaunchers(self) -> list: ...
    def executeBadge(self, p0: Context, p1: ComponentName, p2: int) -> None: ...

from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Context import Context

class DefaultBadger:
    def __init__(self) -> None: ...
    def getSupportLaunchers(self) -> list: ...
    def executeBadge(self, p0: Context, p1: ComponentName, p2: int) -> None: ...

from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Context import Context

class EverythingMeHomeBadger:
    def __init__(self) -> None: ...
    def getSupportLaunchers(self) -> list: ...
    def executeBadge(self, p0: Context, p1: ComponentName, p2: int) -> None: ...

from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Context import Context

class HuaweiHomeBadger:
    def __init__(self) -> None: ...
    def getSupportLaunchers(self) -> list: ...
    def executeBadge(self, p0: Context, p1: ComponentName, p2: int) -> None: ...

from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Context import Context

class LGHomeBadger:
    def __init__(self) -> None: ...
    def getSupportLaunchers(self) -> list: ...
    def executeBadge(self, p0: Context, p1: ComponentName, p2: int) -> None: ...

from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Context import Context

class NewHtcHomeBadger:
    INTENT_UPDATE_SHORTCUT: ClassVar[str]
    INTENT_SET_NOTIFICATION: ClassVar[str]
    PACKAGENAME: ClassVar[str]
    COUNT: ClassVar[str]
    EXTRA_COMPONENT: ClassVar[str]
    EXTRA_COUNT: ClassVar[str]
    def __init__(self) -> None: ...
    def getSupportLaunchers(self) -> list: ...
    def executeBadge(self, p0: Context, p1: ComponentName, p2: int) -> None: ...

from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Context import Context

class NovaHomeBadger:
    def __init__(self) -> None: ...
    def getSupportLaunchers(self) -> list: ...
    def executeBadge(self, p0: Context, p1: ComponentName, p2: int) -> None: ...

from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Context import Context

class OPPOHomeBader:
    def __init__(self) -> None: ...
    def getSupportLaunchers(self) -> list: ...
    def executeBadge(self, p0: Context, p1: ComponentName, p2: int) -> None: ...

from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Context import Context

class SamsungHomeBadger:
    def __init__(self) -> None: ...
    def getSupportLaunchers(self) -> list: ...
    def executeBadge(self, p0: Context, p1: ComponentName, p2: int) -> None: ...

from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Context import Context

class SonyHomeBadger:
    def __init__(self) -> None: ...
    def getSupportLaunchers(self) -> list: ...
    def executeBadge(self, p0: Context, p1: ComponentName, p2: int) -> None: ...

from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Context import Context

class VivoHomeBadger:
    def __init__(self) -> None: ...
    def getSupportLaunchers(self) -> list: ...
    def executeBadge(self, p0: Context, p1: ComponentName, p2: int) -> None: ...

from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Context import Context

class XiaomiHomeBadger:
    INTENT_ACTION: ClassVar[str]
    EXTRA_UPDATE_APP_COMPONENT_NAME: ClassVar[str]
    EXTRA_UPDATE_APP_MSG_TEXT: ClassVar[str]
    def __init__(self) -> None: ...
    def getSupportLaunchers(self) -> list: ...
    def executeBadge(self, p0: Context, p1: ComponentName, p2: int) -> None: ...

from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Context import Context

class ZukHomeBadger:
    def __init__(self) -> None: ...
    def getSupportLaunchers(self) -> list: ...
    def executeBadge(self, p0: Context, p1: ComponentName, p2: int) -> None: ...

