from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

class InitState(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/internal/InitState"
    NOT_STARTED = JavaStaticField("Lcom/onesignal/internal/InitState;")
    IN_PROGRESS = JavaStaticField("Lcom/onesignal/internal/InitState;")
    SUCCESS = JavaStaticField("Lcom/onesignal/internal/InitState;")
    FAILED = JavaStaticField("Lcom/onesignal/internal/InitState;")
    values = JavaStaticMethod("()[Lcom/onesignal/internal/InitState;")
    valueOf = JavaStaticMethod("(Ljava/lang/String;)Lcom/onesignal/internal/InitState;")
    getEntries = JavaStaticMethod("()Lkotlin/enums/EnumEntries;")
    isSDKAccessible = JavaMethod("()Z")
    NOT_STARTED = JavaStaticField("Lcom/onesignal/internal/InitState;")
    IN_PROGRESS = JavaStaticField("Lcom/onesignal/internal/InitState;")
    SUCCESS = JavaStaticField("Lcom/onesignal/internal/InitState;")
    FAILED = JavaStaticField("Lcom/onesignal/internal/InitState;")

class OneSignalImp(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/internal/OneSignalImp"
    __javaconstructor__ = [("()V", False), ("(Lkotlinx/coroutines/CoroutineDispatcher;ILkotlin/jvm/internal/DefaultConstructorMarker;)V", False), ("(Lkotlinx/coroutines/CoroutineDispatcher;)V", False)]
    getLocation = JavaMultipleMethod([("()Lcom/onesignal/location/ILocationManager;", False, False), ("(Lkotlin/coroutines/Continuation;)Ljava/lang/Object;", False, False)])
    getDebug = JavaMethod("()Lcom/onesignal/debug/IDebugManager;")
    getService = JavaMethod("(Ljava/lang/Class;)Ljava/lang/Object;")
    getServiceOrNull = JavaMethod("(Ljava/lang/Class;)Ljava/lang/Object;")
    hasService = JavaMethod("(Ljava/lang/Class;)Z")
    getAllServices = JavaMethod("(Ljava/lang/Class;)Ljava/util/List;")
    login = JavaMultipleMethod([("(Ljava/lang/String;)V", False, False), ("(Ljava/lang/String;Ljava/lang/String;)V", False, False)])
    logout = JavaMethod("()V")
    getUser = JavaMultipleMethod([("()Lcom/onesignal/user/IUserManager;", False, False), ("(Lkotlin/coroutines/Continuation;)Ljava/lang/Object;", False, False)])
    getSession = JavaMultipleMethod([("(Lkotlin/coroutines/Continuation;)Ljava/lang/Object;", False, False), ("()Lcom/onesignal/session/ISessionManager;", False, False)])
    isInitialized = JavaMethod("()Z")
    getDisableGMSMissingPrompt = JavaMultipleMethod([("(Lkotlin/coroutines/Continuation;)Ljava/lang/Object;", False, False), ("()Z", False, False)])
    getSdkVersion = JavaMethod("()Ljava/lang/String;")
    getNotifications = JavaMultipleMethod([("(Lkotlin/coroutines/Continuation;)Ljava/lang/Object;", False, False), ("()Lcom/onesignal/notifications/INotificationsManager;", False, False)])
    getInAppMessages = JavaMultipleMethod([("(Lkotlin/coroutines/Continuation;)Ljava/lang/Object;", False, False), ("()Lcom/onesignal/inAppMessages/IInAppMessagesManager;", False, False)])
    getConsentRequired = JavaMultipleMethod([("()Z", False, False), ("(Lkotlin/coroutines/Continuation;)Ljava/lang/Object;", False, False)])
    setConsentRequired = JavaMultipleMethod([("(Z)V", False, False), ("(ZLkotlin/coroutines/Continuation;)Ljava/lang/Object;", False, False)])
    getConsentGiven = JavaMultipleMethod([("()Z", False, False), ("(Lkotlin/coroutines/Continuation;)Ljava/lang/Object;", False, False)])
    setConsentGiven = JavaMultipleMethod([("(Z)V", False, False), ("(ZLkotlin/coroutines/Continuation;)Ljava/lang/Object;", False, False)])
    setDisableGMSMissingPrompt = JavaMultipleMethod([("(Z)V", False, False), ("(ZLkotlin/coroutines/Continuation;)Ljava/lang/Object;", False, False)])
    initWithContext = JavaMultipleMethod([("(Landroid/content/Context;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;", False, False), ("(Landroid/content/Context;Ljava/lang/String;)Z", False, False)])
    updateUserJwt = JavaMethod("(Ljava/lang/String;Ljava/lang/String;)V")
    addUserJwtInvalidatedListener = JavaMethod("(Lcom/onesignal/IUserJwtInvalidatedListener;)V")
    removeUserJwtInvalidatedListener = JavaMethod("(Lcom/onesignal/IUserJwtInvalidatedListener;)V")
    initWithContextSuspend = JavaMethod("(Landroid/content/Context;Ljava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;")
    loginSuspend = JavaMethod("(Ljava/lang/String;Ljava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;")
    logoutSuspend = JavaMethod("(Lkotlin/coroutines/Continuation;)Ljava/lang/Object;")
    updateUserJwtSuspend = JavaMethod("(Ljava/lang/String;Ljava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;")
    access$getServices$p = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;)Lcom/onesignal/common/services/ServiceProvider;")
    access$getConfigModel = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;)Lcom/onesignal/core/internal/config/ConfigModel;")
    access$get_consentRequired$p = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;)Ljava/lang/Boolean;")
    access$get_consentGiven$p = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;)Ljava/lang/Boolean;")
    access$get_disableGMSMissingPrompt$p = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;)Ljava/lang/Boolean;")
    access$internalInit = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;Landroid/content/Context;Ljava/lang/String;)Z")
    access$getLoginHelper = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;)Lcom/onesignal/user/internal/LoginHelper;")
    access$getLogoutHelper = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;)Lcom/onesignal/user/internal/LogoutHelper;")
    access$waitUntilInitInternal = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;Ljava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;")
    access$suspendUntilInit = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;Ljava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;")
    access$suspendAndReturn = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;Lkotlin/jvm/functions/Function0;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;")
    access$set_consentRequired$p = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;Ljava/lang/Boolean;)V")
    access$set_consentGiven$p = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;Ljava/lang/Boolean;)V")
    access$getOperationRepo = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;)Lcom/onesignal/core/internal/operations/IOperationRepo;")
    access$set_disableGMSMissingPrompt$p = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;Ljava/lang/Boolean;)V")
    access$getInitLock$p = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;)Ljava/lang/Object;")
    access$getInitState$p = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;)Lcom/onesignal/internal/InitState;")
    access$getSuspendCompletion$p = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;)Lkotlinx/coroutines/CompletableDeferred;")
    access$setInitState$p = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;Lcom/onesignal/internal/InitState;)V")
    access$setSuspendCompletion$p = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;Lkotlinx/coroutines/CompletableDeferred;)V")
    access$setInitFailureException$p = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;Ljava/lang/Exception;)V")
    access$getJwtTokenStore = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;)Lcom/onesignal/user/internal/jwt/JwtTokenStore;")
    access$getIdentityModelStore = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;)Lcom/onesignal/user/internal/identity/IdentityModelStore;")
    access$getPropertiesModelStore = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;)Lcom/onesignal/user/internal/properties/PropertiesModelStore;")
    access$getSubscriptionModelStore = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;)Lcom/onesignal/user/internal/subscriptions/SubscriptionModelStore;")
    access$getPreferencesService = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;)Lcom/onesignal/core/internal/preferences/IPreferencesService;")
    access$getUserSwitcher = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;)Lcom/onesignal/user/internal/UserSwitcher;")
    access$getLoginLogoutLock$p = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;)Ljava/lang/Object;")
    access$getIdentityVerificationService = JavaStaticMethod("(Lcom/onesignal/internal/OneSignalImp;)Lcom/onesignal/core/internal/config/impl/IdentityVerificationService;")

    class WhenMappings(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "com/onesignal/internal/OneSignalImp$WhenMappings"
        $EnumSwitchMapping$0 = JavaStaticField("[I")

class OtelConfig(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/internal/OtelConfig"
    __javaconstructor__ = [("(ZLcom/onesignal/debug/LogLevel;)V", False)]
    Companion = JavaStaticField("Lcom/onesignal/internal/OtelConfig$Companion;")
    copy$default = JavaStaticMethod("(Lcom/onesignal/internal/OtelConfig;ZLcom/onesignal/debug/LogLevel;ILjava/lang/Object;)Lcom/onesignal/internal/OtelConfig;")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    isEnabled = JavaMethod("()Z")
    copy = JavaMethod("(ZLcom/onesignal/debug/LogLevel;)Lcom/onesignal/internal/OtelConfig;")
    getLogLevel = JavaMethod("()Lcom/onesignal/debug/LogLevel;")
    component1 = JavaMethod("()Z")
    component2 = JavaMethod("()Lcom/onesignal/debug/LogLevel;")
    access$getDISABLED$cp = JavaStaticMethod("()Lcom/onesignal/internal/OtelConfig;")

    class Companion(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "com/onesignal/internal/OtelConfig$Companion"
        __javaconstructor__ = [("(Lkotlin/jvm/internal/DefaultConstructorMarker;)V", False)]
        getDISABLED = JavaMethod("()Lcom/onesignal/internal/OtelConfig;")

class OtelConfigAction(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/internal/OtelConfigAction"
    __javaconstructor__ = [("(Lkotlin/jvm/internal/DefaultConstructorMarker;)V", False)]

    class Disable(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "com/onesignal/internal/OtelConfigAction$Disable"
        INSTANCE = JavaStaticField("Lcom/onesignal/internal/OtelConfigAction$Disable;")

    class Enable(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "com/onesignal/internal/OtelConfigAction$Enable"
        __javaconstructor__ = [("(Lcom/onesignal/debug/LogLevel;)V", False)]
        copy$default = JavaStaticMethod("(Lcom/onesignal/internal/OtelConfigAction$Enable;Lcom/onesignal/debug/LogLevel;ILjava/lang/Object;)Lcom/onesignal/internal/OtelConfigAction$Enable;")
        equals = JavaMethod("(Ljava/lang/Object;)Z")
        toString = JavaMethod("()Ljava/lang/String;")
        hashCode = JavaMethod("()I")
        copy = JavaMethod("(Lcom/onesignal/debug/LogLevel;)Lcom/onesignal/internal/OtelConfigAction$Enable;")
        getLogLevel = JavaMethod("()Lcom/onesignal/debug/LogLevel;")
        component1 = JavaMethod("()Lcom/onesignal/debug/LogLevel;")

    class NoChange(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "com/onesignal/internal/OtelConfigAction$NoChange"
        INSTANCE = JavaStaticField("Lcom/onesignal/internal/OtelConfigAction$NoChange;")

    class UpdateLogLevel(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "com/onesignal/internal/OtelConfigAction$UpdateLogLevel"
        __javaconstructor__ = [("(Lcom/onesignal/debug/LogLevel;Lcom/onesignal/debug/LogLevel;)V", False)]
        copy$default = JavaStaticMethod("(Lcom/onesignal/internal/OtelConfigAction$UpdateLogLevel;Lcom/onesignal/debug/LogLevel;Lcom/onesignal/debug/LogLevel;ILjava/lang/Object;)Lcom/onesignal/internal/OtelConfigAction$UpdateLogLevel;")
        equals = JavaMethod("(Ljava/lang/Object;)Z")
        toString = JavaMethod("()Ljava/lang/String;")
        hashCode = JavaMethod("()I")
        copy = JavaMethod("(Lcom/onesignal/debug/LogLevel;Lcom/onesignal/debug/LogLevel;)Lcom/onesignal/internal/OtelConfigAction$UpdateLogLevel;")
        getOldLevel = JavaMethod("()Lcom/onesignal/debug/LogLevel;")
        getNewLevel = JavaMethod("()Lcom/onesignal/debug/LogLevel;")
        component1 = JavaMethod("()Lcom/onesignal/debug/LogLevel;")
        component2 = JavaMethod("()Lcom/onesignal/debug/LogLevel;")

class OtelConfigEvaluator(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/internal/OtelConfigEvaluator"
    INSTANCE = JavaStaticField("Lcom/onesignal/internal/OtelConfigEvaluator;")
    evaluate = JavaMethod("(Lcom/onesignal/internal/OtelConfig;Lcom/onesignal/internal/OtelConfig;)Lcom/onesignal/internal/OtelConfigAction;")

class OtelLifecycleManager(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/internal/OtelLifecycleManager"
    __javaconstructor__ = [("(Landroid/content/Context;Lkotlin/jvm/functions/Function0;Lkotlin/jvm/functions/Function3;Lkotlin/jvm/functions/Function4;Lkotlin/jvm/functions/Function1;Lkotlin/jvm/functions/Function2;Lkotlin/jvm/functions/Function0;)V", False), ("(Landroid/content/Context;Lkotlin/jvm/functions/Function0;Lkotlin/jvm/functions/Function3;Lkotlin/jvm/functions/Function4;Lkotlin/jvm/functions/Function1;Lkotlin/jvm/functions/Function2;Lkotlin/jvm/functions/Function0;ILkotlin/jvm/internal/DefaultConstructorMarker;)V", False)]
    onModelUpdated = JavaMethod("(Lcom/onesignal/common/modeling/ModelChangedArgs;Ljava/lang/String;)V")
    onModelReplaced = JavaMultipleMethod([("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;)V", False, False), ("(Lcom/onesignal/core/internal/config/ConfigModel;Ljava/lang/String;)V", False, False)])
    access$getPlatformProviderFactory$p = JavaStaticMethod("(Lcom/onesignal/internal/OtelLifecycleManager;)Lkotlin/jvm/functions/Function2;")
    access$getContext$p = JavaStaticMethod("(Lcom/onesignal/internal/OtelLifecycleManager;)Landroid/content/Context;")
    access$getFeatureManagerProvider$p = JavaStaticMethod("(Lcom/onesignal/internal/OtelLifecycleManager;)Lkotlin/jvm/functions/Function0;")
    access$getLoggerFactory$p = JavaStaticMethod("(Lcom/onesignal/internal/OtelLifecycleManager;)Lkotlin/jvm/functions/Function0;")
    initializeFromCachedConfig = JavaMethod("()V")
    subscribeToConfigStore = JavaMethod("(Lcom/onesignal/core/internal/config/ConfigModelStore;)V")