from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class DefaultConstructorMarker:
    """Forward declaration for ``kotlin.jvm.internal.DefaultConstructorMarker``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.internal.DefaultConstructorMarker')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/internal/DefaultConstructorMarker/
    """
    ...

class BackgroundImageLayout:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str, p2: str, p3: int, p4: DefaultConstructorMarker) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str, p2: str) -> None: ...
    def getImage(self) -> str: ...
    def getTitleTextColor(self) -> str: ...
    def getBodyTextColor(self) -> str: ...

from typing import Any, ClassVar, overload

class IActionButton:
    def getIcon(self) -> str: ...
    def getText(self) -> str: ...
    def getId(self) -> str: ...

from typing import Any, ClassVar, overload

class IDisplayableMutableNotification:
    ...

from typing import Any, ClassVar, overload

class IDisplayableNotification:
    def display(self) -> None: ...

from typing import Any, ClassVar, overload

class IMutableNotification:
    def setExtender(self, p0: Any) -> None: ...

from typing import Any, ClassVar, overload
from notifications.BackgroundImageLayout import BackgroundImageLayout

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONObject:
    """Forward declaration for ``org.json.JSONObject``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONObject')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class INotification:
    def getTtl(self) -> int: ...
    def getAndroidNotificationId(self) -> int: ...
    def getNotificationId(self) -> str: ...
    def getTemplateName(self) -> str: ...
    def getTemplateId(self) -> str: ...
    def getBody(self) -> str: ...
    def getAdditionalData(self) -> JSONObject: ...
    def getSmallIcon(self) -> str: ...
    def getLargeIcon(self) -> str: ...
    def getBigPicture(self) -> str: ...
    def getSmallIconAccentColor(self) -> str: ...
    def getLaunchURL(self) -> str: ...
    def getSound(self) -> str: ...
    def getLedColor(self) -> str: ...
    def getLockScreenVisibility(self) -> int: ...
    def getGroupKey(self) -> str: ...
    def getGroupMessage(self) -> str: ...
    def getActionButtons(self) -> list: ...
    def getFromProjectNumber(self) -> str: ...
    def getBackgroundImageLayout(self) -> BackgroundImageLayout: ...
    def getCollapseId(self) -> str: ...
    def getSentTime(self) -> int: ...
    def getGroupedNotifications(self) -> list: ...
    def getRawPayload(self) -> str: ...
    def getTitle(self) -> str: ...
    def getPriority(self) -> int: ...

    class DefaultImpls:
        @staticmethod
        def getBackgroundImageLayout$annotations() -> None: ...

from typing import Any, ClassVar, overload
from notifications.INotification import INotification
from notifications.INotificationClickResult import INotificationClickResult

class INotificationClickEvent:
    def getNotification(self) -> INotification: ...
    def getResult(self) -> INotificationClickResult: ...

from typing import Any, ClassVar, overload
from notifications.INotificationClickEvent import INotificationClickEvent

class INotificationClickListener:
    def onClick(self, p0: INotificationClickEvent) -> None: ...

from typing import Any, ClassVar, overload

class INotificationClickResult:
    def getUrl(self) -> str: ...
    def getActionId(self) -> str: ...

from typing import Any, ClassVar, overload
from notifications.INotificationWillDisplayEvent import INotificationWillDisplayEvent

class INotificationLifecycleListener:
    def onWillDisplay(self, p0: INotificationWillDisplayEvent) -> None: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from notifications.IDisplayableMutableNotification import IDisplayableMutableNotification

class INotificationReceivedEvent:
    def getContext(self) -> Context: ...
    @overload
    def preventDefault(self, p0: bool) -> None: ...
    @overload
    def preventDefault(self) -> None: ...
    def getNotification(self) -> IDisplayableMutableNotification: ...

from typing import Any, ClassVar, overload
from notifications.INotificationReceivedEvent import INotificationReceivedEvent

class INotificationServiceExtension:
    def onNotificationReceived(self, p0: INotificationReceivedEvent) -> None: ...

from typing import Any, ClassVar, overload
from notifications.IDisplayableNotification import IDisplayableNotification

class INotificationWillDisplayEvent:
    @overload
    def preventDefault(self) -> None: ...
    @overload
    def preventDefault(self, p0: bool) -> None: ...
    def getNotification(self) -> IDisplayableNotification: ...

from typing import Any, ClassVar, overload
from notifications.INotificationClickListener import INotificationClickListener
from notifications.INotificationLifecycleListener import INotificationLifecycleListener
from notifications.IPermissionObserver import IPermissionObserver

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Continuation:
    """Forward declaration for ``kotlin.coroutines.Continuation``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.coroutines.Continuation')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/coroutines/Continuation/
    """
    ...

class INotificationsManager:
    def getCanRequestPermission(self) -> bool: ...
    def requestPermission(self, p0: bool, p1: Continuation) -> Any: ...
    def removeNotification(self, p0: int) -> None: ...
    def removeGroupedNotifications(self, p0: str) -> None: ...
    def clearAllNotifications(self) -> None: ...
    def addPermissionObserver(self, p0: IPermissionObserver) -> None: ...
    def removePermissionObserver(self, p0: IPermissionObserver) -> None: ...
    def addForegroundLifecycleListener(self, p0: INotificationLifecycleListener) -> None: ...
    def removeForegroundLifecycleListener(self, p0: INotificationLifecycleListener) -> None: ...
    def addClickListener(self, p0: INotificationClickListener) -> None: ...
    def removeClickListener(self, p0: INotificationClickListener) -> None: ...
    def getPermission(self) -> bool: ...

from typing import Any, ClassVar, overload

class IPermissionObserver:
    def onNotificationPermissionChange(self, p0: bool) -> None: ...

