from typing import Any, ClassVar, overload

class ISessionManager:
    def addOutcome(self, p0: str) -> None: ...
    def addUniqueOutcome(self, p0: str) -> None: ...
    def addOutcomeWithValue(self, p0: str, p1: float) -> None: ...

from typing import Any, ClassVar, overload
from common.services.ServiceBuilder import ServiceBuilder

class SessionModule:
    def __init__(self) -> None: ...
    def register(self, p0: ServiceBuilder) -> None: ...

