from typing import Any, ClassVar, overload
from user.state.IUserStateObserver import IUserStateObserver
from user.subscriptions.IPushSubscription import IPushSubscription

class IUserManager:
    def getPushSubscription(self) -> IPushSubscription: ...
    def getOnesignalId(self) -> str: ...
    def getExternalId(self) -> str: ...
    def setLanguage(self, p0: str) -> None: ...
    def addAlias(self, p0: str, p1: str) -> None: ...
    def addAliases(self, p0: dict) -> None: ...
    def removeAlias(self, p0: str) -> None: ...
    def removeAliases(self, p0: list) -> None: ...
    def addEmail(self, p0: str) -> None: ...
    def removeEmail(self, p0: str) -> None: ...
    def addSms(self, p0: str) -> None: ...
    def removeSms(self, p0: str) -> None: ...
    def addTag(self, p0: str, p1: str) -> None: ...
    def addTags(self, p0: dict) -> None: ...
    def removeTag(self, p0: str) -> None: ...
    def removeTags(self, p0: list) -> None: ...
    def getTags(self) -> dict: ...
    def addObserver(self, p0: IUserStateObserver) -> None: ...
    def removeObserver(self, p0: IUserStateObserver) -> None: ...
    def trackEvent(self, p0: str, p1: dict) -> None: ...

    class DefaultImpls:
        @staticmethod
        def trackEvent$default(p0: "IUserManager", p1: str, p2: dict, p3: int, p4: Any) -> None: ...

from typing import Any, ClassVar, overload
from common.services.ServiceBuilder import ServiceBuilder

class UserModule:
    def __init__(self) -> None: ...
    def register(self, p0: ServiceBuilder) -> None: ...

