from typing import Any, ClassVar, overload
from common.modeling.Model import Model
from common.modeling.ModelChangedArgs import ModelChangedArgs
from core.internal.application.IApplicationService import IApplicationService
from session.internal.session.ISessionService import ISessionService
from user.internal.subscriptions.ISubscriptionChangedHandler import ISubscriptionChangedHandler
from user.internal.subscriptions.SubscriptionList import SubscriptionList
from user.internal.subscriptions.SubscriptionModel import SubscriptionModel
from user.internal.subscriptions.SubscriptionModelStore import SubscriptionModelStore
from user.internal.subscriptions.SubscriptionStatus import SubscriptionStatus

class SubscriptionManager:
    def __init__(self, p0: IApplicationService, p1: ISessionService, p2: SubscriptionModelStore) -> None: ...
    def getHasSubscribers(self) -> bool: ...
    @overload
    def subscribe(self, p0: ISubscriptionChangedHandler) -> None: ...
    @overload
    def subscribe(self, p0: Any) -> None: ...
    @overload
    def unsubscribe(self, p0: ISubscriptionChangedHandler) -> None: ...
    @overload
    def unsubscribe(self, p0: Any) -> None: ...
    @overload
    def onModelAdded(self, p0: SubscriptionModel, p1: str) -> None: ...
    @overload
    def onModelAdded(self, p0: Model, p1: str) -> None: ...
    def onModelUpdated(self, p0: ModelChangedArgs, p1: str) -> None: ...
    @overload
    def onModelRemoved(self, p0: SubscriptionModel, p1: str) -> None: ...
    @overload
    def onModelRemoved(self, p0: Model, p1: str) -> None: ...
    def getSubscriptions(self) -> SubscriptionList: ...
    def getPushSubscriptionModel(self) -> SubscriptionModel: ...
    def setSubscriptions(self, p0: SubscriptionList) -> None: ...
    def addEmailSubscription(self, p0: str) -> None: ...
    def addOrUpdatePushSubscriptionToken(self, p0: str, p1: SubscriptionStatus) -> None: ...
    def addSmsSubscription(self, p0: str) -> None: ...
    def removeEmailSubscription(self, p0: str) -> None: ...
    def removeSmsSubscription(self, p0: str) -> None: ...
    def onSessionStarted(self) -> None: ...
    def onSessionActive(self) -> None: ...
    def onSessionEnded(self, p0: int) -> None: ...

    class WhenMappings:
        $EnumSwitchMapping$0: ClassVar[Any]

