from typing import Any, ClassVar, overload
from core.internal.application.IApplicationService import IApplicationService
from debug.ILogListener import ILogListener
from debug.LogLevel import LogLevel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Throwable:
    """Forward declaration for ``java.lang.Throwable``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.lang.Throwable')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html
    """
    ...
class IOtelOpenTelemetryRemote:
    """Forward declaration for ``com.onesignal.otel.IOtelOpenTelemetryRemote``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.onesignal.otel.IOtelOpenTelemetryRemote')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...
class Function1:
    """Forward declaration for ``kotlin.jvm.functions.Function1``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.functions.Function1')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/functions/Function1/
    """
    ...

class Logging:
    INSTANCE: ClassVar["Logging"]
    @staticmethod
    def getVisualLogLevel() -> LogLevel: ...
    def addListener(self, p0: ILogListener) -> None: ...
    @staticmethod
    def setVisualLogLevel(p0: LogLevel) -> None: ...
    def removeListener(self, p0: ILogListener) -> None: ...
    @staticmethod
    def getLogLevel() -> LogLevel: ...
    @staticmethod
    def setLogLevel(p0: LogLevel) -> None: ...
    @staticmethod
    def error(p0: str, p1: Throwable) -> None: ...
    @overload
    @staticmethod
    def log(p0: LogLevel, p1: str) -> None: ...
    @overload
    @staticmethod
    def log(p0: LogLevel, p1: str, p2: Throwable) -> None: ...
    @staticmethod
    def info(p0: str, p1: Throwable) -> None: ...
    @staticmethod
    def debug(p0: str, p1: Throwable) -> None: ...
    @staticmethod
    def error$default(p0: str, p1: Throwable, p2: int, p3: Any) -> None: ...
    @staticmethod
    def info$default(p0: str, p1: Throwable, p2: int, p3: Any) -> None: ...
    @staticmethod
    def verbose(p0: str, p1: Throwable) -> None: ...
    @staticmethod
    def debug$default(p0: str, p1: Throwable, p2: int, p3: Any) -> None: ...
    @staticmethod
    def atLogLevel(p0: LogLevel) -> bool: ...
    @staticmethod
    def fatal(p0: str, p1: Throwable) -> None: ...
    def getApplicationService(self) -> IApplicationService: ...
    def setApplicationService(self, p0: IApplicationService) -> None: ...
    def setOtelTelemetry(self, p0: IOtelOpenTelemetryRemote, p1: Function1) -> None: ...
    @staticmethod
    def setOtelTelemetry$default(p0: "Logging", p1: IOtelOpenTelemetryRemote, p2: Function1, p3: int, p4: Any) -> None: ...
    @staticmethod
    def getLogLevel$annotations() -> None: ...
    @staticmethod
    def getVisualLogLevel$annotations() -> None: ...
    @staticmethod
    def fatal$default(p0: str, p1: Throwable, p2: int, p3: Any) -> None: ...
    @staticmethod
    def verbose$default(p0: str, p1: Throwable, p2: int, p3: Any) -> None: ...
    @staticmethod
    def warn$default(p0: str, p1: Throwable, p2: int, p3: Any) -> None: ...
    @staticmethod
    def warn(p0: str, p1: Throwable) -> None: ...

    class WhenMappings:
        $EnumSwitchMapping$0: ClassVar[Any]

