from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

class INotificationActivityOpener(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/notifications/internal/INotificationActivityOpener"
    openDestinationActivity = JavaMethod("(Landroid/app/Activity;Lorg/json/JSONArray;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;")

class Notification(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/notifications/internal/Notification"
    __javaconstructor__ = [("(Lorg/json/JSONObject;Lcom/onesignal/core/internal/time/ITime;)V", False), ("(Ljava/util/List;Lorg/json/JSONObject;ILcom/onesignal/core/internal/time/ITime;)V", False)]
    toString = JavaMethod("()Ljava/lang/String;")
    setPriority = JavaMethod("(I)V")
    getPriority = JavaMethod("()I")
    display = JavaMethod("()V")
    getTitle = JavaMethod("()Ljava/lang/String;")
    setTitle = JavaMethod("(Ljava/lang/String;)V")
    toJSONObject = JavaMethod("()Lorg/json/JSONObject;")
    getTtl = JavaMethod("()I")
    setTtl = JavaMethod("(I)V")
    getNotificationExtender = JavaMethod("()Landroidx/core/app/NotificationCompat$Extender;")
    setNotificationExtender = JavaMethod("(Landroidx/core/app/NotificationCompat$Extender;)V")
    getDisplayWaiter = JavaMethod("()Lcom/onesignal/common/threading/WaiterWithValue;")
    getGroupedNotifications = JavaMethod("()Ljava/util/List;")
    setGroupedNotifications = JavaMethod("(Ljava/util/List;)V")
    getAndroidNotificationId = JavaMethod("()I")
    setAndroidNotificationId = JavaMethod("(I)V")
    getNotificationId = JavaMethod("()Ljava/lang/String;")
    setNotificationId = JavaMethod("(Ljava/lang/String;)V")
    getTemplateName = JavaMethod("()Ljava/lang/String;")
    setTemplateName = JavaMethod("(Ljava/lang/String;)V")
    getTemplateId = JavaMethod("()Ljava/lang/String;")
    setTemplateId = JavaMethod("(Ljava/lang/String;)V")
    getBody = JavaMethod("()Ljava/lang/String;")
    setBody = JavaMethod("(Ljava/lang/String;)V")
    getAdditionalData = JavaMethod("()Lorg/json/JSONObject;")
    setAdditionalData = JavaMethod("(Lorg/json/JSONObject;)V")
    getSmallIcon = JavaMethod("()Ljava/lang/String;")
    setSmallIcon = JavaMethod("(Ljava/lang/String;)V")
    getLargeIcon = JavaMethod("()Ljava/lang/String;")
    setLargeIcon = JavaMethod("(Ljava/lang/String;)V")
    getBigPicture = JavaMethod("()Ljava/lang/String;")
    setBigPicture = JavaMethod("(Ljava/lang/String;)V")
    getSmallIconAccentColor = JavaMethod("()Ljava/lang/String;")
    setSmallIconAccentColor = JavaMethod("(Ljava/lang/String;)V")
    getLaunchURL = JavaMethod("()Ljava/lang/String;")
    setLaunchURL = JavaMethod("(Ljava/lang/String;)V")
    getSound = JavaMethod("()Ljava/lang/String;")
    setSound = JavaMethod("(Ljava/lang/String;)V")
    getLedColor = JavaMethod("()Ljava/lang/String;")
    setLedColor = JavaMethod("(Ljava/lang/String;)V")
    getLockScreenVisibility = JavaMethod("()I")
    setLockScreenVisibility = JavaMethod("(I)V")
    getGroupKey = JavaMethod("()Ljava/lang/String;")
    setGroupKey = JavaMethod("(Ljava/lang/String;)V")
    getGroupMessage = JavaMethod("()Ljava/lang/String;")
    setGroupMessage = JavaMethod("(Ljava/lang/String;)V")
    getActionButtons = JavaMethod("()Ljava/util/List;")
    setActionButtons = JavaMethod("(Ljava/util/List;)V")
    getFromProjectNumber = JavaMethod("()Ljava/lang/String;")
    setFromProjectNumber = JavaMethod("(Ljava/lang/String;)V")
    getBackgroundImageLayout = JavaMethod("()Lcom/onesignal/notifications/BackgroundImageLayout;")
    setBackgroundImageLayout = JavaMethod("(Lcom/onesignal/notifications/BackgroundImageLayout;)V")
    getCollapseId = JavaMethod("()Ljava/lang/String;")
    setCollapseId = JavaMethod("(Ljava/lang/String;)V")
    getSentTime = JavaMethod("()J")
    setSentTime = JavaMethod("(J)V")
    getRawPayload = JavaMethod("()Ljava/lang/String;")
    setRawPayload = JavaMethod("(Ljava/lang/String;)V")
    setExtender = JavaMethod("(Landroidx/core/app/NotificationCompat$Extender;)V")
    hasNotificationId = JavaMethod("()Z")

    class ActionButton(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "com/onesignal/notifications/internal/Notification$ActionButton"
        __javaconstructor__ = [("()V", False), ("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILkotlin/jvm/internal/DefaultConstructorMarker;)V", False), ("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V", False)]
        getId = JavaMethod("()Ljava/lang/String;")
        getText = JavaMethod("()Ljava/lang/String;")
        getIcon = JavaMethod("()Ljava/lang/String;")
        toJSONObject = JavaMethod("()Lorg/json/JSONObject;")

class NotificationClickEvent(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/notifications/internal/NotificationClickEvent"
    __javaconstructor__ = [("(Lcom/onesignal/notifications/internal/Notification;Lcom/onesignal/notifications/internal/NotificationClickResult;)V", False)]
    getNotification = JavaMethod("()Lcom/onesignal/notifications/INotification;")
    getResult = JavaMethod("()Lcom/onesignal/notifications/INotificationClickResult;")
    toJSONObject = JavaMethod("()Lorg/json/JSONObject;")

class NotificationClickResult(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/notifications/internal/NotificationClickResult"
    __javaconstructor__ = [("(Ljava/lang/String;Ljava/lang/String;)V", False)]
    getUrl = JavaMethod("()Ljava/lang/String;")
    getActionId = JavaMethod("()Ljava/lang/String;")
    toJSONObject = JavaMethod("()Lorg/json/JSONObject;")

class NotificationReceivedEvent(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/notifications/internal/NotificationReceivedEvent"
    __javaconstructor__ = [("(Landroid/content/Context;Lcom/onesignal/notifications/internal/Notification;)V", False)]
    getContext = JavaMethod("()Landroid/content/Context;")
    getNotification = JavaMultipleMethod([("()Lcom/onesignal/notifications/IDisplayableMutableNotification;", False, False), ("()Lcom/onesignal/notifications/internal/Notification;", False, False)])
    setPreventDefault = JavaMethod("(Z)V")
    getDiscard = JavaMethod("()Z")
    isPreventDefault = JavaMethod("()Z")
    setDiscard = JavaMethod("(Z)V")
    preventDefault = JavaMultipleMethod([("(Z)V", False, False), ("()V", False, False)])

class NotificationWillDisplayEvent(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/notifications/internal/NotificationWillDisplayEvent"
    __javaconstructor__ = [("(Lcom/onesignal/notifications/internal/Notification;)V", False)]
    getNotification = JavaMultipleMethod([("()Lcom/onesignal/notifications/IDisplayableNotification;", False, False), ("()Lcom/onesignal/notifications/internal/Notification;", False, False)])
    setPreventDefault = JavaMethod("(Z)V")
    getDiscard = JavaMethod("()Z")
    isPreventDefault = JavaMethod("()Z")
    setDiscard = JavaMethod("(Z)V")
    preventDefault = JavaMultipleMethod([("(Z)V", False, False), ("()V", False, False)])

class NotificationsManager(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/notifications/internal/NotificationsManager"
    __javaconstructor__ = [("(Lcom/onesignal/core/internal/application/IApplicationService;Lcom/onesignal/notifications/internal/permissions/INotificationPermissionController;Lcom/onesignal/notifications/internal/restoration/INotificationRestoreWorkManager;Lcom/onesignal/notifications/internal/lifecycle/INotificationLifecycleService;Lcom/onesignal/notifications/internal/data/INotificationRepository;Lcom/onesignal/notifications/internal/summary/INotificationSummaryManager;)V", False)]
    setPermission = JavaMethod("(Z)V")
    getPermission = JavaMethod("()Z")
    getCanRequestPermission = JavaMethod("()Z")
    onFocus = JavaMethod("(Z)V")
    onUnfocused = JavaMethod("()V")
    onNotificationPermissionChanged = JavaMethod("(Z)V")
    requestPermission = JavaMethod("(ZLkotlin/coroutines/Continuation;)Ljava/lang/Object;")
    removeNotification = JavaMethod("(I)V")
    removeGroupedNotifications = JavaMethod("(Ljava/lang/String;)V")
    clearAllNotifications = JavaMethod("()V")
    addPermissionObserver = JavaMethod("(Lcom/onesignal/notifications/IPermissionObserver;)V")
    removePermissionObserver = JavaMethod("(Lcom/onesignal/notifications/IPermissionObserver;)V")
    addForegroundLifecycleListener = JavaMethod("(Lcom/onesignal/notifications/INotificationLifecycleListener;)V")
    removeForegroundLifecycleListener = JavaMethod("(Lcom/onesignal/notifications/INotificationLifecycleListener;)V")
    addClickListener = JavaMethod("(Lcom/onesignal/notifications/INotificationClickListener;)V")
    removeClickListener = JavaMethod("(Lcom/onesignal/notifications/INotificationClickListener;)V")
    access$refreshNotificationState = JavaStaticMethod("(Lcom/onesignal/notifications/internal/NotificationsManager;)V")
    access$get_notificationPermissionController$p = JavaStaticMethod("(Lcom/onesignal/notifications/internal/NotificationsManager;)Lcom/onesignal/notifications/internal/permissions/INotificationPermissionController;")
    access$get_notificationDataController$p = JavaStaticMethod("(Lcom/onesignal/notifications/internal/NotificationsManager;)Lcom/onesignal/notifications/internal/data/INotificationRepository;")
    access$get_summaryManager$p = JavaStaticMethod("(Lcom/onesignal/notifications/internal/NotificationsManager;)Lcom/onesignal/notifications/internal/summary/INotificationSummaryManager;")