from typing import Any, ClassVar, overload
from android.app.Activity import Activity

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONArray:
    """Forward declaration for ``org.json.JSONArray``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONArray')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...
class Continuation:
    """Forward declaration for ``kotlin.coroutines.Continuation``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.coroutines.Continuation')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/coroutines/Continuation/
    """
    ...

class INotificationActivityOpener:
    def openDestinationActivity(self, p0: Activity, p1: JSONArray, p2: Continuation) -> Any: ...

from typing import Any, ClassVar, overload
from pyonesignal.core.internal.time.ITime import ITime
from pyonesignal.core.threading.WaiterWithValue import WaiterWithValue

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONObject:
    """Forward declaration for ``org.json.JSONObject``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONObject')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...
class BackgroundImageLayout:
    """Forward declaration for ``com.onesignal.notifications.BackgroundImageLayout``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.onesignal.notifications.BackgroundImageLayout')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...
class DefaultConstructorMarker:
    """Forward declaration for ``kotlin.jvm.internal.DefaultConstructorMarker``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.internal.DefaultConstructorMarker')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/internal/DefaultConstructorMarker/
    """
    ...

class Notification:
    @overload
    def __init__(self, p0: JSONObject, p1: ITime) -> None: ...
    @overload
    def __init__(self, p0: list, p1: JSONObject, p2: int, p3: ITime) -> None: ...
    def getDisplayWaiter(self) -> WaiterWithValue: ...
    def getGroupedNotifications(self) -> list: ...
    def setGroupedNotifications(self, p0: list) -> None: ...
    def getAndroidNotificationId(self) -> int: ...
    def setAndroidNotificationId(self, p0: int) -> None: ...
    def getNotificationId(self) -> str: ...
    def setNotificationId(self, p0: str) -> None: ...
    def getTemplateName(self) -> str: ...
    def setTemplateName(self, p0: str) -> None: ...
    def getTemplateId(self) -> str: ...
    def setTemplateId(self, p0: str) -> None: ...
    def getBody(self) -> str: ...
    def setBody(self, p0: str) -> None: ...
    def getAdditionalData(self) -> JSONObject: ...
    def setAdditionalData(self, p0: JSONObject) -> None: ...
    def getSmallIcon(self) -> str: ...
    def setSmallIcon(self, p0: str) -> None: ...
    def getLargeIcon(self) -> str: ...
    def setLargeIcon(self, p0: str) -> None: ...
    def getBigPicture(self) -> str: ...
    def setBigPicture(self, p0: str) -> None: ...
    def setExtender(self, p0: Any) -> None: ...
    def hasNotificationId(self) -> bool: ...
    def toString(self) -> str: ...
    def setPriority(self, p0: int) -> None: ...
    def getPriority(self) -> int: ...
    def display(self) -> None: ...
    def getNotificationExtender(self) -> Any: ...
    def setTtl(self, p0: int) -> None: ...
    def getTtl(self) -> int: ...
    def setNotificationExtender(self, p0: Any) -> None: ...
    def setGroupKey(self, p0: str) -> None: ...
    def getGroupMessage(self) -> str: ...
    def setGroupMessage(self, p0: str) -> None: ...
    def getActionButtons(self) -> list: ...
    def setActionButtons(self, p0: list) -> None: ...
    def getFromProjectNumber(self) -> str: ...
    def setFromProjectNumber(self, p0: str) -> None: ...
    def getBackgroundImageLayout(self) -> BackgroundImageLayout: ...
    def setBackgroundImageLayout(self, p0: BackgroundImageLayout) -> None: ...
    def getCollapseId(self) -> str: ...
    def setCollapseId(self, p0: str) -> None: ...
    def getSentTime(self) -> int: ...
    def setSentTime(self, p0: int) -> None: ...
    def getRawPayload(self) -> str: ...
    def setRawPayload(self, p0: str) -> None: ...
    def getLaunchURL(self) -> str: ...
    def getSmallIconAccentColor(self) -> str: ...
    def getTitle(self) -> str: ...
    def setTitle(self, p0: str) -> None: ...
    def setSmallIconAccentColor(self, p0: str) -> None: ...
    def setLaunchURL(self, p0: str) -> None: ...
    def getSound(self) -> str: ...
    def setSound(self, p0: str) -> None: ...
    def getLedColor(self) -> str: ...
    def setLedColor(self, p0: str) -> None: ...
    def getLockScreenVisibility(self) -> int: ...
    def setLockScreenVisibility(self, p0: int) -> None: ...
    def getGroupKey(self) -> str: ...
    def toJSONObject(self) -> JSONObject: ...

    class ActionButton:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: str, p1: str, p2: str, p3: int, p4: DefaultConstructorMarker) -> None: ...
        @overload
        def __init__(self, p0: str, p1: str, p2: str) -> None: ...
        def getId(self) -> str: ...
        def getIcon(self) -> str: ...
        def getText(self) -> str: ...
        def toJSONObject(self) -> JSONObject: ...

from typing import Any, ClassVar, overload
from notifications.internal.Notification import Notification
from notifications.internal.NotificationClickResult import NotificationClickResult

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class INotification:
    """Forward declaration for ``com.onesignal.notifications.INotification``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.onesignal.notifications.INotification')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...
class INotificationClickResult:
    """Forward declaration for ``com.onesignal.notifications.INotificationClickResult``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.onesignal.notifications.INotificationClickResult')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...
class JSONObject:
    """Forward declaration for ``org.json.JSONObject``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONObject')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class NotificationClickEvent:
    def __init__(self, p0: Notification, p1: NotificationClickResult) -> None: ...
    def getNotification(self) -> INotification: ...
    def getResult(self) -> INotificationClickResult: ...
    def toJSONObject(self) -> JSONObject: ...

from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONObject:
    """Forward declaration for ``org.json.JSONObject``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONObject')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class NotificationClickResult:
    def __init__(self, p0: str, p1: str) -> None: ...
    def getUrl(self) -> str: ...
    def getActionId(self) -> str: ...
    def toJSONObject(self) -> JSONObject: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from notifications.internal.Notification import Notification

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class IDisplayableMutableNotification:
    """Forward declaration for ``com.onesignal.notifications.IDisplayableMutableNotification``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.onesignal.notifications.IDisplayableMutableNotification')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class NotificationReceivedEvent:
    def __init__(self, p0: Context, p1: Notification) -> None: ...
    def getContext(self) -> Context: ...
    def setDiscard(self, p0: bool) -> None: ...
    @overload
    def preventDefault(self) -> None: ...
    @overload
    def preventDefault(self, p0: bool) -> None: ...
    @overload
    def getNotification(self) -> IDisplayableMutableNotification: ...
    @overload
    def getNotification(self) -> Notification: ...
    def getDiscard(self) -> bool: ...
    def isPreventDefault(self) -> bool: ...
    def setPreventDefault(self, p0: bool) -> None: ...

from typing import Any, ClassVar, overload
from notifications.internal.Notification import Notification

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class IDisplayableNotification:
    """Forward declaration for ``com.onesignal.notifications.IDisplayableNotification``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.onesignal.notifications.IDisplayableNotification')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class NotificationWillDisplayEvent:
    def __init__(self, p0: Notification) -> None: ...
    def setDiscard(self, p0: bool) -> None: ...
    @overload
    def preventDefault(self) -> None: ...
    @overload
    def preventDefault(self, p0: bool) -> None: ...
    @overload
    def getNotification(self) -> IDisplayableNotification: ...
    @overload
    def getNotification(self) -> Notification: ...
    def getDiscard(self) -> bool: ...
    def isPreventDefault(self) -> bool: ...
    def setPreventDefault(self, p0: bool) -> None: ...

from typing import Any, ClassVar, overload
from notifications.internal.data.INotificationRepository import INotificationRepository
from notifications.internal.lifecycle.INotificationLifecycleService import INotificationLifecycleService
from notifications.internal.permissions.INotificationPermissionController import INotificationPermissionController
from notifications.internal.restoration.INotificationRestoreWorkManager import INotificationRestoreWorkManager
from notifications.internal.summary.INotificationSummaryManager import INotificationSummaryManager
from pyonesignal.core.internal.application.IApplicationService import IApplicationService

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Continuation:
    """Forward declaration for ``kotlin.coroutines.Continuation``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.coroutines.Continuation')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/coroutines/Continuation/
    """
    ...
class IPermissionObserver:
    """Forward declaration for ``com.onesignal.notifications.IPermissionObserver``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.onesignal.notifications.IPermissionObserver')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...
class INotificationLifecycleListener:
    """Forward declaration for ``com.onesignal.notifications.INotificationLifecycleListener``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.onesignal.notifications.INotificationLifecycleListener')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...
class INotificationClickListener:
    """Forward declaration for ``com.onesignal.notifications.INotificationClickListener``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.onesignal.notifications.INotificationClickListener')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class NotificationsManager:
    def __init__(self, p0: IApplicationService, p1: INotificationPermissionController, p2: INotificationRestoreWorkManager, p3: INotificationLifecycleService, p4: INotificationRepository, p5: INotificationSummaryManager) -> None: ...
    def setPermission(self, p0: bool) -> None: ...
    def getPermission(self) -> bool: ...
    def getCanRequestPermission(self) -> bool: ...
    def onFocus(self, p0: bool) -> None: ...
    def onUnfocused(self) -> None: ...
    def onNotificationPermissionChanged(self, p0: bool) -> None: ...
    def requestPermission(self, p0: bool, p1: Continuation) -> Any: ...
    def removeNotification(self, p0: int) -> None: ...
    def removeGroupedNotifications(self, p0: str) -> None: ...
    def clearAllNotifications(self) -> None: ...
    def addPermissionObserver(self, p0: IPermissionObserver) -> None: ...
    def removePermissionObserver(self, p0: IPermissionObserver) -> None: ...
    def addForegroundLifecycleListener(self, p0: INotificationLifecycleListener) -> None: ...
    def removeForegroundLifecycleListener(self, p0: INotificationLifecycleListener) -> None: ...
    def addClickListener(self, p0: INotificationClickListener) -> None: ...
    def removeClickListener(self, p0: INotificationClickListener) -> None: ...
    @staticmethod
    def access$refreshNotificationState(p0: "NotificationsManager") -> None: ...
    @staticmethod
    def access$get_notificationPermissionController$p(p0: "NotificationsManager") -> INotificationPermissionController: ...
    @staticmethod
    def access$get_notificationDataController$p(p0: "NotificationsManager") -> INotificationRepository: ...
    @staticmethod
    def access$get_summaryManager$p(p0: "NotificationsManager") -> INotificationSummaryManager: ...

