from typing import Any, ClassVar, overload
from session.internal.outcomes.IOutcomeEventsController import IOutcomeEventsController

class SessionManager:
    def __init__(self, p0: IOutcomeEventsController) -> None: ...
    def addOutcome(self, p0: str) -> None: ...
    def addUniqueOutcome(self, p0: str) -> None: ...
    def addOutcomeWithValue(self, p0: str, p1: float) -> None: ...
    @staticmethod
    def access$get_outcomeController$p(p0: "SessionManager") -> IOutcomeEventsController: ...

