from typing import Any, ClassVar, overload
from android.content.SharedPreferences import SharedPreferences
from common.threading.Waiter import Waiter
from core.internal.application.IApplicationService import IApplicationService
from core.internal.time.ITime import ITime

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class DefaultConstructorMarker:
    """Forward declaration for ``kotlin.jvm.internal.DefaultConstructorMarker``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.internal.DefaultConstructorMarker')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/internal/DefaultConstructorMarker/
    """
    ...

class PreferencesService:
    Companion: ClassVar[Any]
    def __init__(self, p0: IApplicationService, p1: ITime) -> None: ...
    def getString(self, p0: str, p1: str, p2: str) -> str: ...
    def getInt(self, p0: str, p1: str, p2: int) -> int: ...
    def getLong(self, p0: str, p1: str, p2: int) -> int: ...
    def start(self) -> None: ...
    @staticmethod
    def access$getPrefsToApply$p(p0: "PreferencesService") -> dict: ...
    @staticmethod
    def access$getSharedPrefsByName(p0: "PreferencesService", p1: str) -> SharedPreferences: ...
    @staticmethod
    def access$getHasLoggedMissingAppContext$p(p0: "PreferencesService") -> bool: ...
    @staticmethod
    def access$setHasLoggedMissingAppContext$p(p0: "PreferencesService", p1: bool) -> None: ...
    def saveString(self, p0: str, p1: str, p2: str) -> None: ...
    def getStringSet(self, p0: str, p1: str, p2: set) -> set: ...
    def saveBool(self, p0: str, p1: str, p2: bool) -> None: ...
    def saveLong(self, p0: str, p1: str, p2: int) -> None: ...
    def getBool(self, p0: str, p1: str, p2: bool) -> bool: ...
    def saveInt(self, p0: str, p1: str, p2: int) -> None: ...
    def saveStringSet(self, p0: str, p1: str, p2: set) -> None: ...
    @staticmethod
    def access$getWaiter$p(p0: "PreferencesService") -> Waiter: ...
    @staticmethod
    def access$get_time$p(p0: "PreferencesService") -> ITime: ...

    class Companion:
        def __init__(self, p0: DefaultConstructorMarker) -> None: ...

