from typing import Any, ClassVar, overload
from common.consistency.RywData import RywData

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class DefaultConstructorMarker:
    """Forward declaration for ``kotlin.jvm.internal.DefaultConstructorMarker``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.internal.DefaultConstructorMarker')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/internal/DefaultConstructorMarker/
    """
    ...

class IamFetchReadyCondition:
    Companion: ClassVar[Any]
    ID: ClassVar[str]
    def __init__(self, p0: str) -> None: ...
    def getId(self) -> str: ...
    def isMet(self, p0: dict) -> bool: ...
    def getRywData(self, p0: dict) -> RywData: ...

    class Companion:
        def __init__(self, p0: DefaultConstructorMarker) -> None: ...

from typing import Any, ClassVar, overload

class RywData:
    def __init__(self, p0: str, p1: int) -> None: ...
    @staticmethod
    def copy$default(p0: "RywData", p1: str, p2: int, p3: int, p4: Any) -> "RywData": ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def copy(self, p0: str, p1: int) -> "RywData": ...
    def getRywDelay(self) -> int: ...
    def component1(self) -> str: ...
    def component2(self) -> int: ...
    def getRywToken(self) -> str: ...

