from typing import Any, ClassVar, overload
from common.modeling.ModelChangedArgs import ModelChangedArgs

class IModelChangedHandler:
    def onChanged(self, p0: ModelChangedArgs, p1: str) -> None: ...

from typing import Any, ClassVar, overload
from common.modeling.Model import Model

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONObject:
    """Forward declaration for ``org.json.JSONObject``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONObject')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class IModelStore:
    def remove(self, p0: str, p1: str) -> None: ...
    def get(self, p0: str) -> Model: ...
    def clear(self, p0: str) -> None: ...
    def replaceAll(self, p0: list, p1: str) -> None: ...
    @overload
    def add(self, p0: int, p1: Model, p2: str) -> None: ...
    @overload
    def add(self, p0: Model, p1: str) -> None: ...
    def list(self) -> list: ...
    def create(self, p0: JSONObject) -> Model: ...

    class DefaultImpls:
        @overload
        @staticmethod
        def add$default(p0: "IModelStore", p1: int, p2: Model, p3: str, p4: int, p5: Any) -> None: ...
        @overload
        @staticmethod
        def add$default(p0: "IModelStore", p1: Model, p2: str, p3: int, p4: Any) -> None: ...
        @staticmethod
        def remove$default(p0: "IModelStore", p1: str, p2: str, p3: int, p4: Any) -> None: ...
        @staticmethod
        def clear$default(p0: "IModelStore", p1: str, p2: int, p3: Any) -> None: ...
        @staticmethod
        def create$default(p0: "IModelStore", p1: JSONObject, p2: int, p3: Any) -> Model: ...
        @staticmethod
        def replaceAll$default(p0: "IModelStore", p1: list, p2: str, p3: int, p4: Any) -> None: ...

from typing import Any, ClassVar, overload
from common.modeling.Model import Model
from common.modeling.ModelChangedArgs import ModelChangedArgs

class IModelStoreChangeHandler:
    def onModelAdded(self, p0: Model, p1: str) -> None: ...
    def onModelUpdated(self, p0: ModelChangedArgs, p1: str) -> None: ...
    def onModelRemoved(self, p0: Model, p1: str) -> None: ...

from typing import Any, ClassVar, overload
from common.modeling.Model import Model

class ISingletonModelStore:
    def replace(self, p0: Model, p1: str) -> None: ...
    def getModel(self) -> Model: ...

    class DefaultImpls:
        @staticmethod
        def replace$default(p0: "ISingletonModelStore", p1: Model, p2: str, p3: int, p4: Any) -> None: ...

from typing import Any, ClassVar, overload
from common.modeling.Model import Model
from common.modeling.ModelChangedArgs import ModelChangedArgs

class ISingletonModelStoreChangeHandler:
    def onModelUpdated(self, p0: ModelChangedArgs, p1: str) -> None: ...
    def onModelReplaced(self, p0: Model, p1: str) -> None: ...

from typing import Any, ClassVar, overload
from common.modeling.Model import Model

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class DefaultConstructorMarker:
    """Forward declaration for ``kotlin.jvm.internal.DefaultConstructorMarker``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.internal.DefaultConstructorMarker')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/internal/DefaultConstructorMarker/
    """
    ...

class MapModel:
    @overload
    def __init__(self, p0: Model, p1: str) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: Model, p1: str, p2: int, p3: DefaultConstructorMarker) -> None: ...
    def getKeys(self) -> set: ...
    def getEntries(self) -> set: ...
    @overload
    def remove(self, p0: Any) -> Any: ...
    @overload
    def remove(self, p0: str) -> Any: ...
    def size(self) -> int: ...
    @overload
    def get(self, p0: Any) -> Any: ...
    @overload
    def get(self, p0: str) -> Any: ...
    @overload
    def put(self, p0: Any, p1: Any) -> Any: ...
    @overload
    def put(self, p0: str, p1: Any) -> Any: ...
    def values(self) -> list: ...
    def clear(self) -> None: ...
    def isEmpty(self) -> bool: ...
    def entrySet(self) -> set: ...
    def putAll(self, p0: dict) -> None: ...
    @overload
    def containsKey(self, p0: Any) -> bool: ...
    @overload
    def containsKey(self, p0: str) -> bool: ...
    def keySet(self) -> set: ...
    def containsValue(self, p0: Any) -> bool: ...
    def getSize(self) -> int: ...
    def getValues(self) -> list: ...

from typing import Any, ClassVar, overload
from common.modeling.IModelChangedHandler import IModelChangedHandler
from common.modeling.MapModel import MapModel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class DefaultConstructorMarker:
    """Forward declaration for ``kotlin.jvm.internal.DefaultConstructorMarker``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.internal.DefaultConstructorMarker')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/internal/DefaultConstructorMarker/
    """
    ...
class Function0:
    """Forward declaration for ``kotlin.jvm.functions.Function0``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.functions.Function0')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/functions/Function0/
    """
    ...
class JSONObject:
    """Forward declaration for ``org.json.JSONObject``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONObject')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...
class Enum:
    """Forward declaration for ``java.lang.Enum``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.lang.Enum')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/lang/Enum.html
    """
    ...
class BigDecimal:
    """Forward declaration for ``java.math.BigDecimal``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.math.BigDecimal')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html
    """
    ...

class Model:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: "Model", p1: str, p2: int, p3: DefaultConstructorMarker) -> None: ...
    @overload
    def __init__(self, p0: "Model", p1: str) -> None: ...
    def getId(self) -> str: ...
    def getHasSubscribers(self) -> bool: ...
    @overload
    def subscribe(self, p0: IModelChangedHandler) -> None: ...
    @overload
    def subscribe(self, p0: Any) -> None: ...
    @overload
    def unsubscribe(self, p0: IModelChangedHandler) -> None: ...
    @overload
    def unsubscribe(self, p0: Any) -> None: ...
    @staticmethod
    def getStringProperty$default(p0: "Model", p1: str, p2: Function0, p3: int, p4: Any) -> str: ...
    def setId(self, p0: str) -> None: ...
    @staticmethod
    def setStringProperty$default(p0: "Model", p1: str, p2: str, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    def initializeFromJson(self, p0: JSONObject) -> None: ...
    def initializeFromModel(self, p0: str, p1: "Model") -> None: ...
    def setEnumProperty(self, p0: str, p1: Enum, p2: str, p3: bool) -> None: ...
    def setOptAnyProperty(self, p0: str, p1: Any, p2: str, p3: bool) -> None: ...
    @staticmethod
    def setEnumProperty$default(p0: "Model", p1: str, p2: Enum, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    def setMapModelProperty(self, p0: str, p1: MapModel, p2: str, p3: bool) -> None: ...
    def setOptMapModelProperty(self, p0: str, p1: MapModel, p2: str, p3: bool) -> None: ...
    @staticmethod
    def setMapModelProperty$default(p0: "Model", p1: str, p2: MapModel, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    def setListProperty(self, p0: str, p1: list, p2: str, p3: bool) -> None: ...
    def setOptListProperty(self, p0: str, p1: list, p2: str, p3: bool) -> None: ...
    @staticmethod
    def setListProperty$default(p0: "Model", p1: str, p2: list, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    def setStringProperty(self, p0: str, p1: str, p2: str, p3: bool) -> None: ...
    def setOptStringProperty(self, p0: str, p1: str, p2: str, p3: bool) -> None: ...
    def setBooleanProperty(self, p0: str, p1: bool, p2: str, p3: bool) -> None: ...
    def setOptBooleanProperty(self, p0: str, p1: bool, p2: str, p3: bool) -> None: ...
    @staticmethod
    def setBooleanProperty$default(p0: "Model", p1: str, p2: bool, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    def setLongProperty(self, p0: str, p1: int, p2: str, p3: bool) -> None: ...
    def setOptLongProperty(self, p0: str, p1: int, p2: str, p3: bool) -> None: ...
    @staticmethod
    def setLongProperty$default(p0: "Model", p1: str, p2: int, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    def setDoubleProperty(self, p0: str, p1: float, p2: str, p3: bool) -> None: ...
    def setOptDoubleProperty(self, p0: str, p1: float, p2: str, p3: bool) -> None: ...
    @staticmethod
    def setDoubleProperty$default(p0: "Model", p1: str, p2: float, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    def setFloatProperty(self, p0: str, p1: float, p2: str, p3: bool) -> None: ...
    def setOptFloatProperty(self, p0: str, p1: float, p2: str, p3: bool) -> None: ...
    @staticmethod
    def setFloatProperty$default(p0: "Model", p1: str, p2: float, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    def setIntProperty(self, p0: str, p1: int, p2: str, p3: bool) -> None: ...
    def setOptIntProperty(self, p0: str, p1: int, p2: str, p3: bool) -> None: ...
    @staticmethod
    def setIntProperty$default(p0: "Model", p1: str, p2: int, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    def setBigDecimalProperty(self, p0: str, p1: BigDecimal, p2: str, p3: bool) -> None: ...
    def setOptBigDecimalProperty(self, p0: str, p1: BigDecimal, p2: str, p3: bool) -> None: ...
    @staticmethod
    def setBigDecimalProperty$default(p0: "Model", p1: str, p2: BigDecimal, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    def setAnyProperty(self, p0: str, p1: Any, p2: str, p3: bool) -> None: ...
    @staticmethod
    def setAnyProperty$default(p0: "Model", p1: str, p2: Any, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    def setOptEnumProperty(self, p0: str, p1: Enum, p2: str, p3: bool) -> None: ...
    @staticmethod
    def setOptEnumProperty$default(p0: "Model", p1: str, p2: Enum, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    @staticmethod
    def setOptMapModelProperty$default(p0: "Model", p1: str, p2: MapModel, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    @staticmethod
    def setOptListProperty$default(p0: "Model", p1: str, p2: list, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    @staticmethod
    def setOptStringProperty$default(p0: "Model", p1: str, p2: str, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    @staticmethod
    def setOptBooleanProperty$default(p0: "Model", p1: str, p2: bool, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    @staticmethod
    def setOptLongProperty$default(p0: "Model", p1: str, p2: int, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    @staticmethod
    def setOptDoubleProperty$default(p0: "Model", p1: str, p2: float, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    @staticmethod
    def setOptFloatProperty$default(p0: "Model", p1: str, p2: float, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    @staticmethod
    def setOptIntProperty$default(p0: "Model", p1: str, p2: int, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    @staticmethod
    def setOptBigDecimalProperty$default(p0: "Model", p1: str, p2: BigDecimal, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    @staticmethod
    def setOptAnyProperty$default(p0: "Model", p1: str, p2: Any, p3: str, p4: bool, p5: int, p6: Any) -> None: ...
    def hasProperty(self, p0: str) -> bool: ...
    @staticmethod
    def getOptAnyProperty$default(p0: "Model", p1: str, p2: Function0, p3: int, p4: Any) -> Any: ...
    @staticmethod
    def getMapModelProperty$default(p0: "Model", p1: str, p2: Function0, p3: int, p4: Any) -> MapModel: ...
    @staticmethod
    def getListProperty$default(p0: "Model", p1: str, p2: Function0, p3: int, p4: Any) -> list: ...
    @staticmethod
    def getBooleanProperty$default(p0: "Model", p1: str, p2: Function0, p3: int, p4: Any) -> bool: ...
    @staticmethod
    def getLongProperty$default(p0: "Model", p1: str, p2: Function0, p3: int, p4: Any) -> int: ...
    @staticmethod
    def getDoubleProperty$default(p0: "Model", p1: str, p2: Function0, p3: int, p4: Any) -> float: ...
    @staticmethod
    def getFloatProperty$default(p0: "Model", p1: str, p2: Function0, p3: int, p4: Any) -> float: ...
    @staticmethod
    def getIntProperty$default(p0: "Model", p1: str, p2: Function0, p3: int, p4: Any) -> int: ...
    @staticmethod
    def getBigDecimalProperty$default(p0: "Model", p1: str, p2: Function0, p3: int, p4: Any) -> BigDecimal: ...
    @staticmethod
    def getAnyProperty$default(p0: "Model", p1: str, p2: Function0, p3: int, p4: Any) -> Any: ...
    @staticmethod
    def getOptMapModelProperty$default(p0: "Model", p1: str, p2: Function0, p3: int, p4: Any) -> MapModel: ...
    @staticmethod
    def getOptListProperty$default(p0: "Model", p1: str, p2: Function0, p3: int, p4: Any) -> list: ...
    @staticmethod
    def getOptStringProperty$default(p0: "Model", p1: str, p2: Function0, p3: int, p4: Any) -> str: ...
    @staticmethod
    def getOptBooleanProperty$default(p0: "Model", p1: str, p2: Function0, p3: int, p4: Any) -> bool: ...
    @staticmethod
    def getOptLongProperty$default(p0: "Model", p1: str, p2: Function0, p3: int, p4: Any) -> int: ...
    @staticmethod
    def getOptFloatProperty$default(p0: "Model", p1: str, p2: Function0, p3: int, p4: Any) -> float: ...
    @staticmethod
    def getOptDoubleProperty$default(p0: "Model", p1: str, p2: Function0, p3: int, p4: Any) -> float: ...
    @staticmethod
    def getOptIntProperty$default(p0: "Model", p1: str, p2: Function0, p3: int, p4: Any) -> int: ...
    @staticmethod
    def getOptBigDecimalProperty$default(p0: "Model", p1: str, p2: Function0, p3: int, p4: Any) -> BigDecimal: ...
    def toJSON(self) -> JSONObject: ...

from typing import Any, ClassVar, overload

class ModelChangeTags:
    INSTANCE: ClassVar["ModelChangeTags"]
    NORMAL: ClassVar[str]
    NO_PROPOGATE: ClassVar[str]
    HYDRATE: ClassVar[str]

from typing import Any, ClassVar, overload
from common.modeling.Model import Model

class ModelChangedArgs:
    def __init__(self, p0: Model, p1: str, p2: str, p3: Any, p4: Any) -> None: ...
    def getPath(self) -> str: ...
    def getProperty(self) -> str: ...
    def getOldValue(self) -> Any: ...
    def getModel(self) -> Model: ...
    def getNewValue(self) -> Any: ...

from typing import Any, ClassVar, overload
from common.modeling.IModelStoreChangeHandler import IModelStoreChangeHandler
from common.modeling.Model import Model
from common.modeling.ModelChangedArgs import ModelChangedArgs
from core.internal.preferences.IPreferencesService import IPreferencesService

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class DefaultConstructorMarker:
    """Forward declaration for ``kotlin.jvm.internal.DefaultConstructorMarker``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.internal.DefaultConstructorMarker')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/internal/DefaultConstructorMarker/
    """
    ...

class ModelStore:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str, p1: IPreferencesService) -> None: ...
    @overload
    def __init__(self, p0: str, p1: IPreferencesService, p2: int, p3: DefaultConstructorMarker) -> None: ...
    def getName(self) -> str: ...
    def remove(self, p0: str, p1: str) -> None: ...
    def get(self, p0: str) -> Model: ...
    def clear(self, p0: str) -> None: ...
    def replaceAll(self, p0: list, p1: str) -> None: ...
    @overload
    def add(self, p0: Model, p1: str) -> None: ...
    @overload
    def add(self, p0: int, p1: Model, p2: str) -> None: ...
    def list(self) -> list: ...
    def getHasSubscribers(self) -> bool: ...
    @overload
    def subscribe(self, p0: IModelStoreChangeHandler) -> None: ...
    @overload
    def subscribe(self, p0: Any) -> None: ...
    @overload
    def unsubscribe(self, p0: IModelStoreChangeHandler) -> None: ...
    @overload
    def unsubscribe(self, p0: Any) -> None: ...
    def onChanged(self, p0: ModelChangedArgs, p1: str) -> None: ...
    def persist(self) -> None: ...

from typing import Any, ClassVar, overload
from common.modeling.Model import Model
from core.internal.preferences.IPreferencesService import IPreferencesService

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Function0:
    """Forward declaration for ``kotlin.jvm.functions.Function0``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.functions.Function0')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/functions/Function0/
    """
    ...
class DefaultConstructorMarker:
    """Forward declaration for ``kotlin.jvm.internal.DefaultConstructorMarker``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.internal.DefaultConstructorMarker')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/internal/DefaultConstructorMarker/
    """
    ...
class JSONObject:
    """Forward declaration for ``org.json.JSONObject``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONObject')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class SimpleModelStore:
    @overload
    def __init__(self, p0: Function0, p1: str, p2: IPreferencesService) -> None: ...
    @overload
    def __init__(self, p0: Function0, p1: str, p2: IPreferencesService, p3: int, p4: DefaultConstructorMarker) -> None: ...
    def create(self, p0: JSONObject) -> Model: ...

from typing import Any, ClassVar, overload
from common.modeling.ISingletonModelStoreChangeHandler import ISingletonModelStoreChangeHandler
from common.modeling.Model import Model
from common.modeling.ModelChangedArgs import ModelChangedArgs
from common.modeling.ModelStore import ModelStore

class SingletonModelStore:
    def __init__(self, p0: ModelStore) -> None: ...
    def replace(self, p0: Model, p1: str) -> None: ...
    def getHasSubscribers(self) -> bool: ...
    @overload
    def subscribe(self, p0: Any) -> None: ...
    @overload
    def subscribe(self, p0: ISingletonModelStoreChangeHandler) -> None: ...
    @overload
    def unsubscribe(self, p0: ISingletonModelStoreChangeHandler) -> None: ...
    @overload
    def unsubscribe(self, p0: Any) -> None: ...
    def getModel(self) -> Model: ...
    def onModelAdded(self, p0: Model, p1: str) -> None: ...
    def onModelUpdated(self, p0: ModelChangedArgs, p1: str) -> None: ...
    def onModelRemoved(self, p0: Model, p1: str) -> None: ...
    def getStore(self) -> ModelStore: ...

