from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

class IModelChangedHandler(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/common/modeling/IModelChangedHandler"
    onChanged = JavaMethod("(Lcom/onesignal/common/modeling/ModelChangedArgs;Ljava/lang/String;)V")

class IModelStore(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/common/modeling/IModelStore"
    remove = JavaMethod("(Ljava/lang/String;Ljava/lang/String;)V")
    get = JavaMethod("(Ljava/lang/String;)Lcom/onesignal/common/modeling/Model;")
    clear = JavaMethod("(Ljava/lang/String;)V")
    replaceAll = JavaMethod("(Ljava/util/List;Ljava/lang/String;)V")
    add = JavaMultipleMethod([("(ILcom/onesignal/common/modeling/Model;Ljava/lang/String;)V", False, False), ("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;)V", False, False)])
    list = JavaMethod("()Ljava/util/Collection;")
    create = JavaMethod("(Lorg/json/JSONObject;)Lcom/onesignal/common/modeling/Model;")

    class DefaultImpls(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "com/onesignal/common/modeling/IModelStore$DefaultImpls"
        add$default = JavaMultipleMethod([("(Lcom/onesignal/common/modeling/IModelStore;ILcom/onesignal/common/modeling/Model;Ljava/lang/String;ILjava/lang/Object;)V", True, False), ("(Lcom/onesignal/common/modeling/IModelStore;Lcom/onesignal/common/modeling/Model;Ljava/lang/String;ILjava/lang/Object;)V", True, False)])
        remove$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/IModelStore;Ljava/lang/String;Ljava/lang/String;ILjava/lang/Object;)V")
        clear$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/IModelStore;Ljava/lang/String;ILjava/lang/Object;)V")
        create$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/IModelStore;Lorg/json/JSONObject;ILjava/lang/Object;)Lcom/onesignal/common/modeling/Model;")
        replaceAll$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/IModelStore;Ljava/util/List;Ljava/lang/String;ILjava/lang/Object;)V")

class IModelStoreChangeHandler(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/common/modeling/IModelStoreChangeHandler"
    onModelAdded = JavaMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;)V")
    onModelUpdated = JavaMethod("(Lcom/onesignal/common/modeling/ModelChangedArgs;Ljava/lang/String;)V")
    onModelRemoved = JavaMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;)V")

class ISingletonModelStore(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/common/modeling/ISingletonModelStore"
    replace = JavaMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;)V")
    getModel = JavaMethod("()Lcom/onesignal/common/modeling/Model;")

    class DefaultImpls(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "com/onesignal/common/modeling/ISingletonModelStore$DefaultImpls"
        replace$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/ISingletonModelStore;Lcom/onesignal/common/modeling/Model;Ljava/lang/String;ILjava/lang/Object;)V")

class ISingletonModelStoreChangeHandler(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/common/modeling/ISingletonModelStoreChangeHandler"
    onModelUpdated = JavaMethod("(Lcom/onesignal/common/modeling/ModelChangedArgs;Ljava/lang/String;)V")
    onModelReplaced = JavaMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;)V")

class MapModel(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/common/modeling/MapModel"
    __javaconstructor__ = [("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;)V", False), ("()V", False), ("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;ILkotlin/jvm/internal/DefaultConstructorMarker;)V", False)]
    getKeys = JavaMethod("()Ljava/util/Set;")
    getEntries = JavaMethod("()Ljava/util/Set;")
    remove = JavaMultipleMethod([("(Ljava/lang/Object;)Ljava/lang/Object;", False, False), ("(Ljava/lang/String;)Ljava/lang/Object;", False, False)])
    size = JavaMethod("()I")
    get = JavaMultipleMethod([("(Ljava/lang/Object;)Ljava/lang/Object;", False, False), ("(Ljava/lang/String;)Ljava/lang/Object;", False, False)])
    put = JavaMultipleMethod([("(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;", False, False), ("(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;", False, False)])
    values = JavaMethod("()Ljava/util/Collection;")
    clear = JavaMethod("()V")
    isEmpty = JavaMethod("()Z")
    entrySet = JavaMethod("()Ljava/util/Set;")
    putAll = JavaMethod("(Ljava/util/Map;)V")
    containsKey = JavaMultipleMethod([("(Ljava/lang/Object;)Z", False, False), ("(Ljava/lang/String;)Z", False, False)])
    keySet = JavaMethod("()Ljava/util/Set;")
    containsValue = JavaMethod("(Ljava/lang/Object;)Z")
    getSize = JavaMethod("()I")
    getValues = JavaMethod("()Ljava/util/Collection;")

class Model(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/common/modeling/Model"
    __javaconstructor__ = [("()V", False), ("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;ILkotlin/jvm/internal/DefaultConstructorMarker;)V", False), ("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;)V", False)]
    getId = JavaMethod("()Ljava/lang/String;")
    getHasSubscribers = JavaMethod("()Z")
    subscribe = JavaMultipleMethod([("(Lcom/onesignal/common/modeling/IModelChangedHandler;)V", False, False), ("(Ljava/lang/Object;)V", False, False)])
    unsubscribe = JavaMultipleMethod([("(Lcom/onesignal/common/modeling/IModelChangedHandler;)V", False, False), ("(Ljava/lang/Object;)V", False, False)])
    getStringProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)Ljava/lang/String;")
    setId = JavaMethod("(Ljava/lang/String;)V")
    setStringProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZILjava/lang/Object;)V")
    initializeFromJson = JavaMethod("(Lorg/json/JSONObject;)V")
    initializeFromModel = JavaMethod("(Ljava/lang/String;Lcom/onesignal/common/modeling/Model;)V")
    setEnumProperty = JavaMethod("(Ljava/lang/String;Ljava/lang/Enum;Ljava/lang/String;Z)V")
    setOptAnyProperty = JavaMethod("(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;Z)V")
    setEnumProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Ljava/lang/Enum;Ljava/lang/String;ZILjava/lang/Object;)V")
    setMapModelProperty = JavaMethod("(Ljava/lang/String;Lcom/onesignal/common/modeling/MapModel;Ljava/lang/String;Z)V")
    setOptMapModelProperty = JavaMethod("(Ljava/lang/String;Lcom/onesignal/common/modeling/MapModel;Ljava/lang/String;Z)V")
    setMapModelProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lcom/onesignal/common/modeling/MapModel;Ljava/lang/String;ZILjava/lang/Object;)V")
    setListProperty = JavaMethod("(Ljava/lang/String;Ljava/util/List;Ljava/lang/String;Z)V")
    setOptListProperty = JavaMethod("(Ljava/lang/String;Ljava/util/List;Ljava/lang/String;Z)V")
    setListProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Ljava/util/List;Ljava/lang/String;ZILjava/lang/Object;)V")
    setStringProperty = JavaMethod("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V")
    setOptStringProperty = JavaMethod("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V")
    setBooleanProperty = JavaMethod("(Ljava/lang/String;ZLjava/lang/String;Z)V")
    setOptBooleanProperty = JavaMethod("(Ljava/lang/String;Ljava/lang/Boolean;Ljava/lang/String;Z)V")
    setBooleanProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;ZLjava/lang/String;ZILjava/lang/Object;)V")
    setLongProperty = JavaMethod("(Ljava/lang/String;JLjava/lang/String;Z)V")
    setOptLongProperty = JavaMethod("(Ljava/lang/String;Ljava/lang/Long;Ljava/lang/String;Z)V")
    setLongProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;JLjava/lang/String;ZILjava/lang/Object;)V")
    setDoubleProperty = JavaMethod("(Ljava/lang/String;DLjava/lang/String;Z)V")
    setOptDoubleProperty = JavaMethod("(Ljava/lang/String;Ljava/lang/Double;Ljava/lang/String;Z)V")
    setDoubleProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;DLjava/lang/String;ZILjava/lang/Object;)V")
    setFloatProperty = JavaMethod("(Ljava/lang/String;FLjava/lang/String;Z)V")
    setOptFloatProperty = JavaMethod("(Ljava/lang/String;Ljava/lang/Float;Ljava/lang/String;Z)V")
    setFloatProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;FLjava/lang/String;ZILjava/lang/Object;)V")
    setIntProperty = JavaMethod("(Ljava/lang/String;ILjava/lang/String;Z)V")
    setOptIntProperty = JavaMethod("(Ljava/lang/String;Ljava/lang/Integer;Ljava/lang/String;Z)V")
    setIntProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;ILjava/lang/String;ZILjava/lang/Object;)V")
    setBigDecimalProperty = JavaMethod("(Ljava/lang/String;Ljava/math/BigDecimal;Ljava/lang/String;Z)V")
    setOptBigDecimalProperty = JavaMethod("(Ljava/lang/String;Ljava/math/BigDecimal;Ljava/lang/String;Z)V")
    setBigDecimalProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Ljava/math/BigDecimal;Ljava/lang/String;ZILjava/lang/Object;)V")
    setAnyProperty = JavaMethod("(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;Z)V")
    setAnyProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;ZILjava/lang/Object;)V")
    setOptEnumProperty = JavaMethod("(Ljava/lang/String;Ljava/lang/Enum;Ljava/lang/String;Z)V")
    setOptEnumProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Ljava/lang/Enum;Ljava/lang/String;ZILjava/lang/Object;)V")
    setOptMapModelProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lcom/onesignal/common/modeling/MapModel;Ljava/lang/String;ZILjava/lang/Object;)V")
    setOptListProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Ljava/util/List;Ljava/lang/String;ZILjava/lang/Object;)V")
    setOptStringProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZILjava/lang/Object;)V")
    setOptBooleanProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Ljava/lang/Boolean;Ljava/lang/String;ZILjava/lang/Object;)V")
    setOptLongProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Ljava/lang/Long;Ljava/lang/String;ZILjava/lang/Object;)V")
    setOptDoubleProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Ljava/lang/Double;Ljava/lang/String;ZILjava/lang/Object;)V")
    setOptFloatProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Ljava/lang/Float;Ljava/lang/String;ZILjava/lang/Object;)V")
    setOptIntProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Ljava/lang/Integer;Ljava/lang/String;ZILjava/lang/Object;)V")
    setOptBigDecimalProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Ljava/math/BigDecimal;Ljava/lang/String;ZILjava/lang/Object;)V")
    setOptAnyProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;ZILjava/lang/Object;)V")
    hasProperty = JavaMethod("(Ljava/lang/String;)Z")
    getOptAnyProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)Ljava/lang/Object;")
    getMapModelProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)Lcom/onesignal/common/modeling/MapModel;")
    getListProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)Ljava/util/List;")
    getBooleanProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)Z")
    getLongProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)J")
    getDoubleProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)D")
    getFloatProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)F")
    getIntProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)I")
    getBigDecimalProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)Ljava/math/BigDecimal;")
    getAnyProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)Ljava/lang/Object;")
    getOptMapModelProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)Lcom/onesignal/common/modeling/MapModel;")
    getOptListProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)Ljava/util/List;")
    getOptStringProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)Ljava/lang/String;")
    getOptBooleanProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)Ljava/lang/Boolean;")
    getOptLongProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)Ljava/lang/Long;")
    getOptFloatProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)Ljava/lang/Float;")
    getOptDoubleProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)Ljava/lang/Double;")
    getOptIntProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)Ljava/lang/Integer;")
    getOptBigDecimalProperty$default = JavaStaticMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)Ljava/math/BigDecimal;")
    toJSON = JavaMethod("()Lorg/json/JSONObject;")

class ModelChangeTags(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/common/modeling/ModelChangeTags"
    INSTANCE = JavaStaticField("Lcom/onesignal/common/modeling/ModelChangeTags;")
    NORMAL = JavaStaticField("Ljava/lang/String;")
    NO_PROPOGATE = JavaStaticField("Ljava/lang/String;")
    HYDRATE = JavaStaticField("Ljava/lang/String;")

class ModelChangedArgs(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/common/modeling/ModelChangedArgs"
    __javaconstructor__ = [("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V", False)]
    getPath = JavaMethod("()Ljava/lang/String;")
    getProperty = JavaMethod("()Ljava/lang/String;")
    getOldValue = JavaMethod("()Ljava/lang/Object;")
    getModel = JavaMethod("()Lcom/onesignal/common/modeling/Model;")
    getNewValue = JavaMethod("()Ljava/lang/Object;")

class ModelStore(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/common/modeling/ModelStore"
    __javaconstructor__ = [("()V", False), ("(Ljava/lang/String;Lcom/onesignal/core/internal/preferences/IPreferencesService;)V", False), ("(Ljava/lang/String;Lcom/onesignal/core/internal/preferences/IPreferencesService;ILkotlin/jvm/internal/DefaultConstructorMarker;)V", False)]
    getName = JavaMethod("()Ljava/lang/String;")
    remove = JavaMethod("(Ljava/lang/String;Ljava/lang/String;)V")
    get = JavaMethod("(Ljava/lang/String;)Lcom/onesignal/common/modeling/Model;")
    clear = JavaMethod("(Ljava/lang/String;)V")
    replaceAll = JavaMethod("(Ljava/util/List;Ljava/lang/String;)V")
    add = JavaMultipleMethod([("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;)V", False, False), ("(ILcom/onesignal/common/modeling/Model;Ljava/lang/String;)V", False, False)])
    list = JavaMethod("()Ljava/util/Collection;")
    getHasSubscribers = JavaMethod("()Z")
    subscribe = JavaMultipleMethod([("(Lcom/onesignal/common/modeling/IModelStoreChangeHandler;)V", False, False), ("(Ljava/lang/Object;)V", False, False)])
    unsubscribe = JavaMultipleMethod([("(Lcom/onesignal/common/modeling/IModelStoreChangeHandler;)V", False, False), ("(Ljava/lang/Object;)V", False, False)])
    onChanged = JavaMethod("(Lcom/onesignal/common/modeling/ModelChangedArgs;Ljava/lang/String;)V")
    persist = JavaMethod("()V")

class SimpleModelStore(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/common/modeling/SimpleModelStore"
    __javaconstructor__ = [("(Lkotlin/jvm/functions/Function0;Ljava/lang/String;Lcom/onesignal/core/internal/preferences/IPreferencesService;)V", False), ("(Lkotlin/jvm/functions/Function0;Ljava/lang/String;Lcom/onesignal/core/internal/preferences/IPreferencesService;ILkotlin/jvm/internal/DefaultConstructorMarker;)V", False)]
    create = JavaMethod("(Lorg/json/JSONObject;)Lcom/onesignal/common/modeling/Model;")

class SingletonModelStore(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/common/modeling/SingletonModelStore"
    __javaconstructor__ = [("(Lcom/onesignal/common/modeling/ModelStore;)V", False)]
    replace = JavaMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;)V")
    getHasSubscribers = JavaMethod("()Z")
    subscribe = JavaMultipleMethod([("(Ljava/lang/Object;)V", False, False), ("(Lcom/onesignal/common/modeling/ISingletonModelStoreChangeHandler;)V", False, False)])
    unsubscribe = JavaMultipleMethod([("(Lcom/onesignal/common/modeling/ISingletonModelStoreChangeHandler;)V", False, False), ("(Ljava/lang/Object;)V", False, False)])
    getModel = JavaMethod("()Lcom/onesignal/common/modeling/Model;")
    onModelAdded = JavaMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;)V")
    onModelUpdated = JavaMethod("(Lcom/onesignal/common/modeling/ModelChangedArgs;Ljava/lang/String;)V")
    onModelRemoved = JavaMethod("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;)V")
    getStore = JavaMethod("()Lcom/onesignal/common/modeling/ModelStore;")