from typing import Any, ClassVar, overload
from android.app.Activity import Activity

class ActivityLifecycleHandlerBase:
    def __init__(self) -> None: ...
    def onActivityStopped(self, p0: Activity) -> None: ...
    def onActivityAvailable(self, p0: Activity) -> None: ...

from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class EnumEntries:
    """Forward declaration for ``kotlin.enums.EnumEntries``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.enums.EnumEntries')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/enums/EnumEntries/
    """
    ...

class AppEntryAction:
    NOTIFICATION_CLICK: ClassVar["AppEntryAction"]
    APP_OPEN: ClassVar["AppEntryAction"]
    APP_CLOSE: ClassVar["AppEntryAction"]
    NOTIFICATION_CLICK: ClassVar["AppEntryAction"]
    APP_OPEN: ClassVar["AppEntryAction"]
    APP_CLOSE: ClassVar["AppEntryAction"]
    @staticmethod
    def values() -> Any: ...
    @staticmethod
    def valueOf(p0: str) -> "AppEntryAction": ...
    @staticmethod
    def getEntries() -> EnumEntries: ...
    def isAppOpen(self) -> bool: ...
    def isNotificationClick(self) -> bool: ...
    def isAppClose(self) -> bool: ...

from typing import Any, ClassVar, overload

class ApplicationLifecycleHandlerBase:
    def __init__(self) -> None: ...
    def onFocus(self, p0: bool) -> None: ...
    def onUnfocused(self) -> None: ...

from typing import Any, ClassVar, overload
from android.app.Activity import Activity

class IActivityLifecycleHandler:
    def onActivityStopped(self, p0: Activity) -> None: ...
    def onActivityAvailable(self, p0: Activity) -> None: ...

from typing import Any, ClassVar, overload

class IApplicationLifecycleHandler:
    def onFocus(self, p0: bool) -> None: ...
    def onUnfocused(self) -> None: ...

from typing import Any, ClassVar, overload
from android.app.Activity import Activity
from android.content.Context import Context
from core.internal.application.AppEntryAction import AppEntryAction
from core.internal.application.IActivityLifecycleHandler import IActivityLifecycleHandler
from core.internal.application.IApplicationLifecycleHandler import IApplicationLifecycleHandler

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Continuation:
    """Forward declaration for ``kotlin.coroutines.Continuation``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.coroutines.Continuation')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/coroutines/Continuation/
    """
    ...

class IApplicationService:
    def getAppContext(self) -> Context: ...
    def addActivityLifecycleHandler(self, p0: IActivityLifecycleHandler) -> None: ...
    def getCurrent(self) -> Activity: ...
    def isInForeground(self) -> bool: ...
    def getEntryState(self) -> AppEntryAction: ...
    def setEntryState(self, p0: AppEntryAction) -> None: ...
    def waitUntilSystemConditionsAvailable(self, p0: Continuation) -> Any: ...
    def waitUntilActivityReady(self, p0: Continuation) -> Any: ...
    def removeActivityLifecycleHandler(self, p0: IActivityLifecycleHandler) -> None: ...
    def addApplicationLifecycleHandler(self, p0: IApplicationLifecycleHandler) -> None: ...
    def removeApplicationLifecycleHandler(self, p0: IApplicationLifecycleHandler) -> None: ...

