from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class DefaultConstructorMarker:
    """Forward declaration for ``kotlin.jvm.internal.DefaultConstructorMarker``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.internal.DefaultConstructorMarker')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/internal/DefaultConstructorMarker/
    """
    ...

class FCMParamsObject:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str, p2: str, p3: int, p4: DefaultConstructorMarker) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str, p2: str) -> None: ...
    def getProjectId(self) -> str: ...
    def getAppId(self) -> str: ...
    def getApiKey(self) -> str: ...

from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Continuation:
    """Forward declaration for ``kotlin.coroutines.Continuation``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.coroutines.Continuation')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/coroutines/Continuation/
    """
    ...

class IFeatureFlagsBackendService:
    def fetchRemoteFeatureFlags(self, p0: str, p1: Continuation) -> Any: ...

from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Continuation:
    """Forward declaration for ``kotlin.coroutines.Continuation``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.coroutines.Continuation')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/coroutines/Continuation/
    """
    ...

class IParamsBackendService:
    def fetchParams(self, p0: str, p1: str, p2: Continuation) -> Any: ...

from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class DefaultConstructorMarker:
    """Forward declaration for ``kotlin.jvm.internal.DefaultConstructorMarker``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.internal.DefaultConstructorMarker')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/internal/DefaultConstructorMarker/
    """
    ...

class InfluenceParamsObject:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: int, p1: int, p2: int, p3: int, p4: bool, p5: bool, p6: bool, p7: int, p8: DefaultConstructorMarker) -> None: ...
    @overload
    def __init__(self, p0: int, p1: int, p2: int, p3: int, p4: bool, p5: bool, p6: bool) -> None: ...
    def isIndirectEnabled(self) -> bool: ...
    def isDirectEnabled(self) -> bool: ...
    def isUnattributedEnabled(self) -> bool: ...
    def getIndirectNotificationAttributionWindow(self) -> int: ...
    def getNotificationLimit(self) -> int: ...
    def getIndirectIAMAttributionWindow(self) -> int: ...
    def getIamLimit(self) -> int: ...

from typing import Any, ClassVar, overload
from core.internal.backend.FCMParamsObject import FCMParamsObject
from core.internal.backend.InfluenceParamsObject import InfluenceParamsObject
from core.internal.backend.RemoteLoggingParamsObject import RemoteLoggingParamsObject

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONArray:
    """Forward declaration for ``org.json.JSONArray``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONArray')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...
class DefaultConstructorMarker:
    """Forward declaration for ``kotlin.jvm.internal.DefaultConstructorMarker``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.internal.DefaultConstructorMarker')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/internal/DefaultConstructorMarker/
    """
    ...

class ParamsObject:
    @overload
    def __init__(self, p0: str, p1: bool, p2: bool, p3: JSONArray, p4: bool, p5: bool, p6: bool, p7: bool, p8: bool, p9: bool, p10: bool, p11: bool, p12: int, p13: InfluenceParamsObject, p14: FCMParamsObject, p15: RemoteLoggingParamsObject) -> None: ...
    @overload
    def __init__(self, p0: str, p1: bool, p2: bool, p3: JSONArray, p4: bool, p5: bool, p6: bool, p7: bool, p8: bool, p9: bool, p10: bool, p11: bool, p12: int, p13: InfluenceParamsObject, p14: FCMParamsObject, p15: RemoteLoggingParamsObject, p16: int, p17: DefaultConstructorMarker) -> None: ...
    def getDisableGMSMissingPrompt(self) -> bool: ...
    def setDisableGMSMissingPrompt(self, p0: bool) -> None: ...
    def getEnterprise(self) -> bool: ...
    def getGoogleProjectNumber(self) -> str: ...
    def setGoogleProjectNumber(self, p0: str) -> None: ...
    def setEnterprise(self, p0: bool) -> None: ...
    def getUseIdentityVerification(self) -> bool: ...
    def setUseIdentityVerification(self, p0: bool) -> None: ...
    def getNotificationChannels(self) -> JSONArray: ...
    def setNotificationChannels(self, p0: JSONArray) -> None: ...
    def getFirebaseAnalytics(self) -> bool: ...
    def setFirebaseAnalytics(self, p0: bool) -> None: ...
    def getRestoreTTLFilter(self) -> bool: ...
    def setRestoreTTLFilter(self, p0: bool) -> None: ...
    def getClearGroupOnSummaryClick(self) -> bool: ...
    def setClearGroupOnSummaryClick(self, p0: bool) -> None: ...
    def getReceiveReceiptEnabled(self) -> bool: ...
    def setReceiveReceiptEnabled(self, p0: bool) -> None: ...
    def getUnsubscribeWhenNotificationsDisabled(self) -> bool: ...
    def setUnsubscribeWhenNotificationsDisabled(self, p0: bool) -> None: ...
    def getLocationShared(self) -> bool: ...
    def setLocationShared(self, p0: bool) -> None: ...
    def getRequiresUserPrivacyConsent(self) -> bool: ...
    def setRequiresUserPrivacyConsent(self, p0: bool) -> None: ...
    def getOpRepoExecutionInterval(self) -> int: ...
    def setOpRepoExecutionInterval(self, p0: int) -> None: ...
    def getInfluenceParams(self) -> InfluenceParamsObject: ...
    def setInfluenceParams(self, p0: InfluenceParamsObject) -> None: ...
    def getFcmParams(self) -> FCMParamsObject: ...
    def setFcmParams(self, p0: FCMParamsObject) -> None: ...
    def getRemoteLoggingParams(self) -> RemoteLoggingParamsObject: ...

from typing import Any, ClassVar, overload
from core.internal.backend.RemoteFeatureFlagsResult import RemoteFeatureFlagsResult

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class DefaultConstructorMarker:
    """Forward declaration for ``kotlin.jvm.internal.DefaultConstructorMarker``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.internal.DefaultConstructorMarker')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/internal/DefaultConstructorMarker/
    """
    ...

class RemoteFeatureFlagsFetchOutcome:
    def __init__(self, p0: DefaultConstructorMarker) -> None: ...

    class Success:
        def __init__(self, p0: RemoteFeatureFlagsResult) -> None: ...
        def equals(self, p0: Any) -> bool: ...
        def toString(self) -> str: ...
        def hashCode(self) -> int: ...
        def copy(self, p0: RemoteFeatureFlagsResult) -> Any: ...
        def component1(self) -> RemoteFeatureFlagsResult: ...
        @staticmethod
        def copy$default(p0: Any, p1: RemoteFeatureFlagsResult, p2: int, p3: Any) -> Any: ...
        def getResult(self) -> RemoteFeatureFlagsResult: ...

    class Unavailable:
        INSTANCE: ClassVar[Any]
        def equals(self, p0: Any) -> bool: ...
        def toString(self) -> str: ...
        def hashCode(self) -> int: ...

from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JsonObject:
    """Forward declaration for ``kotlinx.serialization.json.JsonObject``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlinx.serialization.json.JsonObject')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlinx/serialization/json/JsonObject/
    """
    ...
class DefaultConstructorMarker:
    """Forward declaration for ``kotlin.jvm.internal.DefaultConstructorMarker``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.internal.DefaultConstructorMarker')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/internal/DefaultConstructorMarker/
    """
    ...

class RemoteFeatureFlagsResult:
    Companion: ClassVar[Any]
    def __init__(self, p0: list, p1: JsonObject) -> None: ...
    def getMetadata(self) -> JsonObject: ...
    def getEnabledKeys(self) -> list: ...
    @staticmethod
    def access$getEMPTY$cp() -> "RemoteFeatureFlagsResult": ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def copy(self, p0: list, p1: JsonObject) -> "RemoteFeatureFlagsResult": ...
    def component1(self) -> list: ...
    def component2(self) -> JsonObject: ...
    @staticmethod
    def copy$default(p0: "RemoteFeatureFlagsResult", p1: list, p2: JsonObject, p3: int, p4: Any) -> "RemoteFeatureFlagsResult": ...

    class Companion:
        def __init__(self, p0: DefaultConstructorMarker) -> None: ...
        def getEMPTY(self) -> "RemoteFeatureFlagsResult": ...

from typing import Any, ClassVar, overload
from debug.LogLevel import LogLevel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class DefaultConstructorMarker:
    """Forward declaration for ``kotlin.jvm.internal.DefaultConstructorMarker``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.internal.DefaultConstructorMarker')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/internal/DefaultConstructorMarker/
    """
    ...

class RemoteLoggingParamsObject:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: LogLevel, p1: bool) -> None: ...
    @overload
    def __init__(self, p0: LogLevel, p1: bool, p2: int, p3: DefaultConstructorMarker) -> None: ...
    def getLogLevel(self) -> LogLevel: ...
    def isEnabled(self) -> bool: ...

