from typing import Any, ClassVar, overload
from core.internal.config.FCMConfigModel import FCMConfigModel
from core.internal.config.InfluenceConfigModel import InfluenceConfigModel
from core.internal.config.RemoteLoggingConfigModel import RemoteLoggingConfigModel
from user.internal.jwt.JwtRequirement import JwtRequirement

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONArray:
    """Forward declaration for ``org.json.JSONArray``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONArray')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class ConfigModel:
    def __init__(self) -> None: ...
    def getAppId(self) -> str: ...
    def getGoogleProjectNumber(self) -> str: ...
    def setGoogleProjectNumber(self, p0: str) -> None: ...
    def getEnterprise(self) -> bool: ...
    def setEnterprise(self, p0: bool) -> None: ...
    def getNotificationChannels(self) -> JSONArray: ...
    def setNotificationChannels(self, p0: JSONArray) -> None: ...
    def getFirebaseAnalytics(self) -> bool: ...
    def setFirebaseAnalytics(self, p0: bool) -> None: ...
    def getRestoreTTLFilter(self) -> bool: ...
    def setRestoreTTLFilter(self, p0: bool) -> None: ...
    def getClearGroupOnSummaryClick(self) -> bool: ...
    def setClearGroupOnSummaryClick(self, p0: bool) -> None: ...
    def getReceiveReceiptEnabled(self) -> bool: ...
    def setReceiveReceiptEnabled(self, p0: bool) -> None: ...
    def getUnsubscribeWhenNotificationsDisabled(self) -> bool: ...
    def setUnsubscribeWhenNotificationsDisabled(self, p0: bool) -> None: ...
    def getLocationShared(self) -> bool: ...
    def setLocationShared(self, p0: bool) -> None: ...
    def getOpRepoExecutionInterval(self) -> int: ...
    def setOpRepoExecutionInterval(self, p0: int) -> None: ...
    def getInfluenceParams(self) -> InfluenceConfigModel: ...
    def getFcmParams(self) -> FCMConfigModel: ...
    def getRemoteLoggingParams(self) -> RemoteLoggingConfigModel: ...
    def getDisableGMSMissingPrompt(self) -> bool: ...
    def getConsentRequired(self) -> bool: ...
    def setConsentRequired(self, p0: bool) -> None: ...
    def getConsentGiven(self) -> bool: ...
    def setConsentGiven(self, p0: bool) -> None: ...
    def setDisableGMSMissingPrompt(self, p0: bool) -> None: ...
    def setAppId(self, p0: str) -> None: ...
    def setInitializedWithRemote(self, p0: bool) -> None: ...
    def isInitializedWithRemote(self) -> bool: ...
    def getPushSubscriptionId(self) -> str: ...
    def setPushSubscriptionId(self, p0: str) -> None: ...
    def getApiUrl(self) -> str: ...
    def setApiUrl(self, p0: str) -> None: ...
    def getUserRejectedGMSUpdate(self) -> bool: ...
    def setUserRejectedGMSUpdate(self, p0: bool) -> None: ...
    def getHttpTimeout(self) -> int: ...
    def setHttpTimeout(self, p0: int) -> None: ...
    def getHttpGetTimeout(self) -> int: ...
    def setHttpGetTimeout(self, p0: int) -> None: ...
    def getHttpRetryAfterParseFailFallback(self) -> int: ...
    def setHttpRetryAfterParseFailFallback(self, p0: int) -> None: ...
    def getSessionFocusTimeout(self) -> int: ...
    def setSessionFocusTimeout(self, p0: int) -> None: ...
    def getOpRepoPostWakeDelay(self) -> int: ...
    def setOpRepoPostWakeDelay(self, p0: int) -> None: ...
    def getOpRepoPostCreateDelay(self) -> int: ...
    def setOpRepoPostCreateDelay(self, p0: int) -> None: ...
    def getOpRepoPostCreateRetryUpTo(self) -> int: ...
    def setOpRepoPostCreateRetryUpTo(self, p0: int) -> None: ...
    def getOpRepoDefaultFailRetryBackoff(self) -> int: ...
    def setOpRepoDefaultFailRetryBackoff(self, p0: int) -> None: ...
    def getFetchIAMMinInterval(self) -> int: ...
    def setFetchIAMMinInterval(self, p0: int) -> None: ...
    def getForegroundFetchNotificationPermissionInterval(self) -> int: ...
    def setForegroundFetchNotificationPermissionInterval(self, p0: int) -> None: ...
    def getBackgroundFetchNotificationPermissionInterval(self) -> int: ...
    def setBackgroundFetchNotificationPermissionInterval(self, p0: int) -> None: ...
    def getUseIdentityVerification$com_onesignal_core(self) -> JwtRequirement: ...
    def setUseIdentityVerification$com_onesignal_core(self, p0: JwtRequirement) -> None: ...
    def getSdkRemoteFeatureFlags(self) -> list: ...
    def setSdkRemoteFeatureFlags(self, p0: list) -> None: ...
    def getSdkRemoteFeatureFlagMetadata(self) -> str: ...
    def setSdkRemoteFeatureFlagMetadata(self, p0: str) -> None: ...

    class WhenMappings:
        $EnumSwitchMapping$0: ClassVar[Any]

from typing import Any, ClassVar, overload

class ConfigModelChangeTags:
    INSTANCE: ClassVar["ConfigModelChangeTags"]
    REMOTE_FEATURE_FLAGS: ClassVar[str]

from typing import Any, ClassVar, overload
from core.internal.preferences.IPreferencesService import IPreferencesService

class ConfigModelStore:
    def __init__(self, p0: IPreferencesService) -> None: ...

from typing import Any, ClassVar, overload

class ConfigModelStoreKt:
    CONFIG_NAME_SPACE: ClassVar[str]

from typing import Any, ClassVar, overload
from common.modeling.Model import Model

class FCMConfigModel:
    def __init__(self, p0: Model, p1: str) -> None: ...
    def getProjectId(self) -> str: ...
    def getAppId(self) -> str: ...
    def getApiKey(self) -> str: ...
    def setProjectId(self, p0: str) -> None: ...
    def setApiKey(self, p0: str) -> None: ...
    def setAppId(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload
from common.modeling.Model import Model

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class DefaultConstructorMarker:
    """Forward declaration for ``kotlin.jvm.internal.DefaultConstructorMarker``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.internal.DefaultConstructorMarker')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/internal/DefaultConstructorMarker/
    """
    ...

class InfluenceConfigModel:
    Companion: ClassVar[Any]
    DEFAULT_INDIRECT_ATTRIBUTION_WINDOW: ClassVar[int]
    DEFAULT_NOTIFICATION_LIMIT: ClassVar[int]
    def __init__(self, p0: Model, p1: str) -> None: ...
    def isDirectEnabled(self) -> bool: ...
    def isIndirectEnabled(self) -> bool: ...
    def isUnattributedEnabled(self) -> bool: ...
    def getIndirectNotificationAttributionWindow(self) -> int: ...
    def getNotificationLimit(self) -> int: ...
    def getIndirectIAMAttributionWindow(self) -> int: ...
    def getIamLimit(self) -> int: ...
    def setIndirectNotificationAttributionWindow(self, p0: int) -> None: ...
    def setNotificationLimit(self, p0: int) -> None: ...
    def setIndirectIAMAttributionWindow(self, p0: int) -> None: ...
    def setIamLimit(self, p0: int) -> None: ...
    def setDirectEnabled(self, p0: bool) -> None: ...
    def setIndirectEnabled(self, p0: bool) -> None: ...
    def setUnattributedEnabled(self, p0: bool) -> None: ...

    class Companion:
        def __init__(self, p0: DefaultConstructorMarker) -> None: ...

from typing import Any, ClassVar, overload
from common.modeling.Model import Model
from debug.LogLevel import LogLevel

class RemoteLoggingConfigModel:
    def __init__(self, p0: Model, p1: str) -> None: ...
    def isEnabled(self) -> bool: ...
    def getLogLevel(self) -> LogLevel: ...
    def setLogLevel(self, p0: LogLevel) -> None: ...
    def setEnabled(self, p0: bool) -> None: ...

