from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

class ConfigModel(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/core/internal/config/ConfigModel"
    __javaconstructor__ = [("()V", False)]
    getDisableGMSMissingPrompt = JavaMethod("()Z")
    getConsentRequired = JavaMethod("()Ljava/lang/Boolean;")
    setConsentRequired = JavaMethod("(Ljava/lang/Boolean;)V")
    getConsentGiven = JavaMethod("()Ljava/lang/Boolean;")
    setConsentGiven = JavaMethod("(Ljava/lang/Boolean;)V")
    setDisableGMSMissingPrompt = JavaMethod("(Z)V")
    getAppId = JavaMethod("()Ljava/lang/String;")
    getEnterprise = JavaMethod("()Z")
    getGoogleProjectNumber = JavaMethod("()Ljava/lang/String;")
    setGoogleProjectNumber = JavaMethod("(Ljava/lang/String;)V")
    setEnterprise = JavaMethod("(Z)V")
    getNotificationChannels = JavaMethod("()Lorg/json/JSONArray;")
    setNotificationChannels = JavaMethod("(Lorg/json/JSONArray;)V")
    getFirebaseAnalytics = JavaMethod("()Z")
    setFirebaseAnalytics = JavaMethod("(Z)V")
    getRestoreTTLFilter = JavaMethod("()Z")
    setRestoreTTLFilter = JavaMethod("(Z)V")
    getClearGroupOnSummaryClick = JavaMethod("()Z")
    setClearGroupOnSummaryClick = JavaMethod("(Z)V")
    getReceiveReceiptEnabled = JavaMethod("()Z")
    setReceiveReceiptEnabled = JavaMethod("(Z)V")
    getUnsubscribeWhenNotificationsDisabled = JavaMethod("()Z")
    setUnsubscribeWhenNotificationsDisabled = JavaMethod("(Z)V")
    getLocationShared = JavaMethod("()Z")
    setLocationShared = JavaMethod("(Z)V")
    getOpRepoExecutionInterval = JavaMethod("()J")
    setOpRepoExecutionInterval = JavaMethod("(J)V")
    getInfluenceParams = JavaMethod("()Lcom/onesignal/core/internal/config/InfluenceConfigModel;")
    getFcmParams = JavaMethod("()Lcom/onesignal/core/internal/config/FCMConfigModel;")
    getRemoteLoggingParams = JavaMethod("()Lcom/onesignal/core/internal/config/RemoteLoggingConfigModel;")
    isInitializedWithRemote = JavaMethod("()Z")
    setInitializedWithRemote = JavaMethod("(Z)V")
    setAppId = JavaMethod("(Ljava/lang/String;)V")
    getPushSubscriptionId = JavaMethod("()Ljava/lang/String;")
    setPushSubscriptionId = JavaMethod("(Ljava/lang/String;)V")
    getApiUrl = JavaMethod("()Ljava/lang/String;")
    setApiUrl = JavaMethod("(Ljava/lang/String;)V")
    getUserRejectedGMSUpdate = JavaMethod("()Z")
    setUserRejectedGMSUpdate = JavaMethod("(Z)V")
    getHttpTimeout = JavaMethod("()I")
    setHttpTimeout = JavaMethod("(I)V")
    getHttpGetTimeout = JavaMethod("()I")
    setHttpGetTimeout = JavaMethod("(I)V")
    getHttpRetryAfterParseFailFallback = JavaMethod("()I")
    setHttpRetryAfterParseFailFallback = JavaMethod("(I)V")
    getSessionFocusTimeout = JavaMethod("()J")
    setSessionFocusTimeout = JavaMethod("(J)V")
    getOpRepoPostWakeDelay = JavaMethod("()J")
    setOpRepoPostWakeDelay = JavaMethod("(J)V")
    getOpRepoPostCreateDelay = JavaMethod("()J")
    setOpRepoPostCreateDelay = JavaMethod("(J)V")
    getOpRepoPostCreateRetryUpTo = JavaMethod("()J")
    setOpRepoPostCreateRetryUpTo = JavaMethod("(J)V")
    getOpRepoDefaultFailRetryBackoff = JavaMethod("()J")
    setOpRepoDefaultFailRetryBackoff = JavaMethod("(J)V")
    getFetchIAMMinInterval = JavaMethod("()J")
    setFetchIAMMinInterval = JavaMethod("(J)V")
    getForegroundFetchNotificationPermissionInterval = JavaMethod("()J")
    setForegroundFetchNotificationPermissionInterval = JavaMethod("(J)V")
    getBackgroundFetchNotificationPermissionInterval = JavaMethod("()J")
    setBackgroundFetchNotificationPermissionInterval = JavaMethod("(J)V")
    getUseIdentityVerification$com_onesignal_core = JavaMethod("()Lcom/onesignal/user/internal/jwt/JwtRequirement;")
    setUseIdentityVerification$com_onesignal_core = JavaMethod("(Lcom/onesignal/user/internal/jwt/JwtRequirement;)V")
    getSdkRemoteFeatureFlags = JavaMethod("()Ljava/util/List;")
    setSdkRemoteFeatureFlags = JavaMethod("(Ljava/util/List;)V")
    getSdkRemoteFeatureFlagMetadata = JavaMethod("()Ljava/lang/String;")
    setSdkRemoteFeatureFlagMetadata = JavaMethod("(Ljava/lang/String;)V")

    class WhenMappings(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "com/onesignal/core/internal/config/ConfigModel$WhenMappings"
        $EnumSwitchMapping$0 = JavaStaticField("[I")

class ConfigModelChangeTags(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/core/internal/config/ConfigModelChangeTags"
    INSTANCE = JavaStaticField("Lcom/onesignal/core/internal/config/ConfigModelChangeTags;")
    REMOTE_FEATURE_FLAGS = JavaStaticField("Ljava/lang/String;")

class ConfigModelStore(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/core/internal/config/ConfigModelStore"
    __javaconstructor__ = [("(Lcom/onesignal/core/internal/preferences/IPreferencesService;)V", False)]

class ConfigModelStoreKt(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/core/internal/config/ConfigModelStoreKt"
    CONFIG_NAME_SPACE = JavaStaticField("Ljava/lang/String;")

class FCMConfigModel(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/core/internal/config/FCMConfigModel"
    __javaconstructor__ = [("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;)V", False)]
    getProjectId = JavaMethod("()Ljava/lang/String;")
    getAppId = JavaMethod("()Ljava/lang/String;")
    getApiKey = JavaMethod("()Ljava/lang/String;")
    setAppId = JavaMethod("(Ljava/lang/String;)V")
    setProjectId = JavaMethod("(Ljava/lang/String;)V")
    setApiKey = JavaMethod("(Ljava/lang/String;)V")

class InfluenceConfigModel(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/core/internal/config/InfluenceConfigModel"
    __javaconstructor__ = [("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;)V", False)]
    Companion = JavaStaticField("Lcom/onesignal/core/internal/config/InfluenceConfigModel$Companion;")
    DEFAULT_INDIRECT_ATTRIBUTION_WINDOW = JavaStaticField("I")
    DEFAULT_NOTIFICATION_LIMIT = JavaStaticField("I")
    isIndirectEnabled = JavaMethod("()Z")
    isDirectEnabled = JavaMethod("()Z")
    isUnattributedEnabled = JavaMethod("()Z")
    getIndirectNotificationAttributionWindow = JavaMethod("()I")
    getNotificationLimit = JavaMethod("()I")
    getIndirectIAMAttributionWindow = JavaMethod("()I")
    getIamLimit = JavaMethod("()I")
    setNotificationLimit = JavaMethod("(I)V")
    setIndirectNotificationAttributionWindow = JavaMethod("(I)V")
    setIamLimit = JavaMethod("(I)V")
    setIndirectIAMAttributionWindow = JavaMethod("(I)V")
    setDirectEnabled = JavaMethod("(Z)V")
    setIndirectEnabled = JavaMethod("(Z)V")
    setUnattributedEnabled = JavaMethod("(Z)V")

    class Companion(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "com/onesignal/core/internal/config/InfluenceConfigModel$Companion"
        __javaconstructor__ = [("(Lkotlin/jvm/internal/DefaultConstructorMarker;)V", False)]

class RemoteLoggingConfigModel(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/core/internal/config/RemoteLoggingConfigModel"
    __javaconstructor__ = [("(Lcom/onesignal/common/modeling/Model;Ljava/lang/String;)V", False)]
    getLogLevel = JavaMethod("()Lcom/onesignal/debug/LogLevel;")
    setLogLevel = JavaMethod("(Lcom/onesignal/debug/LogLevel;)V")
    isEnabled = JavaMethod("()Z")
    setEnabled = JavaMethod("(Z)V")