from typing import Any, ClassVar, overload

class ICursor:
    def getInt(self, p0: str) -> int: ...
    def getLong(self, p0: str) -> int: ...
    def getFloat(self, p0: str) -> float: ...
    def getCount(self) -> int: ...
    def getString(self, p0: str) -> str: ...
    def moveToNext(self) -> bool: ...
    def getOptString(self, p0: str) -> str: ...
    def moveToFirst(self) -> bool: ...
    def getOptFloat(self, p0: str) -> float: ...
    def getOptLong(self, p0: str) -> int: ...
    def getOptInt(self, p0: str) -> int: ...

from typing import Any, ClassVar, overload
from android.content.ContentValues import ContentValues

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Function1:
    """Forward declaration for ``kotlin.jvm.functions.Function1``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.functions.Function1')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/functions/Function1/
    """
    ...

class IDatabase:
    def update(self, p0: str, p1: ContentValues, p2: str, p3: Any) -> int: ...
    def insert(self, p0: str, p1: str, p2: ContentValues) -> None: ...
    def delete(self, p0: str, p1: str, p2: Any) -> None: ...
    def query(self, p0: str, p1: Any, p2: str, p3: Any, p4: str, p5: str, p6: str, p7: str, p8: Function1) -> None: ...
    def insertOrThrow(self, p0: str, p1: str, p2: ContentValues) -> None: ...

    class DefaultImpls:
        @staticmethod
        def query$default(p0: "IDatabase", p1: str, p2: Any, p3: str, p4: Any, p5: str, p6: str, p7: str, p8: str, p9: Function1, p10: int, p11: Any) -> None: ...

from typing import Any, ClassVar, overload
from core.internal.database.IDatabase import IDatabase

class IDatabaseProvider:
    def getOs(self) -> IDatabase: ...

