from typing import Any, ClassVar, overload

class ILocationCapturer:
    def getLocationCoarse(self) -> bool: ...
    def setLocationCoarse(self, p0: bool) -> None: ...
    def captureLastLocation(self) -> None: ...

