from typing import Any, ClassVar, overload

class LocationConstants:
    INSTANCE: ClassVar["LocationConstants"]
    TIME_FOREGROUND_SEC: ClassVar[int]
    TIME_BACKGROUND_SEC: ClassVar[int]
    FOREGROUND_UPDATE_TIME_MS: ClassVar[int]
    BACKGROUND_UPDATE_TIME_MS: ClassVar[int]
    ANDROID_FINE_LOCATION_PERMISSION_STRING: ClassVar[str]
    ANDROID_COARSE_LOCATION_PERMISSION_STRING: ClassVar[str]
    ANDROID_BACKGROUND_LOCATION_PERMISSION_STRING: ClassVar[str]

from typing import Any, ClassVar, overload

class LocationPoint:
    def __init__(self) -> None: ...
    def toString(self) -> str: ...
    def getType(self) -> int: ...
    def getLat(self) -> float: ...
    def setLog(self, p0: float) -> None: ...
    def getBg(self) -> bool: ...
    def setBg(self, p0: bool) -> None: ...
    def setLat(self, p0: float) -> None: ...
    def getLog(self) -> float: ...
    def getAccuracy(self) -> float: ...
    def setAccuracy(self, p0: float) -> None: ...
    def setType(self, p0: int) -> None: ...
    def setTimeStamp(self, p0: int) -> None: ...
    def getTimeStamp(self) -> int: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context

class LocationUtils:
    INSTANCE: ClassVar["LocationUtils"]
    def hasGMSLocationLibrary(self) -> bool: ...
    def hasHMSLocationLibrary(self) -> bool: ...
    def hasLocationPermission(self, p0: Context) -> bool: ...

