from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

class ChannelTracker(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/session/internal/influence/impl/ChannelTracker"
    __javaconstructor__ = [("(Lcom/onesignal/session/internal/influence/impl/InfluenceDataRepository;Lcom/onesignal/core/internal/time/ITime;)V", False)]
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    getInfluenceType = JavaMethod("()Lcom/onesignal/session/internal/influence/InfluenceType;")
    setInfluenceType = JavaMethod("(Lcom/onesignal/session/internal/influence/InfluenceType;)V")
    getDirectId = JavaMethod("()Ljava/lang/String;")
    getIndirectAttributionWindow = JavaMethod("()I")
    getIndirectIds = JavaMethod("()Lorg/json/JSONArray;")
    setIndirectIds = JavaMethod("(Lorg/json/JSONArray;)V")
    setDirectId = JavaMethod("(Ljava/lang/String;)V")
    getLastChannelObjects = JavaMethod("()Lorg/json/JSONArray;")
    getChannelLimit = JavaMethod("()I")
    getLastChannelObjectsReceivedByNewId = JavaMethod("(Ljava/lang/String;)Lorg/json/JSONArray;")
    saveChannelObjects = JavaMethod("(Lorg/json/JSONArray;)V")
    initInfluencedTypeFromCache = JavaMethod("()V")
    getCurrentSessionInfluence = JavaMethod("()Lcom/onesignal/session/internal/influence/Influence;")
    getLastReceivedIds = JavaMethod("()Lorg/json/JSONArray;")
    resetAndInitInfluence = JavaMethod("()V")
    saveLastId = JavaMethod("(Ljava/lang/String;)V")

class IChannelTracker(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/session/internal/influence/impl/IChannelTracker"
    getInfluenceType = JavaMethod("()Lcom/onesignal/session/internal/influence/InfluenceType;")
    setInfluenceType = JavaMethod("(Lcom/onesignal/session/internal/influence/InfluenceType;)V")
    getDirectId = JavaMethod("()Ljava/lang/String;")
    getIndirectIds = JavaMethod("()Lorg/json/JSONArray;")
    setIndirectIds = JavaMethod("(Lorg/json/JSONArray;)V")
    setDirectId = JavaMethod("(Ljava/lang/String;)V")
    getCurrentSessionInfluence = JavaMethod("()Lcom/onesignal/session/internal/influence/Influence;")
    getChannelType = JavaMethod("()Lcom/onesignal/session/internal/influence/InfluenceChannel;")
    getLastReceivedIds = JavaMethod("()Lorg/json/JSONArray;")
    getIdTag = JavaMethod("()Ljava/lang/String;")
    resetAndInitInfluence = JavaMethod("()V")
    cacheState = JavaMethod("()V")
    saveLastId = JavaMethod("(Ljava/lang/String;)V")

class IInfluenceDataRepository(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/session/internal/influence/impl/IInfluenceDataRepository"
    isDirectInfluenceEnabled = JavaMethod("()Z")
    isIndirectInfluenceEnabled = JavaMethod("()Z")
    isUnattributedInfluenceEnabled = JavaMethod("()Z")
    getNotificationLimit = JavaMethod("()I")
    getIamLimit = JavaMethod("()I")
    cacheNotificationInfluenceType = JavaMethod("(Lcom/onesignal/session/internal/influence/InfluenceType;)V")
    getNotificationCachedInfluenceType = JavaMethod("()Lcom/onesignal/session/internal/influence/InfluenceType;")
    cacheIAMInfluenceType = JavaMethod("(Lcom/onesignal/session/internal/influence/InfluenceType;)V")
    getIamCachedInfluenceType = JavaMethod("()Lcom/onesignal/session/internal/influence/InfluenceType;")
    cacheNotificationOpenId = JavaMethod("(Ljava/lang/String;)V")
    getCachedNotificationOpenId = JavaMethod("()Ljava/lang/String;")
    saveNotifications = JavaMethod("(Lorg/json/JSONArray;)V")
    saveIAMs = JavaMethod("(Lorg/json/JSONArray;)V")
    getLastNotificationsReceivedData = JavaMethod("()Lorg/json/JSONArray;")
    getLastIAMsReceivedData = JavaMethod("()Lorg/json/JSONArray;")
    getNotificationIndirectAttributionWindow = JavaMethod("()I")
    getIamIndirectAttributionWindow = JavaMethod("()I")

class InAppMessageTracker(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/session/internal/influence/impl/InAppMessageTracker"
    __javaconstructor__ = [("(Lcom/onesignal/session/internal/influence/impl/InfluenceDataRepository;Lcom/onesignal/core/internal/time/ITime;)V", False)]
    getIndirectAttributionWindow = JavaMethod("()I")
    getLastChannelObjects = JavaMethod("()Lorg/json/JSONArray;")
    getChannelLimit = JavaMethod("()I")
    getLastChannelObjectsReceivedByNewId = JavaMethod("(Ljava/lang/String;)Lorg/json/JSONArray;")
    saveChannelObjects = JavaMethod("(Lorg/json/JSONArray;)V")
    initInfluencedTypeFromCache = JavaMethod("()V")
    getChannelType = JavaMethod("()Lcom/onesignal/session/internal/influence/InfluenceChannel;")
    getIdTag = JavaMethod("()Ljava/lang/String;")
    cacheState = JavaMethod("()V")

class InfluenceConstants(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/session/internal/influence/impl/InfluenceConstants"
    INSTANCE = JavaStaticField("Lcom/onesignal/session/internal/influence/impl/InfluenceConstants;")
    TIME = JavaStaticField("Ljava/lang/String;")
    IAM_ID_TAG = JavaStaticField("Ljava/lang/String;")
    DIRECT_TAG = JavaStaticField("Ljava/lang/String;")
    NOTIFICATIONS_IDS = JavaStaticField("Ljava/lang/String;")
    NOTIFICATION_ID_TAG = JavaStaticField("Ljava/lang/String;")
    PREFS_OS_LAST_ATTRIBUTED_NOTIFICATION_OPEN = JavaStaticField("Ljava/lang/String;")
    PREFS_OS_LAST_NOTIFICATIONS_RECEIVED = JavaStaticField("Ljava/lang/String;")
    PREFS_OS_LAST_IAMS_RECEIVED = JavaStaticField("Ljava/lang/String;")
    PREFS_OS_OUTCOMES_CURRENT_NOTIFICATION_INFLUENCE = JavaStaticField("Ljava/lang/String;")
    PREFS_OS_OUTCOMES_CURRENT_IAM_INFLUENCE = JavaStaticField("Ljava/lang/String;")
    getNOTIFICATION_TAG = JavaMethod("()Ljava/lang/String;")
    getIAM_TAG = JavaMethod("()Ljava/lang/String;")

class InfluenceDataRepository(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/session/internal/influence/impl/InfluenceDataRepository"
    __javaconstructor__ = [("(Lcom/onesignal/core/internal/preferences/IPreferencesService;Lcom/onesignal/core/internal/config/ConfigModelStore;)V", False)]
    isDirectInfluenceEnabled = JavaMethod("()Z")
    isIndirectInfluenceEnabled = JavaMethod("()Z")
    isUnattributedInfluenceEnabled = JavaMethod("()Z")
    getNotificationLimit = JavaMethod("()I")
    getIamLimit = JavaMethod("()I")
    cacheNotificationInfluenceType = JavaMethod("(Lcom/onesignal/session/internal/influence/InfluenceType;)V")
    getNotificationCachedInfluenceType = JavaMethod("()Lcom/onesignal/session/internal/influence/InfluenceType;")
    cacheIAMInfluenceType = JavaMethod("(Lcom/onesignal/session/internal/influence/InfluenceType;)V")
    getIamCachedInfluenceType = JavaMethod("()Lcom/onesignal/session/internal/influence/InfluenceType;")
    cacheNotificationOpenId = JavaMethod("(Ljava/lang/String;)V")
    getCachedNotificationOpenId = JavaMethod("()Ljava/lang/String;")
    saveNotifications = JavaMethod("(Lorg/json/JSONArray;)V")
    saveIAMs = JavaMethod("(Lorg/json/JSONArray;)V")
    getLastNotificationsReceivedData = JavaMethod("()Lorg/json/JSONArray;")
    getLastIAMsReceivedData = JavaMethod("()Lorg/json/JSONArray;")
    getNotificationIndirectAttributionWindow = JavaMethod("()I")
    getIamIndirectAttributionWindow = JavaMethod("()I")

class InfluenceManager(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/session/internal/influence/impl/InfluenceManager"
    __javaconstructor__ = [("(Lcom/onesignal/session/internal/session/ISessionService;Lcom/onesignal/core/internal/application/IApplicationService;Lcom/onesignal/core/internal/config/ConfigModelStore;Lcom/onesignal/core/internal/preferences/IPreferencesService;Lcom/onesignal/core/internal/time/ITime;)V", False)]
    onSessionStarted = JavaMethod("()V")
    onSessionActive = JavaMethod("()V")
    onSessionEnded = JavaMethod("(J)V")
    onNotificationReceived = JavaMethod("(Ljava/lang/String;)V")
    onInAppMessageDisplayed = JavaMethod("(Ljava/lang/String;)V")
    onDirectInfluenceFromIAM = JavaMethod("(Ljava/lang/String;)V")
    getInfluences = JavaMethod("()Ljava/util/List;")
    onDirectInfluenceFromNotification = JavaMethod("(Ljava/lang/String;)V")
    onInAppMessageDismissed = JavaMethod("()V")

class NotificationTracker(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/session/internal/influence/impl/NotificationTracker"
    __javaconstructor__ = [("(Lcom/onesignal/session/internal/influence/impl/InfluenceDataRepository;Lcom/onesignal/core/internal/time/ITime;)V", False)]
    getIndirectAttributionWindow = JavaMethod("()I")
    getLastChannelObjects = JavaMethod("()Lorg/json/JSONArray;")
    getChannelLimit = JavaMethod("()I")
    getLastChannelObjectsReceivedByNewId = JavaMethod("(Ljava/lang/String;)Lorg/json/JSONArray;")
    saveChannelObjects = JavaMethod("(Lorg/json/JSONArray;)V")
    initInfluencedTypeFromCache = JavaMethod("()V")
    getChannelType = JavaMethod("()Lcom/onesignal/session/internal/influence/InfluenceChannel;")
    getIdTag = JavaMethod("()Ljava/lang/String;")
    cacheState = JavaMethod("()V")