from typing import Any, ClassVar, overload
from core.internal.time.ITime import ITime
from session.internal.influence.Influence import Influence
from session.internal.influence.InfluenceType import InfluenceType
from session.internal.influence.impl.InfluenceDataRepository import InfluenceDataRepository

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONArray:
    """Forward declaration for ``org.json.JSONArray``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONArray')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class ChannelTracker:
    def __init__(self, p0: InfluenceDataRepository, p1: ITime) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getIndirectIds(self) -> JSONArray: ...
    def setIndirectIds(self, p0: JSONArray) -> None: ...
    def setDirectId(self, p0: str) -> None: ...
    def getLastChannelObjects(self) -> JSONArray: ...
    def getChannelLimit(self) -> int: ...
    def getIndirectAttributionWindow(self) -> int: ...
    def getLastChannelObjectsReceivedByNewId(self, p0: str) -> JSONArray: ...
    def saveChannelObjects(self, p0: JSONArray) -> None: ...
    def initInfluencedTypeFromCache(self) -> None: ...
    def getCurrentSessionInfluence(self) -> Influence: ...
    def getLastReceivedIds(self) -> JSONArray: ...
    def resetAndInitInfluence(self) -> None: ...
    def saveLastId(self, p0: str) -> None: ...
    def setInfluenceType(self, p0: InfluenceType) -> None: ...
    def getInfluenceType(self) -> InfluenceType: ...
    def getDirectId(self) -> str: ...

from typing import Any, ClassVar, overload
from session.internal.influence.Influence import Influence
from session.internal.influence.InfluenceChannel import InfluenceChannel
from session.internal.influence.InfluenceType import InfluenceType

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONArray:
    """Forward declaration for ``org.json.JSONArray``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONArray')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class IChannelTracker:
    def getIndirectIds(self) -> JSONArray: ...
    def setIndirectIds(self, p0: JSONArray) -> None: ...
    def setDirectId(self, p0: str) -> None: ...
    def getCurrentSessionInfluence(self) -> Influence: ...
    def getChannelType(self) -> InfluenceChannel: ...
    def getLastReceivedIds(self) -> JSONArray: ...
    def getIdTag(self) -> str: ...
    def resetAndInitInfluence(self) -> None: ...
    def cacheState(self) -> None: ...
    def saveLastId(self, p0: str) -> None: ...
    def setInfluenceType(self, p0: InfluenceType) -> None: ...
    def getInfluenceType(self) -> InfluenceType: ...
    def getDirectId(self) -> str: ...

from typing import Any, ClassVar, overload
from session.internal.influence.InfluenceType import InfluenceType

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONArray:
    """Forward declaration for ``org.json.JSONArray``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONArray')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class IInfluenceDataRepository:
    def getNotificationLimit(self) -> int: ...
    def getIamLimit(self) -> int: ...
    def isDirectInfluenceEnabled(self) -> bool: ...
    def isIndirectInfluenceEnabled(self) -> bool: ...
    def isUnattributedInfluenceEnabled(self) -> bool: ...
    def cacheNotificationInfluenceType(self, p0: InfluenceType) -> None: ...
    def saveIAMs(self, p0: JSONArray) -> None: ...
    def getNotificationCachedInfluenceType(self) -> InfluenceType: ...
    def cacheIAMInfluenceType(self, p0: InfluenceType) -> None: ...
    def getIamCachedInfluenceType(self) -> InfluenceType: ...
    def cacheNotificationOpenId(self, p0: str) -> None: ...
    def getCachedNotificationOpenId(self) -> str: ...
    def saveNotifications(self, p0: JSONArray) -> None: ...
    def getLastNotificationsReceivedData(self) -> JSONArray: ...
    def getLastIAMsReceivedData(self) -> JSONArray: ...
    def getNotificationIndirectAttributionWindow(self) -> int: ...
    def getIamIndirectAttributionWindow(self) -> int: ...

from typing import Any, ClassVar, overload
from core.internal.time.ITime import ITime
from session.internal.influence.InfluenceChannel import InfluenceChannel
from session.internal.influence.impl.InfluenceDataRepository import InfluenceDataRepository

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONArray:
    """Forward declaration for ``org.json.JSONArray``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONArray')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class InAppMessageTracker:
    def __init__(self, p0: InfluenceDataRepository, p1: ITime) -> None: ...
    def getLastChannelObjects(self) -> JSONArray: ...
    def getChannelLimit(self) -> int: ...
    def getIndirectAttributionWindow(self) -> int: ...
    def getLastChannelObjectsReceivedByNewId(self, p0: str) -> JSONArray: ...
    def saveChannelObjects(self, p0: JSONArray) -> None: ...
    def initInfluencedTypeFromCache(self) -> None: ...
    def getChannelType(self) -> InfluenceChannel: ...
    def getIdTag(self) -> str: ...
    def cacheState(self) -> None: ...

from typing import Any, ClassVar, overload

class InfluenceConstants:
    INSTANCE: ClassVar["InfluenceConstants"]
    TIME: ClassVar[str]
    IAM_ID_TAG: ClassVar[str]
    DIRECT_TAG: ClassVar[str]
    NOTIFICATIONS_IDS: ClassVar[str]
    NOTIFICATION_ID_TAG: ClassVar[str]
    PREFS_OS_LAST_ATTRIBUTED_NOTIFICATION_OPEN: ClassVar[str]
    PREFS_OS_LAST_NOTIFICATIONS_RECEIVED: ClassVar[str]
    PREFS_OS_LAST_IAMS_RECEIVED: ClassVar[str]
    PREFS_OS_OUTCOMES_CURRENT_NOTIFICATION_INFLUENCE: ClassVar[str]
    PREFS_OS_OUTCOMES_CURRENT_IAM_INFLUENCE: ClassVar[str]
    def getIAM_TAG(self) -> str: ...
    def getNOTIFICATION_TAG(self) -> str: ...

from typing import Any, ClassVar, overload
from core.internal.config.ConfigModelStore import ConfigModelStore
from core.internal.preferences.IPreferencesService import IPreferencesService
from session.internal.influence.InfluenceType import InfluenceType

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONArray:
    """Forward declaration for ``org.json.JSONArray``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONArray')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class InfluenceDataRepository:
    def __init__(self, p0: IPreferencesService, p1: ConfigModelStore) -> None: ...
    def getNotificationLimit(self) -> int: ...
    def getIamLimit(self) -> int: ...
    def isDirectInfluenceEnabled(self) -> bool: ...
    def isIndirectInfluenceEnabled(self) -> bool: ...
    def isUnattributedInfluenceEnabled(self) -> bool: ...
    def cacheNotificationInfluenceType(self, p0: InfluenceType) -> None: ...
    def saveIAMs(self, p0: JSONArray) -> None: ...
    def getNotificationCachedInfluenceType(self) -> InfluenceType: ...
    def cacheIAMInfluenceType(self, p0: InfluenceType) -> None: ...
    def getIamCachedInfluenceType(self) -> InfluenceType: ...
    def cacheNotificationOpenId(self, p0: str) -> None: ...
    def getCachedNotificationOpenId(self) -> str: ...
    def saveNotifications(self, p0: JSONArray) -> None: ...
    def getLastNotificationsReceivedData(self) -> JSONArray: ...
    def getLastIAMsReceivedData(self) -> JSONArray: ...
    def getNotificationIndirectAttributionWindow(self) -> int: ...
    def getIamIndirectAttributionWindow(self) -> int: ...

from typing import Any, ClassVar, overload
from core.internal.application.IApplicationService import IApplicationService
from core.internal.config.ConfigModelStore import ConfigModelStore
from core.internal.preferences.IPreferencesService import IPreferencesService
from core.internal.time.ITime import ITime
from session.internal.session.ISessionService import ISessionService

class InfluenceManager:
    def __init__(self, p0: ISessionService, p1: IApplicationService, p2: ConfigModelStore, p3: IPreferencesService, p4: ITime) -> None: ...
    def onNotificationReceived(self, p0: str) -> None: ...
    def getInfluences(self) -> list: ...
    def onInAppMessageDisplayed(self, p0: str) -> None: ...
    def onDirectInfluenceFromNotification(self, p0: str) -> None: ...
    def onDirectInfluenceFromIAM(self, p0: str) -> None: ...
    def onInAppMessageDismissed(self) -> None: ...
    def onSessionStarted(self) -> None: ...
    def onSessionActive(self) -> None: ...
    def onSessionEnded(self, p0: int) -> None: ...

from typing import Any, ClassVar, overload
from core.internal.time.ITime import ITime
from session.internal.influence.InfluenceChannel import InfluenceChannel
from session.internal.influence.impl.InfluenceDataRepository import InfluenceDataRepository

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONArray:
    """Forward declaration for ``org.json.JSONArray``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONArray')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class NotificationTracker:
    def __init__(self, p0: InfluenceDataRepository, p1: ITime) -> None: ...
    def getLastChannelObjects(self) -> JSONArray: ...
    def getChannelLimit(self) -> int: ...
    def getIndirectAttributionWindow(self) -> int: ...
    def getLastChannelObjectsReceivedByNewId(self, p0: str) -> JSONArray: ...
    def saveChannelObjects(self, p0: JSONArray) -> None: ...
    def initInfluencedTypeFromCache(self) -> None: ...
    def getChannelType(self) -> InfluenceChannel: ...
    def getIdTag(self) -> str: ...
    def cacheState(self) -> None: ...

