from typing import Any, ClassVar, overload
from android.app.Activity import Activity
from android.content.Context import Context
from android.os.Bundle import Bundle
from core.internal.application.AppEntryAction import AppEntryAction
from core.internal.application.IActivityLifecycleHandler import IActivityLifecycleHandler
from core.internal.application.IApplicationLifecycleHandler import IApplicationLifecycleHandler

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Runnable:
    """Forward declaration for ``java.lang.Runnable``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.lang.Runnable')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/lang/Runnable.html
    """
    ...
class Continuation:
    """Forward declaration for ``kotlin.coroutines.Continuation``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.coroutines.Continuation')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/coroutines/Continuation/
    """
    ...

class ApplicationService:
    def __init__(self) -> None: ...
    def getAppContext(self) -> Context: ...
    def start(self, p0: Context) -> None: ...
    def setCurrent(self, p0: Activity) -> None: ...
    def onActivityCreated(self, p0: Activity, p1: Bundle) -> None: ...
    def onActivityStarted(self, p0: Activity) -> None: ...
    def onActivityResumed(self, p0: Activity) -> None: ...
    def onActivityPaused(self, p0: Activity) -> None: ...
    def onActivitySaveInstanceState(self, p0: Activity, p1: Bundle) -> None: ...
    def onActivityDestroyed(self, p0: Activity) -> None: ...
    def onGlobalLayout(self) -> None: ...
    def decorViewReady(self, p0: Activity, p1: Runnable) -> None: ...
    @staticmethod
    def access$onOrientationChanged(p0: "ApplicationService", p1: int, p2: Activity) -> None: ...
    def addActivityLifecycleHandler(self, p0: IActivityLifecycleHandler) -> None: ...
    def getCurrent(self) -> Activity: ...
    def isInForeground(self) -> bool: ...
    def getEntryState(self) -> AppEntryAction: ...
    def setEntryState(self, p0: AppEntryAction) -> None: ...
    def waitUntilSystemConditionsAvailable(self, p0: Continuation) -> Any: ...
    def waitUntilActivityReady(self, p0: Continuation) -> Any: ...
    def removeActivityLifecycleHandler(self, p0: IActivityLifecycleHandler) -> None: ...
    def addApplicationLifecycleHandler(self, p0: IApplicationLifecycleHandler) -> None: ...
    def removeApplicationLifecycleHandler(self, p0: IApplicationLifecycleHandler) -> None: ...
    def onActivityStopped(self, p0: Activity) -> None: ...

from typing import Any, ClassVar, overload

class ISystemConditionHandler:
    def systemConditionChanged(self) -> None: ...

