from typing import Any, ClassVar, overload

class ISessionLifecycleHandler:
    def onSessionStarted(self) -> None: ...
    def onSessionActive(self) -> None: ...
    def onSessionEnded(self, p0: int) -> None: ...

from typing import Any, ClassVar, overload

class ISessionService:
    def getStartTime(self) -> int: ...

from typing import Any, ClassVar, overload

class SessionModel:
    def __init__(self) -> None: ...
    def getStartTime(self) -> int: ...
    def getSessionId(self) -> str: ...
    def setSessionId(self, p0: str) -> None: ...
    def isValid(self) -> bool: ...
    def setValid(self, p0: bool) -> None: ...
    def setStartTime(self, p0: int) -> None: ...
    def getFocusTime(self) -> int: ...
    def setFocusTime(self, p0: int) -> None: ...
    def getActiveDuration(self) -> int: ...
    def setActiveDuration(self, p0: int) -> None: ...

from typing import Any, ClassVar, overload
from core.internal.preferences.IPreferencesService import IPreferencesService

class SessionModelStore:
    def __init__(self, p0: IPreferencesService) -> None: ...

