from typing import Any, ClassVar, overload

class IAnalyticsTracker:
    def trackReceivedEvent(self, p0: str, p1: str) -> None: ...
    def trackInfluenceOpenEvent(self) -> None: ...
    def trackOpenedEvent(self, p0: str, p1: str) -> None: ...

