from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.os.Bundle import Bundle

class INotificationBundleProcessor:
    def processBundleFromReceiver(self, p0: Context, p1: Bundle) -> Any: ...

    class ProcessedBundleResult:
        def __init__(self) -> None: ...
        def isProcessed(self) -> bool: ...
        def isWorkManagerProcessing(self) -> bool: ...
        def setWorkManagerProcessing(self, p0: bool) -> None: ...
        def setOneSignalPayload(self, p0: bool) -> None: ...
        def setDeniedByLifecycleCallback(self, p0: bool) -> None: ...

