from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class StringBuilder:
    """Forward declaration for ``java.lang.StringBuilder``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.lang.StringBuilder')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/lang/StringBuilder.html
    """
    ...

class INotificationQueryHelper:
    def recentUninteractedWithNotificationsWhere(self) -> StringBuilder: ...

from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Continuation:
    """Forward declaration for ``kotlin.coroutines.Continuation``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.coroutines.Continuation')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/coroutines/Continuation/
    """
    ...

class INotificationRepository:
    def createSummaryNotification(self, p0: int, p1: str, p2: Continuation) -> Any: ...
    def createNotification(self, p0: str, p1: str, p2: str, p3: bool, p4: bool, p5: int, p6: str, p7: str, p8: int, p9: str, p10: Continuation) -> Any: ...
    def getGroupId(self, p0: int, p1: Continuation) -> Any: ...
    def doesNotificationExist(self, p0: str, p1: Continuation) -> Any: ...
    def getAndroidIdForGroup(self, p0: str, p1: bool, p2: Continuation) -> Any: ...
    def getAndroidIdFromCollapseKey(self, p0: str, p1: Continuation) -> Any: ...
    def listNotificationsForGroup(self, p0: str, p1: Continuation) -> Any: ...
    def listNotificationsForOutstanding(self, p0: list, p1: Continuation) -> Any: ...
    def markAsConsumed(self, p0: int, p1: bool, p2: str, p3: bool, p4: Continuation) -> Any: ...
    def markAsDismissed(self, p0: int, p1: Continuation) -> Any: ...
    def markAsDismissedForGroup(self, p0: str, p1: Continuation) -> Any: ...
    def markAsDismissedForOutstanding(self, p0: Continuation) -> Any: ...
    def clearOldestOverLimitFallback(self, p0: int, p1: int, p2: Continuation) -> Any: ...
    def deleteExpiredNotifications(self, p0: Continuation) -> Any: ...

    class DefaultImpls:
        @staticmethod
        def markAsConsumed$default(p0: "INotificationRepository", p1: int, p2: bool, p3: str, p4: bool, p5: Continuation, p6: int, p7: Any) -> Any: ...
        @staticmethod
        def listNotificationsForOutstanding$default(p0: "INotificationRepository", p1: list, p2: Continuation, p3: int, p4: Any) -> Any: ...

    class NotificationData:
        def __init__(self, p0: int, p1: str, p2: str, p3: int, p4: str, p5: str) -> None: ...
        def getMessage(self) -> str: ...
        def getId(self) -> str: ...
        def getAndroidId(self) -> int: ...
        def getFullData(self) -> str: ...
        def getCreatedAt(self) -> int: ...
        def getTitle(self) -> str: ...

