from typing import Any, ClassVar, overload
from pyonesignal.core.internal.preferences.IPreferencesService import IPreferencesService

class LocationPreferencesService:
    def __init__(self, p0: IPreferencesService) -> None: ...
    def getLastLocationTime(self) -> int: ...
    def setLastLocationTime(self, p0: int) -> None: ...

