from typing import Any, ClassVar, overload
from common.modeling.Model import Model
from core.internal.operations.Operation import Operation
from core.internal.preferences.IPreferencesService import IPreferencesService

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONObject:
    """Forward declaration for ``org.json.JSONObject``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONObject')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class OperationModelStore:
    def __init__(self, p0: IPreferencesService) -> None: ...
    @overload
    def create(self, p0: JSONObject) -> Model: ...
    @overload
    def create(self, p0: JSONObject) -> Operation: ...
    def loadOperations(self) -> None: ...

from typing import Any, ClassVar, overload
from common.threading.WaiterWithValue import WaiterWithValue
from core.internal.config.ConfigModelStore import ConfigModelStore
from core.internal.config.impl.IdentityVerificationService import IdentityVerificationService
from core.internal.operations.Operation import Operation
from core.internal.operations.impl.OperationModelStore import OperationModelStore
from core.internal.time.ITime import ITime
from user.internal.jwt.JwtTokenStore import JwtTokenStore
from user.internal.operations.impl.states.NewRecordsState import NewRecordsState

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Continuation:
    """Forward declaration for ``kotlin.coroutines.Continuation``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.coroutines.Continuation')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/coroutines/Continuation/
    """
    ...
class KClass:
    """Forward declaration for ``kotlin.reflect.KClass``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.reflect.KClass')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/reflect/KClass/
    """
    ...
class DefaultConstructorMarker:
    """Forward declaration for ``kotlin.jvm.internal.DefaultConstructorMarker``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.internal.DefaultConstructorMarker')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/internal/DefaultConstructorMarker/
    """
    ...

class OperationRepo:
    def __init__(self, p0: list, p1: OperationModelStore, p2: ConfigModelStore, p3: ITime, p4: NewRecordsState, p5: JwtTokenStore, p6: IdentityVerificationService) -> None: ...
    def enqueue(self, p0: Operation, p1: bool) -> None: ...
    def start(self) -> None: ...
    def enqueueAndWait(self, p0: Operation, p1: bool, p2: Continuation) -> Any: ...
    def containsInstanceOf(self, p0: KClass) -> bool: ...
    def awaitInitialized(self, p0: Continuation) -> Any: ...
    def forceExecuteOperations(self) -> None: ...
    def getQueue$com_onesignal_core(self) -> list: ...
    def getNextOps$com_onesignal_core(self, p0: int) -> list: ...
    def executeOperations$com_onesignal_core(self, p0: list, p1: Continuation) -> Any: ...
    def removeOperationsWithoutExternalId$com_onesignal_core(self) -> None: ...
    def onJwtConfigHydrated$com_onesignal_core(self, p0: bool) -> None: ...
    def delayBeforeNextExecution(self, p0: int, p1: int, p2: Continuation) -> Any: ...
    def delayForPostCreate(self, p0: int, p1: Continuation) -> Any: ...
    def loadSavedOperations$com_onesignal_core(self) -> None: ...
    @staticmethod
    def access$processQueueForever(p0: "OperationRepo", p1: Continuation) -> Any: ...
    @staticmethod
    def access$getEnqueueIntoBucket$p(p0: "OperationRepo") -> int: ...
    @staticmethod
    def access$waitForNewOperationAndExecutionInterval(p0: "OperationRepo", p1: Continuation) -> Any: ...
    @staticmethod
    def access$getWaiter$p(p0: "OperationRepo") -> WaiterWithValue: ...
    @staticmethod
    def access$getRetryWaiter$p(p0: "OperationRepo") -> WaiterWithValue: ...

    class LoopWaiterMessage:
        @overload
        def __init__(self, p0: bool, p1: int) -> None: ...
        @overload
        def __init__(self, p0: bool, p1: int, p2: int, p3: DefaultConstructorMarker) -> None: ...
        def getPreviousWaitedTime(self) -> int: ...
        def getForce(self) -> bool: ...

    class OperationQueueItem:
        @overload
        def __init__(self, p0: Operation, p1: WaiterWithValue, p2: int, p3: int) -> None: ...
        @overload
        def __init__(self, p0: Operation, p1: WaiterWithValue, p2: int, p3: int, p4: int, p5: DefaultConstructorMarker) -> None: ...
        def toString(self) -> str: ...
        def getOperation(self) -> Operation: ...
        def getWaiter(self) -> WaiterWithValue: ...
        def setWaiter(self, p0: WaiterWithValue) -> None: ...
        def getRetries(self) -> int: ...
        def setRetries(self, p0: int) -> None: ...
        def getBucket(self) -> int: ...

    class WhenMappings:
        $EnumSwitchMapping$0: ClassVar[Any]

from typing import Any, ClassVar, overload
from core.internal.operations.Operation import Operation
from core.internal.operations.impl.OperationRepo import OperationRepo
from user.internal.jwt.JwtTokenStore import JwtTokenStore

class OperationRepoIvExtensionsKt:
    @staticmethod
    def handleFailUnauthorized(p0: OperationRepo, p1: Any, p2: list, p3: JwtTokenStore, p4: bool) -> bool: ...
    @staticmethod
    def hasValidJwtIfRequired(p0: OperationRepo, p1: JwtTokenStore, p2: Operation, p3: bool) -> bool: ...

