from typing import Any, ClassVar, overload
from common.modeling.IModelStore import IModelStore
from common.modeling.Model import Model
from common.modeling.ModelChangedArgs import ModelChangedArgs
from core.internal.operations.IOperationRepo import IOperationRepo
from core.internal.operations.Operation import Operation

class ModelStoreListener:
    def __init__(self, p0: IModelStore, p1: IOperationRepo) -> None: ...
    def close(self) -> None: ...
    def bootstrap(self) -> None: ...
    def onModelUpdated(self, p0: ModelChangedArgs, p1: str) -> None: ...
    def onModelAdded(self, p0: Model, p1: str) -> None: ...
    def onModelRemoved(self, p0: Model, p1: str) -> None: ...
    def getUpdateOperation(self, p0: Model, p1: str, p2: str, p3: Any, p4: Any) -> Operation: ...
    def getAddOperation(self, p0: Model) -> Operation: ...
    def getRemoveOperation(self, p0: Model) -> Operation: ...

from typing import Any, ClassVar, overload
from common.modeling.ISingletonModelStore import ISingletonModelStore
from common.modeling.Model import Model
from common.modeling.ModelChangedArgs import ModelChangedArgs
from core.internal.operations.IOperationRepo import IOperationRepo
from core.internal.operations.Operation import Operation

class SingletonModelStoreListener:
    def __init__(self, p0: ISingletonModelStore, p1: IOperationRepo) -> None: ...
    def close(self) -> None: ...
    def bootstrap(self) -> None: ...
    def onModelUpdated(self, p0: ModelChangedArgs, p1: str) -> None: ...
    def onModelReplaced(self, p0: Model, p1: str) -> None: ...
    def getUpdateOperation(self, p0: Model, p1: str, p2: str, p3: Any, p4: Any) -> Operation: ...
    def getReplaceOperation(self, p0: Model) -> Operation: ...

