from typing import Any, ClassVar, overload

class AppIdResolution:
    def __init__(self, p0: str, p1: bool, p2: bool) -> None: ...
    @staticmethod
    def copy$default(p0: "AppIdResolution", p1: str, p2: bool, p3: bool, p4: int, p5: Any) -> "AppIdResolution": ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def copy(self, p0: str, p1: bool, p2: bool) -> "AppIdResolution": ...
    def component1(self) -> str: ...
    def component2(self) -> bool: ...
    def getAppId(self) -> str: ...
    def component3(self) -> bool: ...
    def getFailed(self) -> bool: ...
    def getForceCreateUser(self) -> bool: ...

from typing import Any, ClassVar, overload
from core.internal.config.ConfigModel import ConfigModel
from core.internal.preferences.IPreferencesService import IPreferencesService
from user.internal.AppIdResolution import AppIdResolution

class AppIdResolutionKt:
    @staticmethod
    def resolveAppId(p0: str, p1: ConfigModel, p2: IPreferencesService) -> AppIdResolution: ...

from typing import Any, ClassVar, overload
from user.internal.subscriptions.SubscriptionModel import SubscriptionModel

class EmailSubscription:
    def __init__(self, p0: SubscriptionModel) -> None: ...
    def getEmail(self) -> str: ...

from typing import Any, ClassVar, overload
from core.internal.config.ConfigModel import ConfigModel
from core.internal.operations.IOperationRepo import IOperationRepo
from user.internal.UserSwitcher import UserSwitcher
from user.internal.identity.IdentityModelStore import IdentityModelStore
from user.internal.jwt.JwtTokenStore import JwtTokenStore

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Continuation:
    """Forward declaration for ``kotlin.coroutines.Continuation``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.coroutines.Continuation')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/coroutines/Continuation/
    """
    ...

class LoginHelper:
    def __init__(self, p0: IdentityModelStore, p1: UserSwitcher, p2: IOperationRepo, p3: ConfigModel, p4: JwtTokenStore, p5: Any) -> None: ...
    def switchUser$com_onesignal_core(self, p0: str, p1: str) -> Any: ...
    @staticmethod
    def switchUser$com_onesignal_core$default(p0: "LoginHelper", p1: str, p2: str, p3: int, p4: Any) -> Any: ...
    def enqueueLogin$com_onesignal_core(self, p0: Any, p1: Continuation) -> Any: ...

    class LoginEnqueueContext:
        def __init__(self, p0: str, p1: str, p2: str, p3: str) -> None: ...
        @staticmethod
        def copy$default(p0: Any, p1: str, p2: str, p3: str, p4: str, p5: int, p6: Any) -> Any: ...
        def equals(self, p0: Any) -> bool: ...
        def toString(self) -> str: ...
        def hashCode(self) -> int: ...
        def copy(self, p0: str, p1: str, p2: str, p3: str) -> Any: ...
        def getExternalId(self) -> str: ...
        def component1(self) -> str: ...
        def component2(self) -> str: ...
        def getAppId(self) -> str: ...
        def component3(self) -> str: ...
        def component4(self) -> str: ...
        def getNewIdentityOneSignalId(self) -> str: ...
        def getExistingOneSignalId(self) -> str: ...

from typing import Any, ClassVar, overload
from core.internal.config.ConfigModel import ConfigModel
from core.internal.config.impl.IdentityVerificationService import IdentityVerificationService
from core.internal.operations.IOperationRepo import IOperationRepo
from user.internal.UserSwitcher import UserSwitcher
from user.internal.identity.IdentityModelStore import IdentityModelStore
from user.internal.subscriptions.SubscriptionModelStore import SubscriptionModelStore

class LogoutHelper:
    def __init__(self, p0: IdentityModelStore, p1: UserSwitcher, p2: IOperationRepo, p3: ConfigModel, p4: SubscriptionModelStore, p5: IdentityVerificationService, p6: Any) -> None: ...
    def switchUser$com_onesignal_core(self) -> Any: ...
    def enqueueLogout$com_onesignal_core(self, p0: Any) -> None: ...

    class LogoutEnqueueContext:
        def __init__(self, p0: str, p1: str) -> None: ...
        @staticmethod
        def copy$default(p0: Any, p1: str, p2: str, p3: int, p4: Any) -> Any: ...
        def equals(self, p0: Any) -> bool: ...
        def toString(self) -> str: ...
        def hashCode(self) -> int: ...
        def copy(self, p0: str, p1: str) -> Any: ...
        def component1(self) -> str: ...
        def component2(self) -> str: ...
        def getAppId(self) -> str: ...
        def getNewOnesignalId(self) -> str: ...

from typing import Any, ClassVar, overload
from core.internal.config.ConfigModel import ConfigModel
from user.internal.UserSwitcher import UserSwitcher
from user.internal.subscriptions.SubscriptionModelStore import SubscriptionModelStore

class LogoutHelperIvExtensionsKt:
    @staticmethod
    def switchUserIv(p0: UserSwitcher, p1: SubscriptionModelStore, p2: ConfigModel, p3: bool) -> bool: ...

from typing import Any, ClassVar, overload
from common.events.EventProducer import EventProducer
from user.internal.subscriptions.SubscriptionModel import SubscriptionModel
from user.subscriptions.IPushSubscriptionObserver import IPushSubscriptionObserver
from user.subscriptions.PushSubscriptionState import PushSubscriptionState

class PushSubscription:
    def __init__(self, p0: SubscriptionModel) -> None: ...
    def optOut(self) -> None: ...
    def addObserver(self, p0: IPushSubscriptionObserver) -> None: ...
    def removeObserver(self, p0: IPushSubscriptionObserver) -> None: ...
    def optIn(self) -> None: ...
    def getToken(self) -> str: ...
    def getOptedIn(self) -> bool: ...
    def getChangeHandlersNotifier(self) -> EventProducer: ...
    def getSavedState(self) -> PushSubscriptionState: ...
    def refreshState(self) -> PushSubscriptionState: ...

from typing import Any, ClassVar, overload
from user.internal.subscriptions.SubscriptionModel import SubscriptionModel

class SmsSubscription:
    def __init__(self, p0: SubscriptionModel) -> None: ...
    def getNumber(self) -> str: ...

from typing import Any, ClassVar, overload
from user.internal.subscriptions.SubscriptionModel import SubscriptionModel

class Subscription:
    def __init__(self, p0: SubscriptionModel) -> None: ...
    def getId(self) -> str: ...
    def getModel(self) -> SubscriptionModel: ...

from typing import Any, ClassVar, overload
from user.internal.subscriptions.SubscriptionModel import SubscriptionModel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class DefaultConstructorMarker:
    """Forward declaration for ``kotlin.jvm.internal.DefaultConstructorMarker``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.internal.DefaultConstructorMarker')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/internal/DefaultConstructorMarker/
    """
    ...

class UninitializedPushSubscription:
    Companion: ClassVar[Any]
    def __init__(self) -> None: ...

    class Companion:
        def __init__(self, p0: DefaultConstructorMarker) -> None: ...
        def createFakePushSub(self) -> SubscriptionModel: ...

from typing import Any, ClassVar, overload
from common.events.EventProducer import EventProducer
from common.modeling.Model import Model
from common.modeling.ModelChangedArgs import ModelChangedArgs
from core.internal.language.ILanguageContext import ILanguageContext
from user.internal.customEvents.ICustomEventController import ICustomEventController
from user.internal.identity.IdentityModel import IdentityModel
from user.internal.identity.IdentityModelStore import IdentityModelStore
from user.internal.properties.PropertiesModelStore import PropertiesModelStore
from user.internal.subscriptions.ISubscriptionManager import ISubscriptionManager
from user.internal.subscriptions.SubscriptionList import SubscriptionList
from user.state.IUserStateObserver import IUserStateObserver
from user.subscriptions.IPushSubscription import IPushSubscription

class UserManager:
    def __init__(self, p0: ISubscriptionManager, p1: IdentityModelStore, p2: PropertiesModelStore, p3: ICustomEventController, p4: ILanguageContext) -> None: ...
    def getPushSubscription(self) -> IPushSubscription: ...
    def getOnesignalId(self) -> str: ...
    def getExternalId(self) -> str: ...
    def setLanguage(self, p0: str) -> None: ...
    def addAlias(self, p0: str, p1: str) -> None: ...
    def addAliases(self, p0: dict) -> None: ...
    def removeAlias(self, p0: str) -> None: ...
    def removeAliases(self, p0: list) -> None: ...
    def addEmail(self, p0: str) -> None: ...
    def removeEmail(self, p0: str) -> None: ...
    def addSms(self, p0: str) -> None: ...
    def removeSms(self, p0: str) -> None: ...
    def addTag(self, p0: str, p1: str) -> None: ...
    def addTags(self, p0: dict) -> None: ...
    def removeTag(self, p0: str) -> None: ...
    def removeTags(self, p0: list) -> None: ...
    def getTags(self) -> dict: ...
    def addObserver(self, p0: IUserStateObserver) -> None: ...
    def removeObserver(self, p0: IUserStateObserver) -> None: ...
    def trackEvent(self, p0: str, p1: dict) -> None: ...
    def onModelUpdated(self, p0: ModelChangedArgs, p1: str) -> None: ...
    @overload
    def onModelReplaced(self, p0: IdentityModel, p1: str) -> None: ...
    @overload
    def onModelReplaced(self, p0: Model, p1: str) -> None: ...
    def getAliases(self) -> dict: ...
    def getSubscriptions(self) -> SubscriptionList: ...
    def getChangeHandlersNotifier(self) -> EventProducer: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from common.AndroidUtils import AndroidUtils
from common.IDManager import IDManager
from common.OneSignalUtils import OneSignalUtils
from common.services.ServiceProvider import ServiceProvider
from core.internal.config.ConfigModel import ConfigModel
from core.internal.operations.IOperationRepo import IOperationRepo
from core.internal.preferences.IPreferencesService import IPreferencesService
from user.internal.identity.IdentityModelStore import IdentityModelStore
from user.internal.properties.PropertiesModelStore import PropertiesModelStore
from user.internal.subscriptions.SubscriptionModelStore import SubscriptionModelStore

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Function0:
    """Forward declaration for ``kotlin.jvm.functions.Function0``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.functions.Function0')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/functions/Function0/
    """
    ...
class DefaultConstructorMarker:
    """Forward declaration for ``kotlin.jvm.internal.DefaultConstructorMarker``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.internal.DefaultConstructorMarker')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/internal/DefaultConstructorMarker/
    """
    ...
class Function2:
    """Forward declaration for ``kotlin.jvm.functions.Function2``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.functions.Function2')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/functions/Function2/
    """
    ...
class JSONObject:
    """Forward declaration for ``org.json.JSONObject``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONObject')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class UserSwitcher:
    @overload
    def __init__(self, p0: IPreferencesService, p1: IOperationRepo, p2: ServiceProvider, p3: IDManager, p4: IdentityModelStore, p5: PropertiesModelStore, p6: SubscriptionModelStore, p7: ConfigModel, p8: OneSignalUtils, p9: str, p10: str, p11: AndroidUtils, p12: Function0) -> None: ...
    @overload
    def __init__(self, p0: IPreferencesService, p1: IOperationRepo, p2: ServiceProvider, p3: IDManager, p4: IdentityModelStore, p5: PropertiesModelStore, p6: SubscriptionModelStore, p7: ConfigModel, p8: OneSignalUtils, p9: str, p10: str, p11: AndroidUtils, p12: Function0, p13: int, p14: DefaultConstructorMarker) -> None: ...
    def initUser(self, p0: bool) -> None: ...
    def createAndSwitchToNewUser(self, p0: bool, p1: Function2) -> None: ...
    @staticmethod
    def createAndSwitchToNewUser$default(p0: "UserSwitcher", p1: bool, p2: Function2, p3: int, p4: Any) -> None: ...
    def createPushSubscriptionFromLegacySync(self, p0: str, p1: JSONObject, p2: ConfigModel, p3: SubscriptionModelStore, p4: Context) -> bool: ...

