from typing import Any, ClassVar, overload
from core.internal.config.ConfigModelStore import ConfigModelStore
from core.internal.time.ITime import ITime

class NewRecordsState:
    def __init__(self, p0: ITime, p1: ConfigModelStore) -> None: ...
    def add(self, p0: str) -> None: ...
    def canAccess(self, p0: str) -> bool: ...
    def isInMissingRetryWindow(self, p0: str) -> bool: ...

