from typing import Any, ClassVar, overload

class AndroidOtelLogger:
    def __init__(self) -> None: ...
    def error(self, p0: str) -> None: ...
    def info(self, p0: str) -> None: ...
    def debug(self, p0: str) -> None: ...
    def warn(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from debug.LogLevel import LogLevel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class DefaultConstructorMarker:
    """Forward declaration for ``kotlin.jvm.internal.DefaultConstructorMarker``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.internal.DefaultConstructorMarker')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/internal/DefaultConstructorMarker/
    """
    ...

class OtelIdResolver:
    Companion: ClassVar[Any]
    def __init__(self, p0: Context) -> None: ...
    def resolveAppId(self) -> str: ...
    def resolveOnesignalId(self) -> str: ...
    def resolvePushSubscriptionId(self) -> str: ...
    def resolveRemoteLoggingEnabled(self) -> bool: ...
    def resolveRemoteLogLevel(self) -> LogLevel: ...
    def resolveInstallId(self) -> str: ...

    class Companion:
        def __init__(self, p0: DefaultConstructorMarker) -> None: ...

from typing import Any, ClassVar, overload
from debug.internal.logging.otel.android.OtelIdResolver import OtelIdResolver
from debug.internal.logging.otel.android.OtelPlatformProviderConfig import OtelPlatformProviderConfig

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Function0:
    """Forward declaration for ``kotlin.jvm.functions.Function0``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.functions.Function0')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/functions/Function0/
    """
    ...
class Continuation:
    """Forward declaration for ``kotlin.coroutines.Continuation``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.coroutines.Continuation')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/coroutines/Continuation/
    """
    ...

class OtelPlatformProvider:
    def __init__(self, p0: OtelPlatformProviderConfig, p1: Function0) -> None: ...
    def getOnesignalId(self) -> str: ...
    def getAppVersion(self) -> str: ...
    def getAppId(self) -> str: ...
    def getPushSubscriptionId(self) -> str: ...
    def getMinFileAgeForReadMillis(self) -> int: ...
    def getCrashStoragePath(self) -> str: ...
    def getRemoteLogLevel(self) -> str: ...
    def isOtelExporterLoggingEnabled(self) -> bool: ...
    def getAppPackageId(self) -> str: ...
    def getDeviceManufacturer(self) -> str: ...
    def getSdkBase(self) -> str: ...
    def getSdkBaseVersion(self) -> str: ...
    def getInstallId(self, p0: Continuation) -> Any: ...
    def getDeviceModel(self) -> str: ...
    def getOsName(self) -> str: ...
    def getOsVersion(self) -> str: ...
    def getOsBuildId(self) -> str: ...
    def getSdkWrapper(self) -> str: ...
    def getSdkWrapperVersion(self) -> str: ...
    def getEnabledFeatureFlags(self) -> list: ...
    def getAppState(self) -> str: ...
    def getProcessUptime(self) -> int: ...
    def getCurrentThreadName(self) -> str: ...
    def isRemoteLoggingEnabled(self) -> bool: ...
    def getAppIdForHeaders(self) -> str: ...
    def getApiBaseUrl(self) -> str: ...
    @staticmethod
    def getEnabledFeatureFlags$annotations() -> None: ...
    @staticmethod
    def getRemoteLogLevel$annotations() -> None: ...
    @staticmethod
    def access$getIdResolver$p(p0: "OtelPlatformProvider") -> OtelIdResolver: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Function0:
    """Forward declaration for ``kotlin.jvm.functions.Function0``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.functions.Function0')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/functions/Function0/
    """
    ...
class DefaultConstructorMarker:
    """Forward declaration for ``kotlin.jvm.internal.DefaultConstructorMarker``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.internal.DefaultConstructorMarker')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/internal/DefaultConstructorMarker/
    """
    ...

class OtelPlatformProviderConfig:
    @overload
    def __init__(self, p0: str, p1: str, p2: str, p3: Context, p4: Function0) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str, p2: str, p3: Context, p4: Function0, p5: int, p6: DefaultConstructorMarker) -> None: ...
    def getAppVersion(self) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getContext(self) -> Context: ...
    def copy(self, p0: str, p1: str, p2: str, p3: Context, p4: Function0) -> "OtelPlatformProviderConfig": ...
    def getGetIsInForeground(self) -> Function0: ...
    def component1(self) -> str: ...
    def component2(self) -> str: ...
    @staticmethod
    def copy$default(p0: "OtelPlatformProviderConfig", p1: str, p2: str, p3: str, p4: Context, p5: Function0, p6: int, p7: Any) -> "OtelPlatformProviderConfig": ...
    def getCrashStoragePath(self) -> str: ...
    def getAppPackageId(self) -> str: ...
    def component3(self) -> str: ...
    def component4(self) -> Context: ...
    def component5(self) -> Function0: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from debug.internal.logging.otel.android.OtelPlatformProvider import OtelPlatformProvider

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Function0:
    """Forward declaration for ``kotlin.jvm.functions.Function0``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.functions.Function0')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/functions/Function0/
    """
    ...

class OtelPlatformProviderKt:
    OTEL_EXPORTER_LOGGING_ENABLED: ClassVar[bool]
    @staticmethod
    def createAndroidOtelPlatformProvider(p0: Context, p1: Function0) -> OtelPlatformProvider: ...

