from typing import Any, ClassVar, overload
from core.internal.application.IApplicationService import IApplicationService

class RequestPermissionService:
    def __init__(self, p0: IApplicationService) -> None: ...
    def startPrompt(self, p0: bool, p1: str, p2: str, p3: type) -> None: ...
    def registerAsCallback(self, p0: str, p1: Any) -> None: ...
    def setFallbackToSettings(self, p0: bool) -> None: ...
    @staticmethod
    def access$get_application$p(p0: "RequestPermissionService") -> IApplicationService: ...
    def setWaiting(self, p0: bool) -> None: ...
    def getWaiting(self) -> bool: ...
    def setShouldShowRequestPermissionRationaleBeforeRequest(self, p0: bool) -> None: ...
    def getCallback(self, p0: str) -> Any: ...
    def getFallbackToSettings(self) -> bool: ...
    def getShouldShowRequestPermissionRationaleBeforeRequest(self) -> bool: ...

