from typing import Any, ClassVar, overload

class IdentityModel:
    def __init__(self) -> None: ...
    def setOnesignalId(self, p0: str) -> None: ...
    def getOnesignalId(self) -> str: ...
    def getExternalId(self) -> str: ...
    def setExternalId(self, p0: str) -> None: ...
    @overload
    def remove(self, p0: Any) -> str: ...
    @overload
    def remove(self, p0: str) -> str: ...
    @overload
    def get(self, p0: Any) -> str: ...
    @overload
    def get(self, p0: str) -> str: ...
    @overload
    def containsValue(self, p0: Any) -> bool: ...
    @overload
    def containsValue(self, p0: str) -> bool: ...
    @overload
    def getOrDefault(self, p0: Any, p1: str) -> str: ...
    @overload
    def getOrDefault(self, p0: str, p1: str) -> str: ...

from typing import Any, ClassVar, overload
from core.internal.preferences.IPreferencesService import IPreferencesService

class IdentityModelStore:
    def __init__(self, p0: IPreferencesService) -> None: ...

from typing import Any, ClassVar, overload
from user.internal.identity.IdentityModelStore import IdentityModelStore

class IdentityModelStoreKt:
    IDENTITY_NAME_SPACE: ClassVar[str]
    @staticmethod
    def hasOneSignalId(p0: IdentityModelStore) -> bool: ...

