from typing import Any, ClassVar, overload

class IMigrationRecovery:
    def isInBadState(self) -> bool: ...
    def recoveryMessage(self) -> str: ...
    def recover(self) -> None: ...

from typing import Any, ClassVar, overload

class MigrationRecovery:
    def __init__(self) -> None: ...
    def start(self) -> None: ...

from typing import Any, ClassVar, overload
from core.internal.config.ConfigModelStore import ConfigModelStore
from user.internal.subscriptions.SubscriptionModel import SubscriptionModel
from user.internal.subscriptions.SubscriptionModelStore import SubscriptionModelStore

class RecoverConfigPushSubscription:
    def __init__(self, p0: ConfigModelStore, p1: SubscriptionModelStore) -> None: ...
    def isInBadState(self) -> bool: ...
    def recoveryMessage(self) -> str: ...
    def recover(self) -> None: ...
    def getActivePushSubscription(self) -> SubscriptionModel: ...
    @staticmethod
    def access$get_subscriptionModelStore$p(p0: "RecoverConfigPushSubscription") -> SubscriptionModelStore: ...

from typing import Any, ClassVar, overload
from core.internal.config.ConfigModelStore import ConfigModelStore
from core.internal.operations.IOperationRepo import IOperationRepo
from user.internal.identity.IdentityModelStore import IdentityModelStore

class RecoverFromDroppedLoginBug:
    def __init__(self, p0: IOperationRepo, p1: IdentityModelStore, p2: ConfigModelStore) -> None: ...
    def start(self) -> None: ...
    @staticmethod
    def access$get_operationRepo$p(p0: "RecoverFromDroppedLoginBug") -> IOperationRepo: ...
    @staticmethod
    def access$isInBadState(p0: "RecoverFromDroppedLoginBug") -> bool: ...
    @staticmethod
    def access$get_identityModelStore$p(p0: "RecoverFromDroppedLoginBug") -> IdentityModelStore: ...
    @staticmethod
    def access$recoverByAddingBackDroppedLoginOperation(p0: "RecoverFromDroppedLoginBug") -> None: ...

