from typing import Any, ClassVar, overload
from core.internal.operations.GroupComparisonType import GroupComparisonType
from user.internal.subscriptions.SubscriptionStatus import SubscriptionStatus
from user.internal.subscriptions.SubscriptionType import SubscriptionType

class CreateSubscriptionOperation:
    @overload
    def __init__(self, p0: str, p1: str, p2: str, p3: str, p4: SubscriptionType, p5: bool, p6: str, p7: SubscriptionStatus) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getOnesignalId(self) -> str: ...
    def getAddress(self) -> str: ...
    def getType(self) -> SubscriptionType: ...
    def getStatus(self) -> SubscriptionStatus: ...
    def getAppId(self) -> str: ...
    def getApplyToRecordId(self) -> str: ...
    def getCreateComparisonKey(self) -> str: ...
    def getModifyComparisonKey(self) -> str: ...
    def getGroupComparisonType(self) -> GroupComparisonType: ...
    def getCanStartExecute(self) -> bool: ...
    def translateIds(self, p0: dict) -> None: ...
    def getSubscriptionId(self) -> str: ...
    def getEnabled(self) -> bool: ...

from typing import Any, ClassVar, overload
from core.internal.operations.GroupComparisonType import GroupComparisonType

class DeleteAliasOperation:
    @overload
    def __init__(self, p0: str, p1: str, p2: str, p3: str) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getOnesignalId(self) -> str: ...
    def getAppId(self) -> str: ...
    def getApplyToRecordId(self) -> str: ...
    def getCreateComparisonKey(self) -> str: ...
    def getModifyComparisonKey(self) -> str: ...
    def getGroupComparisonType(self) -> GroupComparisonType: ...
    def getCanStartExecute(self) -> bool: ...
    def translateIds(self, p0: dict) -> None: ...
    def getLabel(self) -> str: ...

from typing import Any, ClassVar, overload
from core.internal.operations.GroupComparisonType import GroupComparisonType

class DeleteSubscriptionOperation:
    @overload
    def __init__(self, p0: str, p1: str, p2: str, p3: str) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getOnesignalId(self) -> str: ...
    def getAppId(self) -> str: ...
    def getApplyToRecordId(self) -> str: ...
    def getCreateComparisonKey(self) -> str: ...
    def getModifyComparisonKey(self) -> str: ...
    def getGroupComparisonType(self) -> GroupComparisonType: ...
    def getCanStartExecute(self) -> bool: ...
    def translateIds(self, p0: dict) -> None: ...
    def getSubscriptionId(self) -> str: ...

from typing import Any, ClassVar, overload
from core.internal.operations.GroupComparisonType import GroupComparisonType

class DeleteTagOperation:
    @overload
    def __init__(self, p0: str, p1: str, p2: str, p3: str) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getOnesignalId(self) -> str: ...
    def getKey(self) -> str: ...
    def getAppId(self) -> str: ...
    def getApplyToRecordId(self) -> str: ...
    def getCreateComparisonKey(self) -> str: ...
    def getModifyComparisonKey(self) -> str: ...
    def getGroupComparisonType(self) -> GroupComparisonType: ...
    def getCanStartExecute(self) -> bool: ...
    def translateIds(self, p0: dict) -> None: ...

from typing import Any, ClassVar, overload
from core.internal.operations.GroupComparisonType import GroupComparisonType

class LoginUserFromSubscriptionOperation:
    @overload
    def __init__(self, p0: str, p1: str, p2: str, p3: str) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getOnesignalId(self) -> str: ...
    def getAppId(self) -> str: ...
    def getApplyToRecordId(self) -> str: ...
    def getCreateComparisonKey(self) -> str: ...
    def getModifyComparisonKey(self) -> str: ...
    def getGroupComparisonType(self) -> GroupComparisonType: ...
    def getCanStartExecute(self) -> bool: ...
    def getSubscriptionId(self) -> str: ...

from typing import Any, ClassVar, overload
from core.internal.operations.GroupComparisonType import GroupComparisonType

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class DefaultConstructorMarker:
    """Forward declaration for ``kotlin.jvm.internal.DefaultConstructorMarker``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('kotlin.jvm.internal.DefaultConstructorMarker')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/jvm/internal/DefaultConstructorMarker/
    """
    ...

class LoginUserOperation:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str, p2: str, p3: str, p4: int, p5: DefaultConstructorMarker) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str, p2: str, p3: str) -> None: ...
    def getOnesignalId(self) -> str: ...
    def getAppId(self) -> str: ...
    def getApplyToRecordId(self) -> str: ...
    def getCreateComparisonKey(self) -> str: ...
    def getModifyComparisonKey(self) -> str: ...
    def getGroupComparisonType(self) -> GroupComparisonType: ...
    def getCanStartExecute(self) -> bool: ...
    def translateIds(self, p0: dict) -> None: ...
    def getExistingOnesignalId(self) -> str: ...
    def setExistingOnesignalId$com_onesignal_core(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class BigDecimal:
    """Forward declaration for ``java.math.BigDecimal``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.math.BigDecimal')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html
    """
    ...

class PurchaseInfo:
    @overload
    def __init__(self, p0: str, p1: str, p2: BigDecimal) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getSku(self) -> str: ...
    def getIso(self) -> str: ...
    def getAmount(self) -> BigDecimal: ...

from typing import Any, ClassVar, overload
from core.internal.operations.GroupComparisonType import GroupComparisonType

class RefreshUserOperation:
    @overload
    def __init__(self, p0: str, p1: str, p2: str) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getOnesignalId(self) -> str: ...
    def getAppId(self) -> str: ...
    def getApplyToRecordId(self) -> str: ...
    def getCreateComparisonKey(self) -> str: ...
    def getModifyComparisonKey(self) -> str: ...
    def getGroupComparisonType(self) -> GroupComparisonType: ...
    def getCanStartExecute(self) -> bool: ...
    def translateIds(self, p0: dict) -> None: ...

from typing import Any, ClassVar, overload
from core.internal.operations.GroupComparisonType import GroupComparisonType

class SetAliasOperation:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str, p2: str, p3: str, p4: str) -> None: ...
    def getOnesignalId(self) -> str: ...
    def getValue(self) -> str: ...
    def getAppId(self) -> str: ...
    def getApplyToRecordId(self) -> str: ...
    def getCreateComparisonKey(self) -> str: ...
    def getModifyComparisonKey(self) -> str: ...
    def getGroupComparisonType(self) -> GroupComparisonType: ...
    def getCanStartExecute(self) -> bool: ...
    def translateIds(self, p0: dict) -> None: ...
    def getLabel(self) -> str: ...

from typing import Any, ClassVar, overload
from core.internal.operations.GroupComparisonType import GroupComparisonType

class SetPropertyOperation:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str, p2: str, p3: str, p4: Any) -> None: ...
    def getOnesignalId(self) -> str: ...
    def getProperty(self) -> str: ...
    def getValue(self) -> Any: ...
    def getAppId(self) -> str: ...
    def getApplyToRecordId(self) -> str: ...
    def getCreateComparisonKey(self) -> str: ...
    def getModifyComparisonKey(self) -> str: ...
    def getGroupComparisonType(self) -> GroupComparisonType: ...
    def getCanStartExecute(self) -> bool: ...
    def translateIds(self, p0: dict) -> None: ...

from typing import Any, ClassVar, overload
from core.internal.operations.GroupComparisonType import GroupComparisonType

class SetTagOperation:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str, p2: str, p3: str, p4: str) -> None: ...
    def getOnesignalId(self) -> str: ...
    def getValue(self) -> str: ...
    def getKey(self) -> str: ...
    def getAppId(self) -> str: ...
    def getApplyToRecordId(self) -> str: ...
    def getCreateComparisonKey(self) -> str: ...
    def getModifyComparisonKey(self) -> str: ...
    def getGroupComparisonType(self) -> GroupComparisonType: ...
    def getCanStartExecute(self) -> bool: ...
    def translateIds(self, p0: dict) -> None: ...

from typing import Any, ClassVar, overload
from core.internal.operations.GroupComparisonType import GroupComparisonType

class TrackCustomEventOperation:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str, p2: str, p3: int, p4: str, p5: str) -> None: ...
    def getOnesignalId(self) -> str: ...
    def getAppId(self) -> str: ...
    def setEventProperties(self, p0: str) -> None: ...
    def getEventProperties(self) -> str: ...
    def getTimeStamp(self) -> int: ...
    def setEventName(self, p0: str) -> None: ...
    def getEventName(self) -> str: ...
    def getApplyToRecordId(self) -> str: ...
    def getCreateComparisonKey(self) -> str: ...
    def getModifyComparisonKey(self) -> str: ...
    def getGroupComparisonType(self) -> GroupComparisonType: ...
    def getCanStartExecute(self) -> bool: ...
    def translateIds(self, p0: dict) -> None: ...

from typing import Any, ClassVar, overload
from core.internal.operations.GroupComparisonType import GroupComparisonType

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class BigDecimal:
    """Forward declaration for ``java.math.BigDecimal``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by jni-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.math.BigDecimal')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html
    """
    ...

class TrackPurchaseOperation:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str, p2: str, p3: bool, p4: BigDecimal, p5: list) -> None: ...
    def getOnesignalId(self) -> str: ...
    def getAppId(self) -> str: ...
    def getTreatNewAsExisting(self) -> bool: ...
    def getApplyToRecordId(self) -> str: ...
    def getCreateComparisonKey(self) -> str: ...
    def getModifyComparisonKey(self) -> str: ...
    def getGroupComparisonType(self) -> GroupComparisonType: ...
    def getCanStartExecute(self) -> bool: ...
    def translateIds(self, p0: dict) -> None: ...
    def getAmountSpent(self) -> BigDecimal: ...
    def getPurchases(self) -> list: ...

from typing import Any, ClassVar, overload
from core.internal.operations.GroupComparisonType import GroupComparisonType

class TrackSessionEndOperation:
    @overload
    def __init__(self, p0: str, p1: str, p2: str, p3: int) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getOnesignalId(self) -> str: ...
    def getAppId(self) -> str: ...
    def getSessionTime(self) -> int: ...
    def getApplyToRecordId(self) -> str: ...
    def getCreateComparisonKey(self) -> str: ...
    def getModifyComparisonKey(self) -> str: ...
    def getGroupComparisonType(self) -> GroupComparisonType: ...
    def getCanStartExecute(self) -> bool: ...
    def translateIds(self, p0: dict) -> None: ...

from typing import Any, ClassVar, overload
from core.internal.operations.GroupComparisonType import GroupComparisonType

class TrackSessionStartOperation:
    @overload
    def __init__(self, p0: str, p1: str, p2: str) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getOnesignalId(self) -> str: ...
    def getAppId(self) -> str: ...
    def getApplyToRecordId(self) -> str: ...
    def getCreateComparisonKey(self) -> str: ...
    def getModifyComparisonKey(self) -> str: ...
    def getGroupComparisonType(self) -> GroupComparisonType: ...
    def getCanStartExecute(self) -> bool: ...
    def translateIds(self, p0: dict) -> None: ...

from typing import Any, ClassVar, overload
from core.internal.operations.GroupComparisonType import GroupComparisonType

class TransferSubscriptionOperation:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str, p2: str, p3: str) -> None: ...
    def getOnesignalId(self) -> str: ...
    def getAppId(self) -> str: ...
    def getApplyToRecordId(self) -> str: ...
    def getCreateComparisonKey(self) -> str: ...
    def getModifyComparisonKey(self) -> str: ...
    def getGroupComparisonType(self) -> GroupComparisonType: ...
    def getCanStartExecute(self) -> bool: ...
    def translateIds(self, p0: dict) -> None: ...
    def getSubscriptionId(self) -> str: ...

from typing import Any, ClassVar, overload
from core.internal.operations.GroupComparisonType import GroupComparisonType
from user.internal.subscriptions.SubscriptionStatus import SubscriptionStatus
from user.internal.subscriptions.SubscriptionType import SubscriptionType

class UpdateSubscriptionOperation:
    @overload
    def __init__(self, p0: str, p1: str, p2: str, p3: str, p4: SubscriptionType, p5: bool, p6: str, p7: SubscriptionStatus) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getOnesignalId(self) -> str: ...
    def getAddress(self) -> str: ...
    def getType(self) -> SubscriptionType: ...
    def getStatus(self) -> SubscriptionStatus: ...
    def getAppId(self) -> str: ...
    def getApplyToRecordId(self) -> str: ...
    def getCreateComparisonKey(self) -> str: ...
    def getModifyComparisonKey(self) -> str: ...
    def getGroupComparisonType(self) -> GroupComparisonType: ...
    def getCanStartExecute(self) -> bool: ...
    def translateIds(self, p0: dict) -> None: ...
    def getSubscriptionId(self) -> str: ...
    def getEnabled(self) -> bool: ...

