from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

class CreateSubscriptionOperation(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/operations/CreateSubscriptionOperation"
    __javaconstructor__ = [("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/onesignal/user/internal/subscriptions/SubscriptionType;ZLjava/lang/String;Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;)V", False), ("()V", False)]
    getOnesignalId = JavaMethod("()Ljava/lang/String;")
    getAddress = JavaMethod("()Ljava/lang/String;")
    getType = JavaMethod("()Lcom/onesignal/user/internal/subscriptions/SubscriptionType;")
    getStatus = JavaMethod("()Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    getAppId = JavaMethod("()Ljava/lang/String;")
    getApplyToRecordId = JavaMethod("()Ljava/lang/String;")
    getCreateComparisonKey = JavaMethod("()Ljava/lang/String;")
    getModifyComparisonKey = JavaMethod("()Ljava/lang/String;")
    getGroupComparisonType = JavaMethod("()Lcom/onesignal/core/internal/operations/GroupComparisonType;")
    getCanStartExecute = JavaMethod("()Z")
    translateIds = JavaMethod("(Ljava/util/Map;)V")
    getSubscriptionId = JavaMethod("()Ljava/lang/String;")
    getEnabled = JavaMethod("()Z")

class DeleteAliasOperation(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/operations/DeleteAliasOperation"
    __javaconstructor__ = [("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V", False), ("()V", False)]
    getOnesignalId = JavaMethod("()Ljava/lang/String;")
    getAppId = JavaMethod("()Ljava/lang/String;")
    getApplyToRecordId = JavaMethod("()Ljava/lang/String;")
    getCreateComparisonKey = JavaMethod("()Ljava/lang/String;")
    getModifyComparisonKey = JavaMethod("()Ljava/lang/String;")
    getGroupComparisonType = JavaMethod("()Lcom/onesignal/core/internal/operations/GroupComparisonType;")
    getCanStartExecute = JavaMethod("()Z")
    translateIds = JavaMethod("(Ljava/util/Map;)V")
    getLabel = JavaMethod("()Ljava/lang/String;")

class DeleteSubscriptionOperation(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/operations/DeleteSubscriptionOperation"
    __javaconstructor__ = [("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V", False), ("()V", False)]
    getOnesignalId = JavaMethod("()Ljava/lang/String;")
    getAppId = JavaMethod("()Ljava/lang/String;")
    getApplyToRecordId = JavaMethod("()Ljava/lang/String;")
    getCreateComparisonKey = JavaMethod("()Ljava/lang/String;")
    getModifyComparisonKey = JavaMethod("()Ljava/lang/String;")
    getGroupComparisonType = JavaMethod("()Lcom/onesignal/core/internal/operations/GroupComparisonType;")
    getCanStartExecute = JavaMethod("()Z")
    translateIds = JavaMethod("(Ljava/util/Map;)V")
    getSubscriptionId = JavaMethod("()Ljava/lang/String;")

class DeleteTagOperation(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/operations/DeleteTagOperation"
    __javaconstructor__ = [("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V", False), ("()V", False)]
    getOnesignalId = JavaMethod("()Ljava/lang/String;")
    getKey = JavaMethod("()Ljava/lang/String;")
    getAppId = JavaMethod("()Ljava/lang/String;")
    getApplyToRecordId = JavaMethod("()Ljava/lang/String;")
    getCreateComparisonKey = JavaMethod("()Ljava/lang/String;")
    getModifyComparisonKey = JavaMethod("()Ljava/lang/String;")
    getGroupComparisonType = JavaMethod("()Lcom/onesignal/core/internal/operations/GroupComparisonType;")
    getCanStartExecute = JavaMethod("()Z")
    translateIds = JavaMethod("(Ljava/util/Map;)V")

class LoginUserFromSubscriptionOperation(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/operations/LoginUserFromSubscriptionOperation"
    __javaconstructor__ = [("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V", False), ("()V", False)]
    getOnesignalId = JavaMethod("()Ljava/lang/String;")
    getAppId = JavaMethod("()Ljava/lang/String;")
    getApplyToRecordId = JavaMethod("()Ljava/lang/String;")
    getCreateComparisonKey = JavaMethod("()Ljava/lang/String;")
    getModifyComparisonKey = JavaMethod("()Ljava/lang/String;")
    getGroupComparisonType = JavaMethod("()Lcom/onesignal/core/internal/operations/GroupComparisonType;")
    getCanStartExecute = JavaMethod("()Z")
    getSubscriptionId = JavaMethod("()Ljava/lang/String;")

class LoginUserOperation(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/operations/LoginUserOperation"
    __javaconstructor__ = [("()V", False), ("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILkotlin/jvm/internal/DefaultConstructorMarker;)V", False), ("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V", False)]
    getOnesignalId = JavaMethod("()Ljava/lang/String;")
    getAppId = JavaMethod("()Ljava/lang/String;")
    getApplyToRecordId = JavaMethod("()Ljava/lang/String;")
    getCreateComparisonKey = JavaMethod("()Ljava/lang/String;")
    getModifyComparisonKey = JavaMethod("()Ljava/lang/String;")
    getGroupComparisonType = JavaMethod("()Lcom/onesignal/core/internal/operations/GroupComparisonType;")
    getCanStartExecute = JavaMethod("()Z")
    translateIds = JavaMethod("(Ljava/util/Map;)V")
    getExistingOnesignalId = JavaMethod("()Ljava/lang/String;")
    setExistingOnesignalId$com_onesignal_core = JavaMethod("(Ljava/lang/String;)V")

class PurchaseInfo(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/operations/PurchaseInfo"
    __javaconstructor__ = [("(Ljava/lang/String;Ljava/lang/String;Ljava/math/BigDecimal;)V", False), ("()V", False)]
    getSku = JavaMethod("()Ljava/lang/String;")
    getIso = JavaMethod("()Ljava/lang/String;")
    getAmount = JavaMethod("()Ljava/math/BigDecimal;")

class RefreshUserOperation(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/operations/RefreshUserOperation"
    __javaconstructor__ = [("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V", False), ("()V", False)]
    getOnesignalId = JavaMethod("()Ljava/lang/String;")
    getAppId = JavaMethod("()Ljava/lang/String;")
    getApplyToRecordId = JavaMethod("()Ljava/lang/String;")
    getCreateComparisonKey = JavaMethod("()Ljava/lang/String;")
    getModifyComparisonKey = JavaMethod("()Ljava/lang/String;")
    getGroupComparisonType = JavaMethod("()Lcom/onesignal/core/internal/operations/GroupComparisonType;")
    getCanStartExecute = JavaMethod("()Z")
    translateIds = JavaMethod("(Ljava/util/Map;)V")

class SetAliasOperation(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/operations/SetAliasOperation"
    __javaconstructor__ = [("()V", False), ("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V", False)]
    getOnesignalId = JavaMethod("()Ljava/lang/String;")
    getValue = JavaMethod("()Ljava/lang/String;")
    getAppId = JavaMethod("()Ljava/lang/String;")
    getApplyToRecordId = JavaMethod("()Ljava/lang/String;")
    getCreateComparisonKey = JavaMethod("()Ljava/lang/String;")
    getModifyComparisonKey = JavaMethod("()Ljava/lang/String;")
    getGroupComparisonType = JavaMethod("()Lcom/onesignal/core/internal/operations/GroupComparisonType;")
    getCanStartExecute = JavaMethod("()Z")
    translateIds = JavaMethod("(Ljava/util/Map;)V")
    getLabel = JavaMethod("()Ljava/lang/String;")

class SetPropertyOperation(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/operations/SetPropertyOperation"
    __javaconstructor__ = [("()V", False), ("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)V", False)]
    getOnesignalId = JavaMethod("()Ljava/lang/String;")
    getProperty = JavaMethod("()Ljava/lang/String;")
    getValue = JavaMethod("()Ljava/lang/Object;")
    getAppId = JavaMethod("()Ljava/lang/String;")
    getApplyToRecordId = JavaMethod("()Ljava/lang/String;")
    getCreateComparisonKey = JavaMethod("()Ljava/lang/String;")
    getModifyComparisonKey = JavaMethod("()Ljava/lang/String;")
    getGroupComparisonType = JavaMethod("()Lcom/onesignal/core/internal/operations/GroupComparisonType;")
    getCanStartExecute = JavaMethod("()Z")
    translateIds = JavaMethod("(Ljava/util/Map;)V")

class SetTagOperation(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/operations/SetTagOperation"
    __javaconstructor__ = [("()V", False), ("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V", False)]
    getOnesignalId = JavaMethod("()Ljava/lang/String;")
    getValue = JavaMethod("()Ljava/lang/String;")
    getKey = JavaMethod("()Ljava/lang/String;")
    getAppId = JavaMethod("()Ljava/lang/String;")
    getApplyToRecordId = JavaMethod("()Ljava/lang/String;")
    getCreateComparisonKey = JavaMethod("()Ljava/lang/String;")
    getModifyComparisonKey = JavaMethod("()Ljava/lang/String;")
    getGroupComparisonType = JavaMethod("()Lcom/onesignal/core/internal/operations/GroupComparisonType;")
    getCanStartExecute = JavaMethod("()Z")
    translateIds = JavaMethod("(Ljava/util/Map;)V")

class TrackCustomEventOperation(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/operations/TrackCustomEventOperation"
    __javaconstructor__ = [("()V", False), ("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JLjava/lang/String;Ljava/lang/String;)V", False)]
    getOnesignalId = JavaMethod("()Ljava/lang/String;")
    getAppId = JavaMethod("()Ljava/lang/String;")
    setEventProperties = JavaMethod("(Ljava/lang/String;)V")
    getEventProperties = JavaMethod("()Ljava/lang/String;")
    getTimeStamp = JavaMethod("()J")
    setEventName = JavaMethod("(Ljava/lang/String;)V")
    getEventName = JavaMethod("()Ljava/lang/String;")
    getApplyToRecordId = JavaMethod("()Ljava/lang/String;")
    getCreateComparisonKey = JavaMethod("()Ljava/lang/String;")
    getModifyComparisonKey = JavaMethod("()Ljava/lang/String;")
    getGroupComparisonType = JavaMethod("()Lcom/onesignal/core/internal/operations/GroupComparisonType;")
    getCanStartExecute = JavaMethod("()Z")
    translateIds = JavaMethod("(Ljava/util/Map;)V")

class TrackPurchaseOperation(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/operations/TrackPurchaseOperation"
    __javaconstructor__ = [("()V", False), ("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZLjava/math/BigDecimal;Ljava/util/List;)V", False)]
    getOnesignalId = JavaMethod("()Ljava/lang/String;")
    getAppId = JavaMethod("()Ljava/lang/String;")
    getTreatNewAsExisting = JavaMethod("()Z")
    getApplyToRecordId = JavaMethod("()Ljava/lang/String;")
    getCreateComparisonKey = JavaMethod("()Ljava/lang/String;")
    getModifyComparisonKey = JavaMethod("()Ljava/lang/String;")
    getGroupComparisonType = JavaMethod("()Lcom/onesignal/core/internal/operations/GroupComparisonType;")
    getCanStartExecute = JavaMethod("()Z")
    translateIds = JavaMethod("(Ljava/util/Map;)V")
    getAmountSpent = JavaMethod("()Ljava/math/BigDecimal;")
    getPurchases = JavaMethod("()Ljava/util/List;")

class TrackSessionEndOperation(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/operations/TrackSessionEndOperation"
    __javaconstructor__ = [("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;J)V", False), ("()V", False)]
    getOnesignalId = JavaMethod("()Ljava/lang/String;")
    getAppId = JavaMethod("()Ljava/lang/String;")
    getSessionTime = JavaMethod("()J")
    getApplyToRecordId = JavaMethod("()Ljava/lang/String;")
    getCreateComparisonKey = JavaMethod("()Ljava/lang/String;")
    getModifyComparisonKey = JavaMethod("()Ljava/lang/String;")
    getGroupComparisonType = JavaMethod("()Lcom/onesignal/core/internal/operations/GroupComparisonType;")
    getCanStartExecute = JavaMethod("()Z")
    translateIds = JavaMethod("(Ljava/util/Map;)V")

class TrackSessionStartOperation(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/operations/TrackSessionStartOperation"
    __javaconstructor__ = [("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V", False), ("()V", False)]
    getOnesignalId = JavaMethod("()Ljava/lang/String;")
    getAppId = JavaMethod("()Ljava/lang/String;")
    getApplyToRecordId = JavaMethod("()Ljava/lang/String;")
    getCreateComparisonKey = JavaMethod("()Ljava/lang/String;")
    getModifyComparisonKey = JavaMethod("()Ljava/lang/String;")
    getGroupComparisonType = JavaMethod("()Lcom/onesignal/core/internal/operations/GroupComparisonType;")
    getCanStartExecute = JavaMethod("()Z")
    translateIds = JavaMethod("(Ljava/util/Map;)V")

class TransferSubscriptionOperation(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/operations/TransferSubscriptionOperation"
    __javaconstructor__ = [("()V", False), ("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V", False)]
    getOnesignalId = JavaMethod("()Ljava/lang/String;")
    getAppId = JavaMethod("()Ljava/lang/String;")
    getApplyToRecordId = JavaMethod("()Ljava/lang/String;")
    getCreateComparisonKey = JavaMethod("()Ljava/lang/String;")
    getModifyComparisonKey = JavaMethod("()Ljava/lang/String;")
    getGroupComparisonType = JavaMethod("()Lcom/onesignal/core/internal/operations/GroupComparisonType;")
    getCanStartExecute = JavaMethod("()Z")
    translateIds = JavaMethod("(Ljava/util/Map;)V")
    getSubscriptionId = JavaMethod("()Ljava/lang/String;")

class UpdateSubscriptionOperation(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/operations/UpdateSubscriptionOperation"
    __javaconstructor__ = [("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/onesignal/user/internal/subscriptions/SubscriptionType;ZLjava/lang/String;Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;)V", False), ("()V", False)]
    getOnesignalId = JavaMethod("()Ljava/lang/String;")
    getAddress = JavaMethod("()Ljava/lang/String;")
    getType = JavaMethod("()Lcom/onesignal/user/internal/subscriptions/SubscriptionType;")
    getStatus = JavaMethod("()Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    getAppId = JavaMethod("()Ljava/lang/String;")
    getApplyToRecordId = JavaMethod("()Ljava/lang/String;")
    getCreateComparisonKey = JavaMethod("()Ljava/lang/String;")
    getModifyComparisonKey = JavaMethod("()Ljava/lang/String;")
    getGroupComparisonType = JavaMethod("()Lcom/onesignal/core/internal/operations/GroupComparisonType;")
    getCanStartExecute = JavaMethod("()Z")
    translateIds = JavaMethod("(Ljava/util/Map;)V")
    getSubscriptionId = JavaMethod("()Ljava/lang/String;")
    getEnabled = JavaMethod("()Z")