from typing import Any, ClassVar, overload
from common.modeling.MapModel import MapModel

class PropertiesModel:
    def __init__(self) -> None: ...
    def setOnesignalId(self, p0: str) -> None: ...
    def getOnesignalId(self) -> str: ...
    def setLanguage(self, p0: str) -> None: ...
    def getTags(self) -> MapModel: ...
    def setCountry(self, p0: str) -> None: ...
    def getTimezone(self) -> str: ...
    def getLocationLatitude(self) -> float: ...
    def setLocationLatitude(self, p0: float) -> None: ...
    def getLocationLongitude(self) -> float: ...
    def setLocationLongitude(self, p0: float) -> None: ...
    def getLocationAccuracy(self) -> float: ...
    def setLocationAccuracy(self, p0: float) -> None: ...
    def getLocationType(self) -> int: ...
    def setLocationType(self, p0: int) -> None: ...
    def getLocationBackground(self) -> bool: ...
    def setLocationBackground(self, p0: bool) -> None: ...
    def getLocationTimestamp(self) -> int: ...
    def setLocationTimestamp(self, p0: int) -> None: ...
    def getLanguage(self) -> str: ...
    def setTimezone(self, p0: str) -> None: ...
    def getCountry(self) -> str: ...

from typing import Any, ClassVar, overload
from core.internal.preferences.IPreferencesService import IPreferencesService

class PropertiesModelStore:
    def __init__(self, p0: IPreferencesService) -> None: ...

