from typing import Any, ClassVar, overload
from core.internal.application.IApplicationService import IApplicationService
from core.internal.config.ConfigModelStore import ConfigModelStore
from core.internal.operations.IOperationRepo import IOperationRepo
from session.internal.session.ISessionService import ISessionService
from user.internal.identity.IdentityModelStore import IdentityModelStore

class UserRefreshService:
    def __init__(self, p0: IApplicationService, p1: ISessionService, p2: IOperationRepo, p3: ConfigModelStore, p4: IdentityModelStore) -> None: ...
    def start(self) -> None: ...
    def onSessionStarted(self) -> None: ...
    def onSessionActive(self) -> None: ...
    def onSessionEnded(self, p0: int) -> None: ...

