from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

class ISubscriptionChangedHandler(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/subscriptions/ISubscriptionChangedHandler"
    onSubscriptionAdded = JavaMethod("(Lcom/onesignal/user/subscriptions/ISubscription;)V")
    onSubscriptionChanged = JavaMethod("(Lcom/onesignal/user/subscriptions/ISubscription;Lcom/onesignal/common/modeling/ModelChangedArgs;)V")
    onSubscriptionRemoved = JavaMethod("(Lcom/onesignal/user/subscriptions/ISubscription;)V")

class ISubscriptionManager(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/subscriptions/ISubscriptionManager"
    getSubscriptions = JavaMethod("()Lcom/onesignal/user/internal/subscriptions/SubscriptionList;")
    getPushSubscriptionModel = JavaMethod("()Lcom/onesignal/user/internal/subscriptions/SubscriptionModel;")
    setSubscriptions = JavaMethod("(Lcom/onesignal/user/internal/subscriptions/SubscriptionList;)V")
    addEmailSubscription = JavaMethod("(Ljava/lang/String;)V")
    addOrUpdatePushSubscriptionToken = JavaMethod("(Ljava/lang/String;Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;)V")
    addSmsSubscription = JavaMethod("(Ljava/lang/String;)V")
    removeEmailSubscription = JavaMethod("(Ljava/lang/String;)V")
    removeSmsSubscription = JavaMethod("(Ljava/lang/String;)V")

class SubscriptionList(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/subscriptions/SubscriptionList"
    __javaconstructor__ = [("(Ljava/util/List;Lcom/onesignal/user/subscriptions/IPushSubscription;)V", False)]
    getPush = JavaMethod("()Lcom/onesignal/user/subscriptions/IPushSubscription;")
    getCollection = JavaMethod("()Ljava/util/List;")
    getEmails = JavaMethod("()Ljava/util/List;")
    getSmss = JavaMethod("()Ljava/util/List;")
    getByEmail = JavaMethod("(Ljava/lang/String;)Lcom/onesignal/user/subscriptions/IEmailSubscription;")
    getBySMS = JavaMethod("(Ljava/lang/String;)Lcom/onesignal/user/subscriptions/ISmsSubscription;")

class SubscriptionModel(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/subscriptions/SubscriptionModel"
    __javaconstructor__ = [("()V", False)]
    getType = JavaMethod("()Lcom/onesignal/user/internal/subscriptions/SubscriptionType;")
    getAddress = JavaMethod("()Ljava/lang/String;")
    getAppVersion = JavaMethod("()Ljava/lang/String;")
    setType = JavaMethod("(Lcom/onesignal/user/internal/subscriptions/SubscriptionType;)V")
    setDisabledInternally = JavaMethod("(Z)V")
    isDisabledInternally = JavaMethod("()Z")
    getStatus = JavaMethod("()Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    setSdk = JavaMethod("(Ljava/lang/String;)V")
    getSdk = JavaMethod("()Ljava/lang/String;")
    getDeviceOS = JavaMethod("()Ljava/lang/String;")
    setDeviceOS = JavaMethod("(Ljava/lang/String;)V")
    getCarrier = JavaMethod("()Ljava/lang/String;")
    setCarrier = JavaMethod("(Ljava/lang/String;)V")
    setAppVersion = JavaMethod("(Ljava/lang/String;)V")
    setStatus = JavaMethod("(Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;)V")
    getOptedIn = JavaMethod("()Z")
    setOptedIn = JavaMethod("(Z)V")
    setAddress = JavaMethod("(Ljava/lang/String;)V")

class SubscriptionModelStore(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/subscriptions/SubscriptionModelStore"
    __javaconstructor__ = [("(Lcom/onesignal/core/internal/preferences/IPreferencesService;)V", False)]
    replaceAll = JavaMethod("(Ljava/util/List;Ljava/lang/String;)V")
    transformJsonForPersistence = JavaMethod("(Lcom/onesignal/common/modeling/Model;Lorg/json/JSONObject;)Lorg/json/JSONObject;")

class SubscriptionStatus(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/subscriptions/SubscriptionStatus"
    Companion = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus$Companion;")
    SUBSCRIBED = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    NO_PERMISSION = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    UNSUBSCRIBE = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    MISSING_JETPACK_LIBRARY = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    MISSING_FIREBASE_FCM_LIBRARY = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    OUTDATED_JETPACK_LIBRARY = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    INVALID_FCM_SENDER_ID = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    OUTDATED_GOOGLE_PLAY_SERVICES_APP = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    FIREBASE_FCM_INIT_ERROR = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    FIREBASE_FCM_ERROR_IOEXCEPTION_SERVICE_NOT_AVAILABLE = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    FIREBASE_FCM_ERROR_IOEXCEPTION_OTHER = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    FIREBASE_FCM_ERROR_MISC_EXCEPTION = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    HMS_TOKEN_TIMEOUT = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    HMS_ARGUMENTS_INVALID = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    HMS_API_EXCEPTION_OTHER = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    MISSING_HMS_PUSHKIT_LIBRARY = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    FIREBASE_FCM_ERROR_IOEXCEPTION_AUTHENTICATION_FAILED = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    DISABLED_FROM_REST_API_DEFAULT_REASON = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    ERROR = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    values = JavaStaticMethod("()[Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    valueOf = JavaStaticMethod("(Ljava/lang/String;)Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    getValue = JavaMethod("()I")
    getEntries = JavaStaticMethod("()Lkotlin/enums/EnumEntries;")

    class Companion(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "com/onesignal/user/internal/subscriptions/SubscriptionStatus$Companion"
        __javaconstructor__ = [("(Lkotlin/jvm/internal/DefaultConstructorMarker;)V", False)]
        fromInt = JavaMethod("(I)Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    SUBSCRIBED = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    NO_PERMISSION = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    UNSUBSCRIBE = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    MISSING_JETPACK_LIBRARY = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    MISSING_FIREBASE_FCM_LIBRARY = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    OUTDATED_JETPACK_LIBRARY = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    INVALID_FCM_SENDER_ID = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    OUTDATED_GOOGLE_PLAY_SERVICES_APP = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    FIREBASE_FCM_INIT_ERROR = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    FIREBASE_FCM_ERROR_IOEXCEPTION_SERVICE_NOT_AVAILABLE = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    FIREBASE_FCM_ERROR_IOEXCEPTION_OTHER = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    FIREBASE_FCM_ERROR_MISC_EXCEPTION = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    HMS_TOKEN_TIMEOUT = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    HMS_ARGUMENTS_INVALID = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    HMS_API_EXCEPTION_OTHER = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    MISSING_HMS_PUSHKIT_LIBRARY = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    FIREBASE_FCM_ERROR_IOEXCEPTION_AUTHENTICATION_FAILED = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    DISABLED_FROM_REST_API_DEFAULT_REASON = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")
    ERROR = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionStatus;")

class SubscriptionType(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "com/onesignal/user/internal/subscriptions/SubscriptionType"
    EMAIL = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionType;")
    SMS = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionType;")
    PUSH = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionType;")
    values = JavaStaticMethod("()[Lcom/onesignal/user/internal/subscriptions/SubscriptionType;")
    valueOf = JavaStaticMethod("(Ljava/lang/String;)Lcom/onesignal/user/internal/subscriptions/SubscriptionType;")
    getEntries = JavaStaticMethod("()Lkotlin/enums/EnumEntries;")
    EMAIL = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionType;")
    SMS = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionType;")
    PUSH = JavaStaticField("Lcom/onesignal/user/internal/subscriptions/SubscriptionType;")