from typing import Any, ClassVar, overload
from debug.ILogListener import ILogListener
from debug.LogLevel import LogLevel

class DebugManager:
    def __init__(self) -> None: ...
    def getLogLevel(self) -> LogLevel: ...
    def setLogLevel(self, p0: LogLevel) -> None: ...
    def getAlertLevel(self) -> LogLevel: ...
    def setAlertLevel(self, p0: LogLevel) -> None: ...
    def addLogListener(self, p0: ILogListener) -> None: ...
    def removeLogListener(self, p0: ILogListener) -> None: ...

